# Generated by opsdir from env=prod,cloud=target,ou=environments,dc=ciam-ops
# Providers and inputs
# Do not edit. Change the operations directory (under an approved change) and re-render.

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
}

provider "azurerm" {
  features {
  }
  subscription_id = var.subscription_id
}

variable "subscription_id" {
  type    = string
  default = "00000000-0000-0000-0000-000000000000"
}

variable "admin_ssh_public_key" {
  type = string
}
