"""HAProxy in front of an environment's service names: haproxy.cfg shaped by each service name's traffic policy,
and the play writing it with each terminating frontend's TLS bundle (the key read at run time)."""
import pathlib
import subprocess

import pytest
from ansible_yaml import load

from opsdir.connectors.registry import services
from opsdir_adapter_haproxy.config import haproxy_cfg
from opsdir_adapter_haproxy.render import render
from network_fixtures import model
from pki_samples import CA_PEM
from edge_samples import KEY, alpha_with_policy as _alpha

ROOT = pathlib.Path(__file__).resolve().parents[3]
def test_a_terminating_front_with_cookie_stickiness_and_an_http_check():
    cfg = haproxy_cfg(_alpha(KEY))
    assert ("frontend fe_svc_sso_443\n"
            "    bind 10.1.9.10:443 ssl crt /etc/haproxy/certs/svc-sso.pem ssl-min-ver TLSv1.2\n"
            "    mode http\n    option forwardfor\n    timeout client 120s\n    default_backend be_svc_sso_443\n\n"
            "backend be_svc_sso_443\n    mode http\n    balance roundrobin\n    option httpchk GET /health\n"
            "    cookie SERVERID insert indirect nocache\n    timeout server 120s\n"
            "    server web-1 web-1.example.test:443 check cookie s0\n") in cfg


def test_without_a_policy_tls_passes_through():
    _, alpha, _ = model()
    cfg = haproxy_cfg(alpha)
    assert "bind *:443\n    mode tcp\n" in cfg and "server web-1 web-1.example.test:443 check\n" in cfg


def test_the_play_writes_each_bundle_with_its_key_read_at_run_time():
    files = render(_alpha(KEY), services())
    (play,) = load(files["ansible/haproxy.yml"])
    assert play["hosts"] == "load_balancer"
    key = '{{ lookup("amazon.aws.secretsmanager_secret", "ciam/sso-tls-key") }}'
    assert play["vars"] == {"ciam_haproxy_bundles": [{"name": "svc-sso", "cert": CA_PEM, "key": key}],
                            "ciam_haproxy_missing": []}
    assert files["ansible/files/haproxy.cfg"].startswith("# Generated by opsdir from env=prod,cloud=alpha")


def test_a_bundle_the_record_cant_complete_stops_the_play():
    (play,) = load(render(_alpha(), services())["ansible/haproxy.yml"])
    assert play["vars"]["ciam_haproxy_missing"] == ["svc-sso: no binding of key role sso-tls-key in alpha/prod"]


@pytest.mark.ansible
@pytest.mark.skipif(not (ROOT / "tools" / "ansible" / "venv" / "bin" / "ansible-playbook").exists(),
                    reason="no tools/ansible (opsdir/scripts/fetch-tools.sh)")
def test_the_play_passes_ansibles_own_checks(tmp_path):
    from opsdir_adapter_ansible.render import render as ansible
    alpha = _alpha(KEY)
    for path, text in {**ansible(alpha, services()), **render(alpha, services())}.items():
        (tmp_path / path).parent.mkdir(parents=True, exist_ok=True)
        (tmp_path / path).write_text(text)
    done = subprocess.run([str(ROOT / "opsdir" / "scripts" / "validate-ansible.sh"), str(tmp_path)],
                          capture_output=True, text=True)
    assert done.returncode == 0 and "haproxy.yml (syntax)" in done.stdout, done.stdout + done.stderr


def test_a_target_declaring_haproxy_without_load_balancer_servers_is_blocked():
    from types import SimpleNamespace
    from opsdir.core.environment import StackComponent
    from opsdir_adapter_haproxy.checks import check_hosts
    _, alpha, _ = model()
    declared = alpha._replace(stack=(*alpha.stack, StackComponent("load-balancer", "haproxy", None, None)))
    ctx = SimpleNamespace(d=alpha.d, src=alpha, dst=declared)
    (blocker,) = check_hosts(ctx).blockers
    assert "records no server of role `load-balancer`" in blocker[1]
    assert not check_hosts(SimpleNamespace(d=alpha.d, src=alpha, dst=alpha)).blockers


def test_the_play_installs_haproxy_lets_selinux_allow_its_ports_and_pins_what_it_needs():
    files = render(_alpha(KEY), services())
    (play,) = load(files["ansible/haproxy.yml"])
    tasks = {t["name"]: t for t in play["tasks"]}
    assert play["tasks"][0]["ansible.builtin.package"] == {"name": "haproxy", "state": "present"}
    selinux = tasks["SELinux lets HAProxy bind and connect to the service names' ports"]
    assert selinux["ansible.posix.seboolean"] == {"name": "haproxy_connect_any", "state": True, "persistent": True}
    needs = load(files["ansible/requirements-haproxy.yml"])["collections"]
    assert {c["name"] for c in needs} == {"ansible.posix", "amazon.aws"}       # the key's lookup is pinned too


def test_passthrough_with_an_http_check_checks_over_tls():
    from edge_samples import POLICIES
    policy = (f"dn: {POLICIES}\nobjectClass: top\nobjectClass: organizationalUnit\nou: edge-policies\n",
              f"dn: cn=sso,{POLICIES}\nobjectClass: top\nobjectClass: ciamObject\nobjectClass: ciamTrafficPolicy\n"
              "cn: sso\nciamServiceRole: sso-service\nciamTlsMode: passthrough\nciamHealthProtocol: https\n"
              "ciamHealthPath: /health\n")
    _, alpha, _ = model(tree=policy)
    cfg = haproxy_cfg(alpha)
    assert "    option httpchk GET /health\n" in cfg
    assert "server web-1 web-1.example.test:443 check check-ssl verify none\n" in cfg     # as the policy validates


def test_two_names_on_the_same_address_and_port_the_later_isnt_rendered_and_is_blocked():
    from types import SimpleNamespace
    from opsdir.core.environment import StackComponent
    from opsdir_adapter_haproxy.checks import check_binds
    from network_fixtures import ALPHA, entry
    other = entry(ALPHA, "svc-api", "ciamServiceName", ciamBindingRole="api-service", ciamFqdn="api.example.test",
                  ciamTargetRole="web", ciamPort="443")
    lost = entry(ALPHA, "web-x", "ciamServer", ciamServerRole="web")
    _, alpha, _ = model(alpha=(other, lost))
    cfg = haproxy_cfg(alpha)
    assert "# frontend fe_svc_sso_443 not rendered: *:443 is svc-api's" in cfg       # record order: svc-api first
    assert "frontend fe_svc_sso_443\n" not in cfg
    assert "    # UNBOUND:web-x-address: server web-x has no address or host name recorded" in cfg
    declared = alpha._replace(stack=(*alpha.stack, StackComponent("load-balancer", "haproxy", None, None)))
    (blocker,) = check_binds(SimpleNamespace(d=alpha.d, src=alpha, dst=declared)).blockers
    assert blocker[1].startswith("alpha/prod: service name `sso.example.test` and `api.example.test` would both "
                                 "listen on every address:443")
