# Generated by opsdir from env=prod,cloud=source,ou=environments,dc=ciam-ops
# AWS infrastructure for the CIAM platform
# Do not edit. Change the operations directory (under an approved change) and re-render.

data "aws_vpc" "main" {
  id = "vpc-0a1b2c3d4e5f67890"
}

data "aws_subnet" "subnet_am_a" {
  id = "subnet-0c77d88e99fa00b1a"
}

data "aws_subnet" "subnet_am_b" {
  id = "subnet-0c77d88e99fa00b1b"
}

data "aws_subnet" "subnet_ds_a" {
  id = "subnet-0a11b22c33d44e55a"
}

data "aws_subnet" "subnet_ds_b" {
  id = "subnet-0a11b22c33d44e55b"
}

data "aws_subnet" "subnet_ds_c" {
  id = "subnet-0a11b22c33d44e55c"
}

data "aws_subnet" "subnet_idm_a" {
  id = "subnet-0d88e99fa00b11c2a"
}

data "aws_subnet" "subnet_ig_a" {
  id = "subnet-0e99fa00b11c22d3a"
}

data "aws_subnet" "subnet_pf_a" {
  id = "subnet-0f66e77d88c99b00a"
}

data "aws_subnet" "subnet_pf_b" {
  id = "subnet-0f66e77d88c99b00b"
}

resource "aws_security_group" "am" {
  name        = "ciam-prod-am"
  description = "CIAM am (source/prod)"
  vpc_id      = data.aws_vpc.main.id
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "aws_security_group" "ds" {
  name        = "ciam-prod-ds"
  description = "CIAM ds (source/prod)"
  vpc_id      = data.aws_vpc.main.id
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "aws_security_group" "idm" {
  name        = "ciam-prod-idm"
  description = "CIAM idm (source/prod)"
  vpc_id      = data.aws_vpc.main.id
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "aws_security_group" "ig" {
  name        = "ciam-prod-ig"
  description = "CIAM ig (source/prod)"
  vpc_id      = data.aws_vpc.main.id
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "aws_security_group" "pf_admin" {
  name        = "ciam-prod-pf-admin"
  description = "CIAM pf-admin (source/prod)"
  vpc_id      = data.aws_vpc.main.id
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "aws_security_group" "pf_engine" {
  name        = "ciam-prod-pf-engine"
  description = "CIAM pf-engine (source/prod)"
  vpc_id      = data.aws_vpc.main.id
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "aws_vpc_security_group_ingress_rule" "fw_admin_0_4444" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.20.9.0/28"
  from_port         = 4444
  to_port           = 4444
  ip_protocol       = "tcp"
  description       = "fw-admin (fw-admin)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_apps_public_0_443" {
  security_group_id = aws_security_group.ig.id
  cidr_ipv4         = "0.0.0.0/0"
  from_port         = 443
  to_port           = 443
  ip_protocol       = "tcp"
  description       = "fw-apps-public (fw-apps-public)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_customer_portal_0_1636" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.30.8.0/24"
  from_port         = 1636
  to_port           = 1636
  ip_protocol       = "tcp"
  description       = "consumer customer-portal-svc (fw-customer-portal)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_idm_sync_0_1636" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.20.6.0/24"
  from_port         = 1636
  to_port           = 1636
  ip_protocol       = "tcp"
  description       = "consumer idm-sync (fw-idm-sync)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_legacy_rptuser_0_1636" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.40.7.22/32"
  from_port         = 1636
  to_port           = 1636
  ip_protocol       = "tcp"
  description       = "consumer legacy-rptuser (fw-legacy-rptuser)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_login_public_0_443" {
  security_group_id = aws_security_group.am.id
  cidr_ipv4         = "0.0.0.0/0"
  from_port         = 443
  to_port           = 443
  ip_protocol       = "tcp"
  description       = "fw-login-public (fw-login-public)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_mro_batch_0_1636" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.40.12.0/24"
  from_port         = 1636
  to_port           = 1636
  ip_protocol       = "tcp"
  description       = "consumer mro-batch-export (fw-mro-batch)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_pf_cluster_0_7600" {
  security_group_id = aws_security_group.pf_engine.id
  cidr_ipv4         = "10.20.4.0/24"
  from_port         = 7600
  to_port           = 7600
  ip_protocol       = "tcp"
  description       = "fw-pf-cluster (fw-pf-cluster)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_pf_cluster_0_7700" {
  security_group_id = aws_security_group.pf_engine.id
  cidr_ipv4         = "10.20.4.0/24"
  from_port         = 7700
  to_port           = 7700
  ip_protocol       = "tcp"
  description       = "fw-pf-cluster (fw-pf-cluster)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_pf_cluster_1_7600" {
  security_group_id = aws_security_group.pf_engine.id
  cidr_ipv4         = "10.20.5.0/24"
  from_port         = 7600
  to_port           = 7600
  ip_protocol       = "tcp"
  description       = "fw-pf-cluster (fw-pf-cluster)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_pf_cluster_1_7700" {
  security_group_id = aws_security_group.pf_engine.id
  cidr_ipv4         = "10.20.5.0/24"
  from_port         = 7700
  to_port           = 7700
  ip_protocol       = "tcp"
  description       = "fw-pf-cluster (fw-pf-cluster)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_pf_cluster_admin_0_7600" {
  security_group_id = aws_security_group.pf_admin.id
  cidr_ipv4         = "10.20.4.0/24"
  from_port         = 7600
  to_port           = 7600
  ip_protocol       = "tcp"
  description       = "fw-pf-cluster-admin (fw-pf-cluster-admin)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_pf_cluster_admin_0_7700" {
  security_group_id = aws_security_group.pf_admin.id
  cidr_ipv4         = "10.20.4.0/24"
  from_port         = 7700
  to_port           = 7700
  ip_protocol       = "tcp"
  description       = "fw-pf-cluster-admin (fw-pf-cluster-admin)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_pf_cluster_admin_1_7600" {
  security_group_id = aws_security_group.pf_admin.id
  cidr_ipv4         = "10.20.5.0/24"
  from_port         = 7600
  to_port           = 7600
  ip_protocol       = "tcp"
  description       = "fw-pf-cluster-admin (fw-pf-cluster-admin)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_pf_cluster_admin_1_7700" {
  security_group_id = aws_security_group.pf_admin.id
  cidr_ipv4         = "10.20.5.0/24"
  from_port         = 7700
  to_port           = 7700
  ip_protocol       = "tcp"
  description       = "fw-pf-cluster-admin (fw-pf-cluster-admin)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_pf_ds_svc_0_1636" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.20.4.0/24"
  from_port         = 1636
  to_port           = 1636
  ip_protocol       = "tcp"
  description       = "consumer pf-ds-svc (fw-pf-ds-svc)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_pf_ds_svc_1_1636" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.20.5.0/24"
  from_port         = 1636
  to_port           = 1636
  ip_protocol       = "tcp"
  description       = "consumer pf-ds-svc (fw-pf-ds-svc)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_replication_0_8989" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.20.1.0/24"
  from_port         = 8989
  to_port           = 8989
  ip_protocol       = "tcp"
  description       = "fw-replication (fw-replication)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_replication_1_8989" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.20.2.0/24"
  from_port         = 8989
  to_port           = 8989
  ip_protocol       = "tcp"
  description       = "fw-replication (fw-replication)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_replication_2_8989" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.20.3.0/24"
  from_port         = 8989
  to_port           = 8989
  ip_protocol       = "tcp"
  description       = "fw-replication (fw-replication)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_replication_3_8989" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.60.1.0/24"
  from_port         = 8989
  to_port           = 8989
  ip_protocol       = "tcp"
  description       = "fw-replication (fw-replication)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_sso_public_0_443" {
  security_group_id = aws_security_group.pf_engine.id
  cidr_ipv4         = "0.0.0.0/0"
  from_port         = 443
  to_port           = 443
  ip_protocol       = "tcp"
  description       = "fw-sso-public (fw-sso-public)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_supplier_portal_0_1636" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.31.2.0/24"
  from_port         = 1636
  to_port           = 1636
  ip_protocol       = "tcp"
  description       = "consumer supplier-portal-svc (fw-supplier-portal)"
}

resource "aws_iam_role" "identity_ds" {
  name = "ciam-prod-ds"
  assume_role_policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Effect" : "Allow",
        "Principal" : {
          "Service" : "ec2.amazonaws.com"
        },
        "Action" : "sts:AssumeRole"
      }
    ]
  })
  tags = {
    Principal = "pingds"
    Role      = "identity-ds"
    ManagedBy = "opsdir"
  }
}

resource "aws_iam_role_policy" "identity_ds" {
  name = "ciam-prod-ds-permissions"
  role = aws_iam_role.identity_ds.id
  policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Sid" : "ReadSecretDsRootPassword",
        "Effect" : "Allow",
        "Action" : [
          "secretsmanager:GetSecretValue"
        ],
        "Resource" : [
          "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/ds-root-password-??????"
        ]
      },
      {
        "Sid" : "UseKeyDiskEncryption",
        "Effect" : "Allow",
        "Action" : [
          "kms:Decrypt",
          "kms:Encrypt",
          "kms:GenerateDataKey"
        ],
        "Resource" : [
          "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
        ]
      },
      {
        "Sid" : "WriteLogsAuditLogs",
        "Effect" : "Allow",
        "Action" : [
          "logs:PutLogEvents",
          "logs:CreateLogStream"
        ],
        "Resource" : [
          "arn:aws:logs:us-east-1:111122223333:log-group:/ciam/prod/audit:*",
          "arn:aws:logs:us-east-1:111122223333:log-group:/ciam/prod/audit"
        ]
      },
      {
        "Sid" : "WriteStorageBackupTarget",
        "Effect" : "Allow",
        "Action" : [
          "s3:PutObject"
        ],
        "Resource" : [
          "arn:aws:s3:::example-aero-ciam-prod-ds-backups/*",
          "arn:aws:s3:::example-aero-ciam-prod-ds-backups"
        ]
      }
    ]
  })
}

resource "aws_iam_instance_profile" "identity_ds" {
  name = "ciam-prod-ds"
  role = aws_iam_role.identity_ds.name
}

resource "aws_iam_role" "identity_pf" {
  name = "ciam-prod-pf"
  assume_role_policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Effect" : "Allow",
        "Principal" : {
          "Service" : "ec2.amazonaws.com"
        },
        "Action" : "sts:AssumeRole"
      }
    ]
  })
  tags = {
    Principal = "pingfederate"
    Role      = "identity-pf"
    ManagedBy = "opsdir"
  }
}

resource "aws_iam_role_policy" "identity_pf" {
  name = "ciam-prod-pf-permissions"
  role = aws_iam_role.identity_pf.id
  policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Sid" : "ReadSecretPfAdminPassword",
        "Effect" : "Allow",
        "Action" : [
          "secretsmanager:GetSecretValue"
        ],
        "Resource" : [
          "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/pf-admin-password-??????"
        ]
      },
      {
        "Sid" : "ReadSecretPfDsBindPassword",
        "Effect" : "Allow",
        "Action" : [
          "secretsmanager:GetSecretValue"
        ],
        "Resource" : [
          "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/pf-ds-bind-password-??????"
        ]
      },
      {
        "Sid" : "ReadSecretPfSigningKey",
        "Effect" : "Allow",
        "Action" : [
          "secretsmanager:GetSecretValue"
        ],
        "Resource" : [
          "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/pf-signing-key-??????"
        ]
      },
      {
        "Sid" : "WriteLogsAuditLogs",
        "Effect" : "Allow",
        "Action" : [
          "logs:PutLogEvents",
          "logs:CreateLogStream"
        ],
        "Resource" : [
          "arn:aws:logs:us-east-1:111122223333:log-group:/ciam/prod/audit:*",
          "arn:aws:logs:us-east-1:111122223333:log-group:/ciam/prod/audit"
        ]
      }
    ]
  })
}

resource "aws_iam_instance_profile" "identity_pf" {
  name = "ciam-prod-pf"
  role = aws_iam_role.identity_pf.name
}

resource "aws_instance" "am_1" {
  ami                    = "ami-0a9b8c7d6e5f40321"
  instance_type          = "m6i.large"
  subnet_id              = data.aws_subnet.subnet_am_a.id
  private_ip             = "10.20.7.21"
  vpc_security_group_ids = [aws_security_group.am.id]
  root_block_device {
    encrypted  = true
    kms_key_id = "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
  }
  tags = {
    Name      = "am-1"
    Role      = "am"
    Hostname  = "am-1.aws.internal.example-aero.test"
    Product   = "PingAM 7.5.1"
    ManagedBy = "opsdir"
  }
}

resource "aws_instance" "am_2" {
  ami                    = "ami-0a9b8c7d6e5f40321"
  instance_type          = "m6i.large"
  subnet_id              = data.aws_subnet.subnet_am_b.id
  private_ip             = "10.20.8.21"
  vpc_security_group_ids = [aws_security_group.am.id]
  root_block_device {
    encrypted  = true
    kms_key_id = "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
  }
  tags = {
    Name      = "am-2"
    Role      = "am"
    Hostname  = "am-2.aws.internal.example-aero.test"
    Product   = "PingAM 7.5.1"
    ManagedBy = "opsdir"
  }
}

resource "aws_instance" "ds_1" {
  ami                    = "ami-0abcdef1234567890"
  instance_type          = "m6i.xlarge"
  subnet_id              = data.aws_subnet.subnet_ds_a.id
  private_ip             = "10.20.1.11"
  iam_instance_profile   = aws_iam_instance_profile.identity_ds.name
  vpc_security_group_ids = [aws_security_group.ds.id]
  root_block_device {
    encrypted  = true
    kms_key_id = "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
  }
  tags = {
    Name      = "ds-1"
    Role      = "ds"
    Hostname  = "ds-1.aws.internal.example-aero.test"
    Product   = "PingDS 7.5.1"
    ManagedBy = "opsdir"
  }
}

resource "aws_instance" "ds_2" {
  ami                    = "ami-0abcdef1234567890"
  instance_type          = "m6i.xlarge"
  subnet_id              = data.aws_subnet.subnet_ds_b.id
  private_ip             = "10.20.2.11"
  iam_instance_profile   = aws_iam_instance_profile.identity_ds.name
  vpc_security_group_ids = [aws_security_group.ds.id]
  root_block_device {
    encrypted  = true
    kms_key_id = "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
  }
  tags = {
    Name      = "ds-2"
    Role      = "ds"
    Hostname  = "ds-2.aws.internal.example-aero.test"
    Product   = "PingDS 7.5.1"
    ManagedBy = "opsdir"
  }
}

resource "aws_instance" "ds_3" {
  ami                    = "ami-0abcdef1234567890"
  instance_type          = "m6i.xlarge"
  subnet_id              = data.aws_subnet.subnet_ds_c.id
  private_ip             = "10.20.3.11"
  iam_instance_profile   = aws_iam_instance_profile.identity_ds.name
  vpc_security_group_ids = [aws_security_group.ds.id]
  root_block_device {
    encrypted  = true
    kms_key_id = "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
  }
  tags = {
    Name      = "ds-3"
    Role      = "ds"
    Hostname  = "ds-3.aws.internal.example-aero.test"
    Product   = "PingDS 7.5.1"
    ManagedBy = "opsdir"
  }
}

resource "aws_instance" "idm_1" {
  ami                    = "ami-0b1c2d3e4f5a60987"
  instance_type          = "m6i.large"
  subnet_id              = data.aws_subnet.subnet_idm_a.id
  private_ip             = "10.20.6.21"
  vpc_security_group_ids = [aws_security_group.idm.id]
  root_block_device {
    encrypted  = true
    kms_key_id = "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
  }
  tags = {
    Name      = "idm-1"
    Role      = "idm"
    Hostname  = "idm-1.aws.internal.example-aero.test"
    Product   = "PingIDM 7.5.0"
    ManagedBy = "opsdir"
  }
}

resource "aws_instance" "ig_1" {
  ami                    = "ami-0c2d3e4f5a6b70123"
  instance_type          = "m6i.large"
  subnet_id              = data.aws_subnet.subnet_ig_a.id
  private_ip             = "10.20.10.21"
  vpc_security_group_ids = [aws_security_group.ig.id]
  root_block_device {
    encrypted  = true
    kms_key_id = "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
  }
  tags = {
    Name      = "ig-1"
    Role      = "ig"
    Hostname  = "ig-1.aws.internal.example-aero.test"
    Product   = "PingGateway 2024.11.0"
    ManagedBy = "opsdir"
  }
}

resource "aws_instance" "pf_admin_1" {
  ami                    = "ami-0fedcba9876543210"
  instance_type          = "m6i.large"
  subnet_id              = data.aws_subnet.subnet_pf_a.id
  private_ip             = "10.20.4.10"
  vpc_security_group_ids = [aws_security_group.pf_admin.id]
  root_block_device {
    encrypted  = true
    kms_key_id = "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
  }
  tags = {
    Name      = "pf-admin-1"
    Role      = "pf-admin"
    Hostname  = "pf-admin-1.aws.internal.example-aero.test"
    Product   = "PingFederate 12.1.4"
    ManagedBy = "opsdir"
  }
}

resource "aws_instance" "pf_engine_1" {
  ami                    = "ami-0fedcba9876543210"
  instance_type          = "m6i.large"
  subnet_id              = data.aws_subnet.subnet_pf_a.id
  private_ip             = "10.20.4.21"
  iam_instance_profile   = aws_iam_instance_profile.identity_pf.name
  vpc_security_group_ids = [aws_security_group.pf_engine.id]
  root_block_device {
    encrypted  = true
    kms_key_id = "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
  }
  tags = {
    Name      = "pf-engine-1"
    Role      = "pf-engine"
    Hostname  = "pf-engine-1.aws.internal.example-aero.test"
    Product   = "PingFederate 12.1.4"
    ManagedBy = "opsdir"
  }
}

resource "aws_instance" "pf_engine_2" {
  ami                    = "ami-0fedcba9876543210"
  instance_type          = "m6i.large"
  subnet_id              = data.aws_subnet.subnet_pf_b.id
  private_ip             = "10.20.5.21"
  iam_instance_profile   = aws_iam_instance_profile.identity_pf.name
  vpc_security_group_ids = [aws_security_group.pf_engine.id]
  root_block_device {
    encrypted  = true
    kms_key_id = "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
  }
  tags = {
    Name      = "pf-engine-2"
    Role      = "pf-engine"
    Hostname  = "pf-engine-2.aws.internal.example-aero.test"
    Product   = "PingFederate 12.1.4"
    ManagedBy = "opsdir"
  }
}

resource "aws_lb" "svc_apps" {
  name               = "ciam-prod-svc-apps"
  internal           = false
  load_balancer_type = "network"
  subnet_mapping {
    subnet_id     = data.aws_subnet.subnet_ig_a.id
    allocation_id = "eipalloc-0a1b2c3d4e5f60005"
  }
  tags = {
    Service   = "apps.example-aero.test"
    ManagedBy = "opsdir"
  }
}

resource "aws_lb_target_group" "svc_apps_443" {
  name        = "ciam-prod-svc-apps-443"
  port        = 443
  protocol    = "TCP"
  vpc_id      = data.aws_vpc.main.id
  target_type = "instance"
  health_check {
    protocol = "TCP"
  }
}

resource "aws_lb_target_group_attachment" "svc_apps_443_ig_1" {
  target_group_arn = aws_lb_target_group.svc_apps_443.arn
  target_id        = aws_instance.ig_1.id
  port             = 443
}

resource "aws_lb_listener" "svc_apps_443" {
  load_balancer_arn = aws_lb.svc_apps.arn
  port              = 443
  protocol          = "TCP"
  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.svc_apps_443.arn
  }
}

# `apps.example-aero.test` is in a zone corporate-dns runs: not rendered here (the plan drafts the request to them)

resource "aws_lb" "svc_ldaps" {
  name               = "ciam-prod-svc-ldaps"
  internal           = true
  load_balancer_type = "network"
  subnet_mapping {
    subnet_id            = data.aws_subnet.subnet_ds_a.id
    private_ipv4_address = "10.20.1.100"
  }
  subnet_mapping {
    subnet_id = data.aws_subnet.subnet_ds_b.id
  }
  subnet_mapping {
    subnet_id = data.aws_subnet.subnet_ds_c.id
  }
  tags = {
    Service   = "ldap.id.example-aero.test"
    ManagedBy = "opsdir"
  }
}

resource "aws_lb_target_group" "svc_ldaps_1636" {
  name        = "ciam-prod-svc-ldaps-1636"
  port        = 1636
  protocol    = "TCP"
  vpc_id      = data.aws_vpc.main.id
  target_type = "instance"
  health_check {
    protocol = "TCP"
  }
}

resource "aws_lb_target_group_attachment" "svc_ldaps_1636_ds_1" {
  target_group_arn = aws_lb_target_group.svc_ldaps_1636.arn
  target_id        = aws_instance.ds_1.id
  port             = 1636
}

resource "aws_lb_target_group_attachment" "svc_ldaps_1636_ds_2" {
  target_group_arn = aws_lb_target_group.svc_ldaps_1636.arn
  target_id        = aws_instance.ds_2.id
  port             = 1636
}

resource "aws_lb_target_group_attachment" "svc_ldaps_1636_ds_3" {
  target_group_arn = aws_lb_target_group.svc_ldaps_1636.arn
  target_id        = aws_instance.ds_3.id
  port             = 1636
}

resource "aws_lb_listener" "svc_ldaps_1636" {
  load_balancer_arn = aws_lb.svc_ldaps.arn
  port              = 1636
  protocol          = "TCP"
  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.svc_ldaps_1636.arn
  }
}

resource "aws_route53_record" "svc_ldaps" {
  zone_id = "Z0EXAMPLE1PRIVATE"
  name    = "ldap.id.example-aero.test"
  type    = "A"
  # an alias takes the load balancer's TTL; the recorded 60 s doesn't apply
  alias {
    name                   = aws_lb.svc_ldaps.dns_name
    zone_id                = aws_lb.svc_ldaps.zone_id
    evaluate_target_health = true
  }
}

resource "aws_security_group" "svc_login_alb" {
  name        = "ciam-prod-svc-login-alb"
  description = "CIAM login.example-aero.test load balancer (source/prod)"
  vpc_id      = data.aws_vpc.main.id
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "aws_vpc_security_group_ingress_rule" "svc_login_alb_fw_login_public_0_443" {
  security_group_id = aws_security_group.svc_login_alb.id
  cidr_ipv4         = "0.0.0.0/0"
  from_port         = 443
  to_port           = 443
  ip_protocol       = "tcp"
  description       = "clients (fw-login-public)"
}

resource "aws_vpc_security_group_egress_rule" "svc_login_alb_to_servers_443" {
  security_group_id            = aws_security_group.svc_login_alb.id
  referenced_security_group_id = aws_security_group.am.id
  from_port                    = 443
  to_port                      = 443
  ip_protocol                  = "tcp"
  description                  = "to the servers"
}

resource "aws_vpc_security_group_ingress_rule" "svc_login_servers_from_alb_443" {
  security_group_id            = aws_security_group.am.id
  referenced_security_group_id = aws_security_group.svc_login_alb.id
  from_port                    = 443
  to_port                      = 443
  ip_protocol                  = "tcp"
  description                  = "from the login.example-aero.test load balancer"
}

resource "aws_lb" "svc_login" {
  # an ALB's addresses are AWS's: frontend address 198.51.100.21 isn't kept
  name                       = "ciam-prod-svc-login"
  internal                   = false
  load_balancer_type         = "application"
  security_groups            = [aws_security_group.svc_login_alb.id]
  subnets                    = [data.aws_subnet.subnet_am_a.id, data.aws_subnet.subnet_am_b.id]
  drop_invalid_header_fields = true
  tags = {
    Service   = "login.example-aero.test"
    ManagedBy = "opsdir"
  }
}

resource "aws_lb_target_group" "svc_login_443" {
  name        = "ciam-prod-svc-login-443"
  port        = 443
  protocol    = "HTTPS"
  vpc_id      = data.aws_vpc.main.id
  target_type = "instance"
  health_check {
    protocol = "HTTPS"
    path     = "/am/json/health/ready"
    matcher  = "200"
  }
  stickiness {
    type            = "lb_cookie"
    enabled         = true
    cookie_duration = 3600
  }
}

resource "aws_lb_target_group_attachment" "svc_login_443_am_1" {
  target_group_arn = aws_lb_target_group.svc_login_443.arn
  target_id        = aws_instance.am_1.id
  port             = 443
}

resource "aws_lb_target_group_attachment" "svc_login_443_am_2" {
  target_group_arn = aws_lb_target_group.svc_login_443.arn
  target_id        = aws_instance.am_2.id
  port             = 443
}

resource "aws_lb_listener" "svc_login_443" {
  load_balancer_arn = aws_lb.svc_login.arn
  port              = 443
  protocol          = "HTTPS"
  ssl_policy        = "ELBSecurityPolicy-TLS13-1-2-2021-06"
  # UNBOUND: no ACM certificate holds this service's certificate in this environment
  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.svc_login_443.arn
  }
}

resource "aws_wafv2_web_acl" "svc_login" {
  name  = "ciam-prod-svc_login"
  scope = "REGIONAL"
  default_action {
    allow {
    }
  }
  rule {
    name     = "rate-login"
    priority = 0
    action {
      block {
      }
    }
    statement {
      rate_based_statement {
        limit                 = 300
        evaluation_window_sec = 300
        aggregate_key_type    = "IP"
        scope_down_statement {
          regex_match_statement {
            regex_string = "^/am/json/realms/[^?#]+/authenticate$"
            field_to_match {
              uri_path {
              }
            }
            text_transformation {
              priority = 0
              type     = "NONE"
            }
          }
        }
      }
    }
    visibility_config {
      cloudwatch_metrics_enabled = true
      sampled_requests_enabled   = true
      metric_name                = "svc_login-rate-login"
    }
  }
  rule {
    name     = "rate-token"
    priority = 1
    action {
      block {
      }
    }
    statement {
      rate_based_statement {
        limit                 = 600
        evaluation_window_sec = 300
        aggregate_key_type    = "IP"
        scope_down_statement {
          or_statement {
            statement {
              regex_match_statement {
                regex_string = "^/am/oauth2/access_token$"
                field_to_match {
                  uri_path {
                  }
                }
                text_transformation {
                  priority = 0
                  type     = "NONE"
                }
              }
            }
            statement {
              regex_match_statement {
                regex_string = "^/am/oauth2/realms/[^?#]+/access_token$"
                field_to_match {
                  uri_path {
                  }
                }
                text_transformation {
                  priority = 0
                  type     = "NONE"
                }
              }
            }
          }
        }
      }
    }
    visibility_config {
      cloudwatch_metrics_enabled = true
      sampled_requests_enabled   = true
      metric_name                = "svc_login-rate-token"
    }
  }
  rule {
    name     = "core-rules"
    priority = 2
    override_action {
      none {
      }
    }
    statement {
      managed_rule_group_statement {
        name        = "AWSManagedRulesCommonRuleSet"
        vendor_name = "AWS"
        scope_down_statement {
          not_statement {
            statement {
              regex_match_statement {
                regex_string = "^/am/SSOPOST/metaAlias/[^?#]+$"
                field_to_match {
                  uri_path {
                  }
                }
                text_transformation {
                  priority = 0
                  type     = "NONE"
                }
              }
            }
          }
        }
        # exclusions: AWS can't skip one field of a managed group, so these endpoints are out of its scope
      }
    }
    visibility_config {
      cloudwatch_metrics_enabled = true
      sampled_requests_enabled   = true
      metric_name                = "svc_login-core-rules"
    }
  }
  rule {
    name     = "known-bad-inputs"
    priority = 3
    override_action {
      none {
      }
    }
    statement {
      managed_rule_group_statement {
        name        = "AWSManagedRulesKnownBadInputsRuleSet"
        vendor_name = "AWS"
      }
    }
    visibility_config {
      cloudwatch_metrics_enabled = true
      sampled_requests_enabled   = true
      metric_name                = "svc_login-known-bad-inputs"
    }
  }
  rule {
    name     = "bot-control"
    priority = 4
    override_action {
      none {
      }
    }
    statement {
      managed_rule_group_statement {
        name        = "AWSManagedRulesBotControlRuleSet"
        vendor_name = "AWS"
        managed_rule_group_configs {
          aws_managed_rules_bot_control_rule_set {
            inspection_level = "COMMON"
          }
        }
      }
    }
    visibility_config {
      cloudwatch_metrics_enabled = true
      sampled_requests_enabled   = true
      metric_name                = "svc_login-bot-control"
    }
  }
  visibility_config {
    cloudwatch_metrics_enabled = true
    sampled_requests_enabled   = true
    metric_name                = "svc_login-web-acl"
  }
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "aws_wafv2_web_acl_association" "svc_login" {
  resource_arn = aws_lb.svc_login.arn
  web_acl_arn  = aws_wafv2_web_acl.svc_login.arn
}

resource "aws_shield_protection" "svc_login" {
  # needs the account's Shield Advanced subscription
  name         = "svc_login"
  resource_arn = aws_lb.svc_login.arn
}

# `login.example-aero.test` is in a zone corporate-dns runs: not rendered here (the plan drafts the request to them)

resource "aws_security_group" "svc_sso_alb" {
  name        = "ciam-prod-svc-sso-alb"
  description = "CIAM sso.example-aero.test load balancer (source/prod)"
  vpc_id      = data.aws_vpc.main.id
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "aws_vpc_security_group_ingress_rule" "svc_sso_alb_fw_sso_public_0_443" {
  security_group_id = aws_security_group.svc_sso_alb.id
  cidr_ipv4         = "0.0.0.0/0"
  from_port         = 443
  to_port           = 443
  ip_protocol       = "tcp"
  description       = "clients (fw-sso-public)"
}

resource "aws_vpc_security_group_egress_rule" "svc_sso_alb_to_servers_443" {
  security_group_id            = aws_security_group.svc_sso_alb.id
  referenced_security_group_id = aws_security_group.pf_engine.id
  from_port                    = 443
  to_port                      = 443
  ip_protocol                  = "tcp"
  description                  = "to the servers"
}

resource "aws_vpc_security_group_ingress_rule" "svc_sso_servers_from_alb_443" {
  security_group_id            = aws_security_group.pf_engine.id
  referenced_security_group_id = aws_security_group.svc_sso_alb.id
  from_port                    = 443
  to_port                      = 443
  ip_protocol                  = "tcp"
  description                  = "from the sso.example-aero.test load balancer"
}

resource "aws_lb" "svc_sso" {
  # an ALB's addresses are AWS's: frontend address 198.51.100.20 isn't kept
  name                       = "ciam-prod-svc-sso"
  internal                   = false
  load_balancer_type         = "application"
  security_groups            = [aws_security_group.svc_sso_alb.id]
  subnets                    = [data.aws_subnet.subnet_pf_a.id, data.aws_subnet.subnet_pf_b.id]
  drop_invalid_header_fields = true
  tags = {
    Service   = "sso.example-aero.test"
    ManagedBy = "opsdir"
  }
}

resource "aws_lb_target_group" "svc_sso_443" {
  name        = "ciam-prod-svc-sso-443"
  port        = 443
  protocol    = "HTTPS"
  vpc_id      = data.aws_vpc.main.id
  target_type = "instance"
  health_check {
    protocol = "HTTPS"
    path     = "/pf/heartbeat.ping"
    matcher  = "200"
  }
  stickiness {
    type            = "lb_cookie"
    enabled         = true
    cookie_duration = 3600
  }
}

resource "aws_lb_target_group_attachment" "svc_sso_443_pf_engine_1" {
  target_group_arn = aws_lb_target_group.svc_sso_443.arn
  target_id        = aws_instance.pf_engine_1.id
  port             = 443
}

resource "aws_lb_target_group_attachment" "svc_sso_443_pf_engine_2" {
  target_group_arn = aws_lb_target_group.svc_sso_443.arn
  target_id        = aws_instance.pf_engine_2.id
  port             = 443
}

resource "aws_lb_listener" "svc_sso_443" {
  load_balancer_arn = aws_lb.svc_sso.arn
  port              = 443
  protocol          = "HTTPS"
  ssl_policy        = "ELBSecurityPolicy-TLS13-1-2-2021-06"
  certificate_arn   = "arn:aws:acm:us-east-1:111122223333:certificate/7f3e9d21-0000-4000-8000-0000000000a1"
  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.svc_sso_443.arn
  }
}

resource "aws_wafv2_web_acl" "svc_sso" {
  name  = "ciam-prod-svc_sso"
  scope = "REGIONAL"
  default_action {
    allow {
    }
  }
  rule {
    name     = "rate-login"
    priority = 0
    action {
      block {
      }
    }
    statement {
      rate_based_statement {
        limit                 = 300
        evaluation_window_sec = 300
        aggregate_key_type    = "IP"
        scope_down_statement {
          or_statement {
            statement {
              regex_match_statement {
                regex_string = "^/as/authorization\\.oauth2$"
                field_to_match {
                  uri_path {
                  }
                }
                text_transformation {
                  priority = 0
                  type     = "NONE"
                }
              }
            }
            statement {
              regex_match_statement {
                regex_string = "^/idp/SSO\\.saml2$"
                field_to_match {
                  uri_path {
                  }
                }
                text_transformation {
                  priority = 0
                  type     = "NONE"
                }
              }
            }
          }
        }
      }
    }
    visibility_config {
      cloudwatch_metrics_enabled = true
      sampled_requests_enabled   = true
      metric_name                = "svc_sso-rate-login"
    }
  }
  rule {
    name     = "rate-token"
    priority = 1
    action {
      block {
      }
    }
    statement {
      rate_based_statement {
        limit                 = 600
        evaluation_window_sec = 300
        aggregate_key_type    = "IP"
        scope_down_statement {
          regex_match_statement {
            regex_string = "^/as/token\\.oauth2$"
            field_to_match {
              uri_path {
              }
            }
            text_transformation {
              priority = 0
              type     = "NONE"
            }
          }
        }
      }
    }
    visibility_config {
      cloudwatch_metrics_enabled = true
      sampled_requests_enabled   = true
      metric_name                = "svc_sso-rate-token"
    }
  }
  rule {
    name     = "core-rules"
    priority = 2
    override_action {
      none {
      }
    }
    statement {
      managed_rule_group_statement {
        name        = "AWSManagedRulesCommonRuleSet"
        vendor_name = "AWS"
        scope_down_statement {
          not_statement {
            statement {
              or_statement {
                statement {
                  regex_match_statement {
                    regex_string = "^/idp/SSO\\.saml2$"
                    field_to_match {
                      uri_path {
                      }
                    }
                    text_transformation {
                      priority = 0
                      type     = "NONE"
                    }
                  }
                }
                statement {
                  regex_match_statement {
                    regex_string = "^/sp/ACS\\.saml2$"
                    field_to_match {
                      uri_path {
                      }
                    }
                    text_transformation {
                      priority = 0
                      type     = "NONE"
                    }
                  }
                }
              }
            }
          }
        }
        # exclusions: AWS can't skip one field of a managed group, so these endpoints are out of its scope
      }
    }
    visibility_config {
      cloudwatch_metrics_enabled = true
      sampled_requests_enabled   = true
      metric_name                = "svc_sso-core-rules"
    }
  }
  rule {
    name     = "known-bad-inputs"
    priority = 3
    override_action {
      none {
      }
    }
    statement {
      managed_rule_group_statement {
        name        = "AWSManagedRulesKnownBadInputsRuleSet"
        vendor_name = "AWS"
      }
    }
    visibility_config {
      cloudwatch_metrics_enabled = true
      sampled_requests_enabled   = true
      metric_name                = "svc_sso-known-bad-inputs"
    }
  }
  rule {
    name     = "bot-control"
    priority = 4
    override_action {
      none {
      }
    }
    statement {
      managed_rule_group_statement {
        name        = "AWSManagedRulesBotControlRuleSet"
        vendor_name = "AWS"
        managed_rule_group_configs {
          aws_managed_rules_bot_control_rule_set {
            inspection_level = "COMMON"
          }
        }
      }
    }
    visibility_config {
      cloudwatch_metrics_enabled = true
      sampled_requests_enabled   = true
      metric_name                = "svc_sso-bot-control"
    }
  }
  visibility_config {
    cloudwatch_metrics_enabled = true
    sampled_requests_enabled   = true
    metric_name                = "svc_sso-web-acl"
  }
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "aws_wafv2_web_acl_association" "svc_sso" {
  resource_arn = aws_lb.svc_sso.arn
  web_acl_arn  = aws_wafv2_web_acl.svc_sso.arn
}

resource "aws_shield_protection" "svc_sso" {
  # needs the account's Shield Advanced subscription
  name         = "svc_sso"
  resource_arn = aws_lb.svc_sso.arn
}

# `sso.example-aero.test` is in a zone corporate-dns runs: not rendered here (the plan drafts the request to them)

# Private endpoint 'pe-secrets' to secrets (reaches pf-admin-password, pf-signing-key, ds-root-password)

resource "aws_security_group" "pe_secrets_endpoint" {
  name        = "ciam-prod-pe-secrets"
  description = "CIAM private endpoint pe-secrets (source/prod)"
  vpc_id      = data.aws_vpc.main.id
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "aws_vpc_security_group_ingress_rule" "pe_secrets_endpoint_0" {
  security_group_id = aws_security_group.pe_secrets_endpoint.id
  cidr_ipv4         = "10.20.0.0/16"
  from_port         = 443
  to_port           = 443
  ip_protocol       = "tcp"
  description       = "the network to pe-secrets"
}

resource "aws_vpc_endpoint" "pe_secrets" {
  vpc_id              = data.aws_vpc.main.id
  service_name        = "com.amazonaws.us-east-1.secretsmanager"
  vpc_endpoint_type   = "Interface"
  subnet_ids          = [data.aws_subnet.subnet_ds_a.id, data.aws_subnet.subnet_ds_b.id, data.aws_subnet.subnet_ds_c.id, data.aws_subnet.subnet_pf_a.id, data.aws_subnet.subnet_pf_b.id]
  security_group_ids  = [aws_security_group.pe_secrets_endpoint.id]
  private_dns_enabled = true
  tags = {
    Name      = "pe-secrets"
    Role      = "private-secrets"
    ManagedBy = "opsdir"
  }
}

resource "aws_vpc_endpoint_service" "ldaps_link" {
  acceptance_required        = true
  network_load_balancer_arns = [aws_lb.svc_ldaps.arn]
  allowed_principals         = ["arn:aws:iam::444455556666:root"]
  tags = {
    Name      = "ldaps-link"
    Role      = "ldaps-endpoint-service"
    ManagedBy = "opsdir"
  }
}

# Egress firewall 'egress-firewall': reference this rule group from its firewall policy (arn:aws:network-firewall:us-east-1:111122223333:firewall-policy/ciam-prod-egress) (stateful_rule_group_reference)

# A domain list matches TLS SNI and HTTP Host only: email-smtp.us-east-1.amazonaws.com:587 isn't web traffic, so the policy's other stateful rules decide it

resource "aws_networkfirewall_rule_group" "egress_firewall_domains" {
  name        = "ciam-prod-egress-firewall-domains"
  type        = "STATEFUL"
  capacity    = 100
  description = "Sites the CIAM platform reaches (source/prod)"
  rule_group {
    rule_variables {
      ip_sets {
        key = "HOME_NET"
        ip_set {
          definition = ["10.20.0.0/16"]
        }
      }
    }
    rules_source {
      rules_source_list {
        generated_rules_type = "ALLOWLIST"
        target_types         = ["TLS_SNI", "HTTP_HOST"]
        targets              = ["ocsp.example-ca.test", "crl.example-ca.test", "metadata.skyline-air.test", "sso.harbor-mro.test", "email-smtp.us-east-1.amazonaws.com"]
      }
    }
  }
  tags = {
    Name           = "egress-firewall"
    Role           = "egress-firewall"
    ManagedBy      = "opsdir"
    FirewallPolicy = "arn:aws:network-firewall:us-east-1:111122223333:firewall-policy/ciam-prod-egress"
  }
}

variable "pf_grants_admin_username" {
  type        = string
  description = "The master user name of database pf-grants (role pf-grants-db)"
}

resource "aws_db_subnet_group" "pf_grants" {
  name       = "pf-grants"
  subnet_ids = [data.aws_subnet.subnet_pf_a.id, data.aws_subnet.subnet_pf_b.id]
  tags = {
    Name      = "pf-grants"
    Role      = "pf-grants-db"
    ManagedBy = "opsdir"
  }
}

resource "aws_security_group" "pf_grants_db" {
  name        = "ciam-prod-pf-grants-db"
  description = "CIAM database pf-grants-db (source/prod)"
  vpc_id      = data.aws_vpc.main.id
  tags = {
    Name      = "pf-grants"
    Role      = "pf-grants-db"
    ManagedBy = "opsdir"
  }
}

resource "aws_vpc_security_group_ingress_rule" "pf_grants_db_0" {
  security_group_id = aws_security_group.pf_grants_db.id
  cidr_ipv4         = "10.20.4.0/24"
  from_port         = 5432
  to_port           = 5432
  ip_protocol       = "tcp"
  description       = "clients of database pf-grants (pf-grants-db)"
}

resource "aws_vpc_security_group_ingress_rule" "pf_grants_db_1" {
  security_group_id = aws_security_group.pf_grants_db.id
  cidr_ipv4         = "10.20.5.0/24"
  from_port         = 5432
  to_port           = 5432
  ip_protocol       = "tcp"
  description       = "clients of database pf-grants (pf-grants-db)"
}

resource "aws_db_parameter_group" "pf_grants" {
  name   = "pf-grants"
  family = "postgres16"
  parameter {
    name  = "idle_in_transaction_session_timeout"
    value = "60000"
  }
  parameter {
    name  = "log_min_duration_statement"
    value = "1000"
  }
  tags = {
    Name      = "pf-grants"
    Role      = "pf-grants-db"
    ManagedBy = "opsdir"
  }
}

resource "aws_db_instance" "pf_grants" {
  identifier                  = "pf-grants"
  engine                      = "postgres"
  engine_version              = "16.4"
  instance_class              = "db.m6i.large"
  allocated_storage           = 100
  db_subnet_group_name        = aws_db_subnet_group.pf_grants.name
  vpc_security_group_ids      = [aws_security_group.pf_grants_db.id]
  parameter_group_name        = aws_db_parameter_group.pf_grants.name
  username                    = var.pf_grants_admin_username
  multi_az                    = true
  publicly_accessible         = false
  manage_master_user_password = true
  port                        = 5432
  storage_encrypted           = true
  kms_key_id                  = "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
  backup_retention_period     = 14
  deletion_protection         = true
  tags = {
    Name      = "pf-grants"
    Role      = "pf-grants-db"
    ManagedBy = "opsdir"
  }
}

import {
  to = aws_db_instance.pf_grants
  id = "pf-grants"
}

resource "aws_s3_bucket" "backup" {
  bucket              = "example-aero-ciam-prod-ds-backups"
  object_lock_enabled = true
  tags = {
    Name      = "backup"
    Role      = "backup-target"
    ManagedBy = "opsdir"
  }
}

resource "aws_s3_bucket_versioning" "backup" {
  bucket = aws_s3_bucket.backup.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_object_lock_configuration" "backup" {
  bucket = aws_s3_bucket.backup.id
  rule {
    default_retention {
      mode = "COMPLIANCE"
      days = 35
    }
  }
  depends_on = [aws_s3_bucket_versioning.backup]
}

resource "aws_s3_bucket_server_side_encryption_configuration" "backup" {
  bucket = aws_s3_bucket.backup.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
    }
    bucket_key_enabled = true
  }
}

resource "aws_s3_bucket_public_access_block" "backup" {
  bucket                  = aws_s3_bucket.backup.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_lifecycle_configuration" "backup" {
  bucket = aws_s3_bucket.backup.id
  rule {
    id     = "ciam"
    status = "Enabled"
    filter {
    }
    transition {
      days          = 30
      storage_class = "GLACIER_IR"
    }
    expiration {
      days = 90
    }
    noncurrent_version_expiration {
      noncurrent_days = 7
    }
  }
  depends_on = [aws_s3_bucket_versioning.backup]
}

variable "backup_replication_role_arn" {
  type        = string
  description = "The IAM role S3 replicates bucket backup to example-aero-ciam-prod-ds-backups-usw2 with"
}

variable "backup_replica_kms_key_arn" {
  type        = string
  description = "The KMS key ARN objects are re-encrypted with in example-aero-ciam-prod-ds-backups-usw2"
}

resource "aws_s3_bucket_replication_configuration" "backup" {
  bucket = aws_s3_bucket.backup.id
  role   = var.backup_replication_role_arn
  rule {
    id     = "ciam"
    status = "Enabled"
    filter {
    }
    delete_marker_replication {
      status = "Enabled"
    }
    source_selection_criteria {
      sse_kms_encrypted_objects {
        status = "Enabled"
      }
    }
    destination {
      bucket = "arn:aws:s3:::example-aero-ciam-prod-ds-backups-usw2"
      encryption_configuration {
        replica_kms_key_id = var.backup_replica_kms_key_arn
      }
    }
  }
  depends_on = [aws_s3_bucket_versioning.backup]
}

import {
  to = aws_s3_bucket.backup
  id = "example-aero-ciam-prod-ds-backups"
}

resource "aws_route53_resolver_rule" "fwd_corp_ad_0" {
  name                 = "ciam-prod-fwd-corp-ad-0"
  domain_name          = "corp.example-aero.internal"
  rule_type            = "FORWARD"
  resolver_endpoint_id = var.resolver_endpoint_id
  target_ip {
    ip   = "10.40.0.53"
    port = 53
  }
  target_ip {
    ip   = "10.40.0.54"
    port = 53
  }
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "aws_route53_resolver_rule_association" "fwd_corp_ad_0" {
  resolver_rule_id = aws_route53_resolver_rule.fwd_corp_ad_0.id
  vpc_id           = data.aws_vpc.main.id
}

data "aws_secretsmanager_secret" "am_admin_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/am-admin-password"
}

data "aws_secretsmanager_secret" "am_ds_bind_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/am-ds-bind-password"
}

data "aws_secretsmanager_secret" "am_keystore" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/am-keystore"
}

data "aws_secretsmanager_secret" "ds_deployment_id" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/ds-deployment-id"
}

data "aws_secretsmanager_secret" "ds_deployment_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/ds-deployment-password"
}

data "aws_secretsmanager_secret" "ds_root_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/ds-root-password"
}

data "aws_secretsmanager_secret" "ds_tls_keystore" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/ds-tls-keystore"
}

data "aws_secretsmanager_secret" "idm_admin_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/idm-admin-password"
}

data "aws_secretsmanager_secret" "idm_ds_bind_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/idm-ds-bind-password"
}

data "aws_secretsmanager_secret" "idm_hrdb_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/idm-hrdb-password"
}

data "aws_secretsmanager_secret" "idm_keystore" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/idm-keystore"
}

data "aws_secretsmanager_secret" "ig_keystore" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/ig-keystore"
}

data "aws_secretsmanager_secret" "pf_admin_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/pf-admin-password"
}

data "aws_secretsmanager_secret" "pf_captcha_secret" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/pf-captcha-secret"
}

data "aws_secretsmanager_secret" "pf_corp_ad_bind_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/pf-corp-ad-bind-password"
}

data "aws_secretsmanager_secret" "pf_ds_bind_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/pf-ds-bind-password"
}

data "aws_secretsmanager_secret" "pf_grants_db_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/pf-grants-db-password"
}

data "aws_secretsmanager_secret" "pf_signing_key" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/pf-signing-key"
}

data "aws_secretsmanager_secret" "pf_smtp_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/pf-smtp-password"
}

data "aws_secretsmanager_secret" "sso_tls_keystore" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/sso-tls-keystore"
}

data "aws_nat_gateway" "pf_egress" {
  id = "nat-0123456789abcdef0"
}
