"""Render PingDS artifacts.

Environment-neutral (identical for every environment):  ds/dsconfig.batch, ds/acis.ldif
Environment-specific (hostnames, peers, secret refs):   ds/setup-<server>.sh

Command and property names follow the PingDS 7.x documentation; verify them against the exact
target version before use.
"""
from .model import DECL, fetch_secret_cmd, peer_ds_hosts


def _q(v):
    return f'"{v}"' if " " in v else v


def dsconfig_batch(d):
    lines = ["# dsconfig batch file. Generated by opsdir from " + DECL,
             "# Environment-neutral: the same file is applied to every environment.",
             "# Apply: dsconfig --hostname <ds> --port 4444 --bindDN uid=admin --bindPasswordFile <file> \\",
             "#          --usePkcs12TrustStore <truststore> --batchFilePath dsconfig.batch --no-prompt", ""]
    for be in d.subtree(f"ou=backends,{DECL}", "ciamBackend"):
        lines.append(f"# backend {be.name} ({be.one('ciamBaseDn')})")
        for ix in d.children(be.dn, "ciamIndex"):
            attr = d.ref(ix, "ciamIndexedAttribute").one("ciamLdapName")
            types = " ".join(f"--set index-type:{t}" for t in ix.all("ciamIndexType"))
            lines.append(f"create-backend-index --backend-name {be.name} --index-name {attr} {types}")
        lines.append("")
    for pp in d.children(f"ou=password-policies,{DECL}", "ciamPasswordPolicy"):
        props = [f"--set default-password-storage-scheme:{_q(pp.one('ciamStorageScheme'))}",
                 "--set password-attribute:userPassword"]
        for attr, prop in [("ciamLockoutFailureCount", "lockout-failure-count"),
                           ("ciamLockoutDuration", "lockout-duration"),
                           ("ciamPasswordHistoryCount", "password-history-count"),
                           ("ciamMaxPasswordAge", "max-password-age")]:
            if pp.one(attr) is not None:
                props.append(f"--set {prop}:{_q(pp.one(attr))}")
        lines.append(f'create-password-policy --policy-name "{pp.name}" --type password-policy ' + " ".join(props))
    lines.append("")
    for h in d.children(f"ou=connection-handlers,{DECL}", "ciamConnectionHandler"):
        props = f"--set enabled:{h.one('ciamEnabled').lower()}"
        if h.one("ciamListenPort"):
            props += f" --set listen-port:{h.one('ciamListenPort')}"
        lines.append(f"set-connection-handler-prop --handler-name {h.name} {props}")
    for lp in d.children(f"ou=log-publishers,{DECL}", "ciamLogPublisher"):
        lines.append(f'set-log-publisher-prop --publisher-name "{lp.name}" --set enabled:{lp.one("ciamEnabled").lower()}')
    topo = d.get(f"cn=topology,ou=replication,{DECL}")
    if topo and topo.one("ciamReplicationPurgeDelay"):
        lines.append("set-synchronization-provider-prop --provider-name \"Multimaster Synchronization\" "
                     f"--set replication-purge-delay:{_q(topo.one('ciamReplicationPurgeDelay'))}")
    return "\n".join(lines) + "\n"


def acis_ldif(d):
    out = ["# ACIs for the user directory. Generated by opsdir from ou=acis,dc=ciam-ops.",
           "# Environment-neutral. Apply with ldapmodify under change control.", ""]
    for aci in d.children("ou=acis,dc=ciam-ops", "ciamAci"):
        if aci.one("ciamAciAllAttributes") == "TRUE":
            target = "*"
        else:
            target = " || ".join(d.get(a).one("ciamLdapName") for a in aci.all("ciamAciTargetAttr"))
        users = " || ".join(f"ldap:///{d.get(g).one('ciamBindDn')}" for g in aci.all("ciamAciGrantee"))
        rights = ",".join(aci.all("ciamAciRight"))
        warn = []
        if not aci.one("ciamOwner"):
            warn.append("no owner")
        if not aci.one("ciamJustification"):
            warn.append("no justification")
        if target == "*":
            warn.append("targetattr=* (all attributes)")
        if warn:
            out.append(f"# WARNING {aci.name}: " + ", ".join(warn))
        out += [f"dn: {aci.one('ciamAciTargetDn')}", "changetype: modify", "add: aci",
                f'aci: (targetattr = "{target}")(version 3.0; acl "{aci.name}"; '
                f'allow ({rights}) userdn = "{users}";)', ""]
    return "\n".join(out)


def setup_scripts(m):
    d = m.d
    be = d.subtree(f"ou=backends,{DECL}", "ciamBackend")[0]
    ports = {h.name: h.one("ciamListenPort") for h in d.children(f"ou=connection-handlers,{DECL}")}
    peers = peer_ds_hosts(d, m)
    files = {}
    secrets = {}
    for role in ("ds-deployment-id", "ds-deployment-password", "ds-root-password"):
        uri = m.secret(role)
        secrets[role] = f'"$({fetch_secret_cmd(uri)})"' if uri else f'"${{UNBOUND_{role.upper().replace("-", "_")}}}"'
    for s in m.servers_with_role("ds"):
        joins = f"joins the replication deployment of {m.joins.dn}" if m.joins else "new or existing deployment"
        bootstrap = " \\\n  ".join(f"--bootstrapReplicationServer {h}:8989" for h in peers)
        files[f"ds/setup-{s.name}.sh"] = f"""#!/usr/bin/env bash
# Generated by opsdir for {s.name} in {m.dn}
# {s.one('ciamProductVersion')}; {joins}.
# Secrets are resolved at run time from references; no secret value is stored in this file.
# The TLS keystore (binding role ds-tls-keystore) is materialized by the secrets agent before this runs.
set -euo pipefail
DEPLOYMENT_ID={secrets['ds-deployment-id']}
DEPLOYMENT_ID_PASSWORD={secrets['ds-deployment-password']}
ROOT_PASSWORD={secrets['ds-root-password']}

./setup \\
  --serverId {s.name} \\
  --deploymentId "$DEPLOYMENT_ID" \\
  --deploymentIdPassword "$DEPLOYMENT_ID_PASSWORD" \\
  --rootUserDn uid=admin \\
  --rootUserPassword "$ROOT_PASSWORD" \\
  --hostname {s.one('ciamHostname')} \\
  --adminConnectorPort 4444 \\
  --ldapsPort {ports.get('LDAPS', 1636)} \\
  --httpsPort {ports.get('HTTPS', 8443)} \\
  --replicationPort 8989 \\
  {bootstrap} \\
  --profile ds-user-data \\
  --set ds-user-data/baseDn:{be.one('ciamBaseDn')} \\
  --acceptLicense

# Then apply the environment-neutral configuration:
#   dsconfig ... --batchFilePath ../ds/dsconfig.batch
"""
    return files


def render_neutral(d):
    return {"ds/dsconfig.batch": dsconfig_batch(d), "ds/acis.ldif": acis_ldif(d)}
