# Generated by opsdir from env=prod,cloud=target,ou=environments,dc=ciam-ops
# Azure landing zone for the CIAM platform, kept by cloud-landing-zone: applied by the landing zone, not by the platform's pipeline
# Do not edit. Change the operations directory (under an approved change) and re-render.

data "azurerm_resource_group" "main" {
  name = "rg-ciam-prod"
}

data "azurerm_subscription" "current" {
}

data "azurerm_key_vault" "kv_ciam_prod" {
  name                = "kv-ciam-prod"
  resource_group_name = data.azurerm_resource_group.main.name
}

resource "azurerm_user_assigned_identity" "identity_ci" {
  name                = "id-ciam-prod-deploy"
  resource_group_name = data.azurerm_resource_group.main.name
  location            = data.azurerm_resource_group.main.location
  tags = {
    CostCenter  = "CC-1001"
    Environment = "target/prod"
    Owner       = "ciam-platform"
    Principal   = "ciam-ops-ci"
    Role        = "identity-ci"
    ManagedBy   = "opsdir"
  }
}

resource "azurerm_federated_identity_credential" "identity_ci" {
  name                = "id-ciam-prod-deploy-ci"
  resource_group_name = data.azurerm_resource_group.main.name
  parent_id           = azurerm_user_assigned_identity.identity_ci.id
  audience            = ["api://AzureADTokenExchange"]
  issuer              = "https://token.actions.githubusercontent.com"
  subject             = "repo:example-aero/ciam-ops:environment:target-prod"
}

resource "azurerm_role_assignment" "identity_ci_manage_pf_sso_service" {
  scope                = "${data.azurerm_resource_group.main.id}/providers/Microsoft.Network/loadBalancers/lb-ciam-prod-svc-sso"
  role_definition_name = "Network Contributor"
  principal_id         = azurerm_user_assigned_identity.identity_ci.principal_id
}

resource "azurerm_role_assignment" "identity_ci_write_secret_pf_admin_password" {
  scope                = "${data.azurerm_key_vault.kv_ciam_prod.id}/secrets/pf-admin-password"
  role_definition_name = "Key Vault Secrets Officer"
  principal_id         = azurerm_user_assigned_identity.identity_ci.principal_id
}

data "azurerm_role_definition" "identity_admins_manage_pf_admin_password" {
  name  = "Key Vault Secrets Officer"
  scope = data.azurerm_subscription.current.id
}

resource "azurerm_pim_eligible_role_assignment" "identity_admins_manage_pf_admin_password" {
  scope              = "${data.azurerm_key_vault.kv_ciam_prod.id}/secrets/pf-admin-password"
  principal_id       = "5b2c0000-0000-4000-8000-0000000000a1"
  role_definition_id = data.azurerm_role_definition.identity_admins_manage_pf_admin_password.id
  justification      = "ciam-admins: manage pf-admin-password"
  schedule {
    expiration {
      duration_days = 365
    }
  }
}

data "azurerm_role_definition" "identity_admins_manage_key_disk_encryption" {
  name  = "Key Vault Crypto Officer"
  scope = data.azurerm_subscription.current.id
}

resource "azurerm_pim_eligible_role_assignment" "identity_admins_manage_key_disk_encryption" {
  scope              = "${data.azurerm_key_vault.kv_ciam_prod.id}/keys/disk-cmk"
  principal_id       = "5b2c0000-0000-4000-8000-0000000000a1"
  role_definition_id = data.azurerm_role_definition.identity_admins_manage_key_disk_encryption.id
  justification      = "ciam-admins: manage-key disk-encryption"
  schedule {
    expiration {
      duration_days = 365
    }
  }
}

data "azurerm_role_definition" "identity_admins_read_logs_audit_logs" {
  name  = "Log Analytics Reader"
  scope = data.azurerm_subscription.current.id
}

resource "azurerm_pim_eligible_role_assignment" "identity_admins_read_logs_audit_logs" {
  scope              = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-prod/providers/Microsoft.OperationalInsights/workspaces/law-ciam-prod-audit"
  principal_id       = "5b2c0000-0000-4000-8000-0000000000a1"
  role_definition_id = data.azurerm_role_definition.identity_admins_read_logs_audit_logs.id
  justification      = "ciam-admins: read-logs audit-logs"
  schedule {
    expiration {
      duration_days = 365
    }
  }
}

resource "azurerm_subscription_policy_assignment" "org_guardrails_region_escape" {
  name                 = "ciam-prod-region-escape"
  policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c"
  subscription_id      = data.azurerm_subscription.current.id
  parameters = jsonencode({
    "listOfAllowedLocations" : {
      "value" : [
        "eastus2",
        "centralus",
        "eastus"
      ]
    }
  })
}

resource "azurerm_subscription_policy_assignment" "org_guardrails_public_storage" {
  name                 = "ciam-prod-public-storage"
  policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/4fa4b6c0-31ca-4c0d-b10d-24b96f62a751"
  subscription_id      = data.azurerm_subscription.current.id
  parameters = jsonencode({
    "effect" : {
      "value" : "Deny"
    }
  })
}

resource "azurerm_subscription_policy_assignment" "org_guardrails_key_deletion" {
  name                 = "ciam-prod-key-deletion"
  policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/0b60c0b2-2dc2-4e1c-b5c9-abbed971de53"
  subscription_id      = data.azurerm_subscription.current.id
  parameters = jsonencode({
    "effect" : {
      "value" : "Deny"
    }
  })
}
