"""infrastructure domain schema fragment: its attribute types and object classes (OIDs pinned by number)."""
from ...core.standard import AttributeDef, ClassDef, enum_type, fragment
from ..data.schema import STORAGE_DEPTH
from .naming import EXPOSURES

ATTRIBUTES = (
    AttributeDef(1, 'cloud', 'string', 'meta', True,
                 'RDN of a cloud hosting environment'),
    AttributeDef(2, 'env', 'string', 'meta', True,
                 'RDN of a deployment stage within a cloud (prod/stage)'),
    AttributeDef(7, 'ciamCloudProvider', 'vocab', 'binding', True,
                 'Cloud or hosting provider; the adapters that apply are chosen from it'),
    AttributeDef(8, 'ciamRegion', 'string', 'binding', True,
                 'Provider region'),
    AttributeDef(9, 'ciamCloudEnvironment', 'vocab', 'binding', True,
                 'Partition of the provider (e.g. commercial vs government cloud)'),
    AttributeDef(10, 'ciamLifecycle', 'enum:active|building|retiring|retired', 'meta', True,
                 'Lifecycle state'),
    AttributeDef(11, 'ciamPlannedCutover', 'time', 'meta', True,
                 'Planned cutover date for an environment being built'),
    AttributeDef(12, 'ciamJoinsDeploymentOf', 'dn', 'intent', True,
                 'DS replicas here join the replication deployment of that environment'),
    AttributeDef(13, 'ciamServerRole', 'vocab', 'intent', True,
                 'What the server runs (a role the product adapters define)'),
    AttributeDef(14, 'ciamProductVersion', 'string', 'intent', True,
                 'Product and version'),
    AttributeDef(15, 'ciamHostname', 'fqdn', 'binding', True,
                 'Server hostname (never used by consumers)'),
    AttributeDef(16, 'ciamPrivateIp', 'ip', 'binding', True,
                 'Private IP address'),
    AttributeDef(17, 'ciamZone', 'string', 'binding', True,
                 'Availability zone'),
    AttributeDef(18, 'ciamInstanceSize', 'string', 'binding', True,
                 'Instance / VM size'),
    AttributeDef(19, 'ciamImageRef', 'string', 'binding', True,
                 'Machine image reference'),
    AttributeDef(20, 'ciamSubnet', 'dn', 'binding', True,
                 'Subnet binding the server is placed in'),
    AttributeDef(21, 'ciamBindingRole', 'string', 'meta', True,
                 'Abstract role a binding fulfils (for a credential, the role of the bindings that hold it); '
                 'migrations match roles across environments'),
    AttributeDef(22, 'ciamProviderRef', 'string', 'binding', True,
                 'Provider identifier of the resource (network, subnet, DNS zone, encryption key set)'),
    AttributeDef(23, 'ciamResourceGroup', 'string', 'binding', True,
                 'Provider resource group or container the resources are placed in'),
    AttributeDef(24, 'ciamCidr', 'cidr', 'binding', False,
                 'Address range'),
    AttributeDef(25, 'ciamFqdn', 'fqdn', 'contract', True,
                 'Service DNS name consumers and partners use. Must stay stable across migrations'),
    AttributeDef(26, 'ciamDnsZone', 'fqdn', 'binding', True,
                 'DNS zone the service name is published in'),
    AttributeDef(27, 'ciamDnsZoneRef', 'string', 'binding', True,
                 'Provider id of the DNS zone'),
    AttributeDef(28, 'ciamTargetRole', 'vocab', 'intent', True,
                 'Server role a service or rule targets'),
    AttributeDef(29, 'ciamPort', 'port', 'intent', False,
                 'TCP/UDP port'),
    AttributeDef(30, 'ciamFrontendIp', 'ip', 'binding', True,
                 'Load balancer frontend IP'),
    AttributeDef(626, 'ciamManagementAddress', 'string', 'binding', True,
                 "Where an appliance's management API answers: a host name or address (and port when not the "
                 "default)"),
    AttributeDef(627, 'ciamApplianceScope', 'string', 'binding', True,
                 "Where on an appliance the platform's objects go, as its vendor names it (an F5 AS3 tenant, a "
                 "PAN-OS device group or vsys, an Infoblox DNS view, the Windows DNS server)"),
    AttributeDef(628, 'ciamLoginSecretRole', 'string', 'binding', True,
                 "Binding role of the secret holding the password or API key an appliance's login signs in with, "
                 "read at run time"),
    AttributeDef(623, 'ciamExposure', enum_type(EXPOSURES), 'binding', True,
                 'Whether a service name\'s load balancer is internal or internet-facing, recorded when no frontend '
                 'address says so (the provider assigns the address)'),
    AttributeDef(31, 'ciamSourceCidr', 'cidr', 'binding', False,
                 'Allowed source range'),
    AttributeDef(32, 'ciamProtocol', 'enum:tcp|udp', 'intent', True,
                 'Transport protocol'),
    AttributeDef(33, 'ciamAllowsConsumer', 'dn', 'binding', False,
                 'Consumer this firewall rule exists for'),
    AttributeDef(34, 'ciamRulePriority', 'int', 'binding', True,
                 'Provider firewall rule priority. Pinned so adding a rule never renumbers others'),
    AttributeDef(36, 'ciamInterconnectKind', 'string', 'binding', True,
                 'Cross-environment link, in words (site-to-site VPN run by the landing zone); ciamLinkKind says '
                 'which kind it is'),
    AttributeDef(37, 'ciamPeerEnvironment', 'dn', 'binding', True,
                 'Environment at the other end of an interconnect'),
    AttributeDef(38, 'ciamStorageRef', 'string', 'binding', True,
                 'Object storage location (bucket or container URI, e.g. s3://bucket, azblob://account/container, '
                 'gs://bucket)'),
    AttributeDef(39, 'ciamRetentionDays', 'int', 'intent', True,
                 'Retention period in days'),
    AttributeDef(40, 'ciamManagedBy', 'dn', 'meta', True,
                 'Party that operates it outside the platform (an external allowlist, a DNS zone)'),
    AttributeDef(41, 'ciamExternalSystem', 'string', 'meta', True,
                 'Where the allowlist lives (partner firewall, app egress policy, SaaS IP list)'),
    AttributeDef(42, 'ciamAllowlistDirection', 'enum:consumer-egress|partner-ingress|partner-egress', 'meta', True,
                 'consumer-egress: their outbound rule to our service; partner-ingress: they allow our egress in; '
                 'partner-egress: they send to us'),
    AttributeDef(43, 'ciamRefersToRole', 'string', 'meta', True,
                 'Binding role of OUR address this allowlist contains (resolved per environment)'),
    AttributeDef(44, 'ciamRecordedCidr', 'cidr', 'observed', False,
                 'Addresses the external allowlist contains today'),
    AttributeDef(45, 'ciamLeadTimeDays', 'int', 'meta', True,
                 'Typical lead time for the owner to change it'),
    AttributeDef(46, 'ciamRequestStatus', 'enum:not-needed|to-request|requested|done', 'meta', True,
                 'Status of the change request to the owner'),
    AttributeDef(125, 'ciamTlsCertificate', 'dn', 'binding', True,
                 'Certificate this service name presents in this environment'),
    AttributeDef(126, 'ciamStackRole', 'string', 'binding', True,
                 'Role a stack component fills in its environment (e.g. provider, directory, federation)'),
    AttributeDef(127, 'ciamAdapter', 'string', 'binding', True,
                 'Name of the adapter that fills the role, as its package registers it'),
    AttributeDef(128, 'ciamAdapterVersion', 'string', 'binding', True,
                 'Adapter versions the environment accepts (a PEP 440 range, e.g. >=0.1,<1)'),
    AttributeDef(129, 'ciamAdapterSource', 'string', 'binding', True,
                 'Where to get the adapter package (URL or package name)'),
    AttributeDef(208, 'ciamOverlayOf', 'dn', 'binding', True,
                 "The environment this one is an overlay of: it inherits that environment's bindings, stack, required "
                 'roles and overrides, except the roles it binds, drops, declares or overrides itself (never servers)'),
    AttributeDef(209, 'ciamDropsRole', 'string', 'binding', False,
                 'A role of the base environment this overlay does not inherit'),
    AttributeDef(210, 'ciamOverrides', 'dn', 'binding', True,
                 'The entry whose value this environment overrides'),
    AttributeDef(211, 'ciamOverrideAttribute', 'string', 'binding', True,
                 "The attribute overridden: one whose definition allows it (X-OVERRIDABLE)"),
    AttributeDef(212, 'ciamOverrideValue', 'string', 'binding', False,
                 'The value(s) this environment uses instead of the shared one'),
    AttributeDef(426, 'ciamHostOrder', 'int', 'binding', True,
                 "This host's place among an environment's bindings of one role when a product setting lists several "
                 '(failover order, lowest first)'),
)
CLASSES = (
    ClassDef(2, 'ciamCloud', 'ciamObject', 'STRUCTURAL', ('cloud', 'ciamCloudProvider', 'ciamRegion'),
             ('ciamCloudEnvironment', 'ciamLifecycle'),
             'A cloud hosting environment'),
    ClassDef(3, 'ciamEnvironment', 'ciamObject', 'STRUCTURAL', ('env',),
             ('ciamLifecycle', 'ciamPlannedCutover', 'ciamJoinsDeploymentOf', 'ciamOverlayOf', 'ciamDropsRole'),
             'A deployment stage within a cloud'),
    ClassDef(4, 'ciamServer', 'ciamObject', 'STRUCTURAL', ('cn', 'ciamServerRole', 'ciamHostname', 'ciamSubnet'),
             ('ciamProductVersion', 'ciamPrivateIp', 'ciamZone', 'ciamInstanceSize', 'ciamImageRef'),
             'A server instance'),
    ClassDef(5, 'ciamBinding', 'ciamObject', 'ABSTRACT', ('cn', 'ciamBindingRole'),
             ('ciamProviderRef',),
             'Environment-specific binding of an abstract role'),
    ClassDef(6, 'ciamNetwork', 'ciamBinding', 'STRUCTURAL', ('ciamCidr',),
             ('ciamResourceGroup', 'ciamFirewallModel', 'ciamOpenWithinNetwork'),
             'Virtual network'),
    ClassDef(7, 'ciamSubnetBinding', 'ciamBinding', 'STRUCTURAL', ('ciamCidr',),
             ('ciamZone',),
             'Subnet'),
    ClassDef(8, 'ciamServiceName', 'ciamBinding', 'STRUCTURAL', ('ciamFqdn', 'ciamTargetRole', 'ciamPort'),
             ('ciamDnsZone', 'ciamDnsZoneRef', 'ciamFrontendIp', 'ciamExposure', 'ciamTlsCertificate',
              'ciamTtlSeconds', 'ciamRoutingPolicy', 'ciamRoutingWeight', 'ciamEdgeFact', 'ciamEdgeSetting',
              'ciamManagedBy'),
             'Stable service name + load balancer (its DNS answer, and what the load balancer runs)'),
    ClassDef(133, 'ciamAppliance', 'ciamBinding', 'STRUCTURAL', ('ciamStackRole', 'ciamManagementAddress'),
             ('ciamApplianceScope', 'ciamLoginName', 'ciamLoginSecretRole', 'ciamManagedBy', 'ciamProviderRef'),
             "An appliance the platform's configuration is pushed to (a load balancer, a DNS server, a network "
             "firewall), filling a stack role: where its management API answers and how the push signs in"),
    ClassDef(9, 'ciamFirewallRule', 'ciamBinding', 'STRUCTURAL', ('ciamSourceCidr', 'ciamPort', 'ciamTargetRole'),
             ('ciamProtocol', 'ciamAllowsConsumer', 'ciamRulePriority', 'ciamPolicyRole', 'ciamManagedBy'),
             'Inbound allow rule'),
    ClassDef(12, 'ciamEgress', 'ciamBinding', 'STRUCTURAL', ('ciamCidr',),
             ('ciamNatAllocation', 'ciamZone'),
             'Outbound (NAT) addresses our services send from'),
    ClassDef(13, 'ciamExternalAllowlist', 'ciamObject', 'STRUCTURAL',
             ('cn', 'ciamManagedBy', 'ciamRefersToRole', 'ciamRecordedCidr', 'ciamAllowlistDirection'),
             ('ciamExternalSystem', 'ciamLeadTimeDays', 'ciamRequestStatus', 'ciamAllowsConsumer'),
             "An allowlist in someone else's system that contains our addresses"),
    ClassDef(14, 'ciamBackupTarget', 'ciamObjectStore', 'STRUCTURAL', (),
             ('ciamRetentionDays',),
             'An object store backups are written to, with their retention'),
    ClassDef(81, 'ciamObjectStore', 'ciamBinding', 'STRUCTURAL', ('ciamStorageRef',),
             STORAGE_DEPTH,
             'An object storage location (bucket or container) the stack uses; a backup target is one with a '
             'retention'),
    ClassDef(15, 'ciamInterconnect', 'ciamBinding', 'STRUCTURAL',
             ('ciamInterconnectKind', 'ciamPeerEnvironment', 'ciamSourceCidr'),
             ('ciamPort', 'ciamLinkKind', 'ciamPeerGateway', 'ciamLocalAsn', 'ciamPeerAsn', 'ciamAdvertisedCidr',
              'ciamAcceptedCidr', 'ciamPeerAccepted', 'ciamManagedBy'),
             'Link to another environment'),
    ClassDef(33, 'ciamStackComponent', 'ciamObject', 'STRUCTURAL', ('cn', 'ciamStackRole', 'ciamAdapter'),
             ('ciamAdapterVersion', 'ciamAdapterSource'),
             'One component of an environment stack: the adapter that fills a role'),
    ClassDef(44, 'ciamRequiredRole', 'ciamObject', 'STRUCTURAL', ('cn', 'ciamBindingRole'),
             (),
             'A role the environment must bind, declared as data (beyond what its domains and adapters require); '
             'the description says why'),
    ClassDef(45, 'ciamOverride', 'ciamObject', 'STRUCTURAL',
             ('cn', 'ciamOverrides', 'ciamOverrideAttribute', 'ciamOverrideValue'),
             (),
             "An environment's own value for one overridable attribute of a shared entry; the description says why"),
    ClassDef(92, 'ciamExternalHost', 'ciamBinding', 'STRUCTURAL', ('ciamFqdn',),
             ('ciamPort', 'ciamManagedBy', 'ciamHostOrder'),
             "A system the platform reaches but doesn't run (a database, a corporate directory), as this environment "
             "reaches it: its host name (and port); products name its role, so each environment renders its own "
             "host. One host is the usual case; a system reached at several (two domain controllers) is several "
             "bindings of the role, in host order"),
)

FRAGMENT = fragment(ATTRIBUTES, CLASSES)
