"""infrastructure domain schema fragment: its attribute types and object classes (OIDs pinned by number)."""
from ...core.standard import AttributeDef, ClassDef, SchemaFragment

ATTRIBUTES = (
    AttributeDef(1, 'cloud', 'string', 'meta', True,
                 'RDN of a cloud hosting environment'),
    AttributeDef(2, 'env', 'string', 'meta', True,
                 'RDN of a deployment stage within a cloud (prod/stage)'),
    AttributeDef(7, 'ciamCloudProvider', 'vocab', 'binding', True,
                 'Cloud or hosting provider; the adapters that apply are chosen from it'),
    AttributeDef(8, 'ciamRegion', 'string', 'binding', True,
                 'Provider region'),
    AttributeDef(9, 'ciamCloudEnvironment', 'vocab', 'binding', True,
                 'Partition of the provider (e.g. commercial vs government cloud)'),
    AttributeDef(10, 'ciamLifecycle', 'enum:active|building|retiring|retired', 'meta', True,
                 'Lifecycle state'),
    AttributeDef(11, 'ciamPlannedCutover', 'time', 'meta', True,
                 'Planned cutover date for an environment being built'),
    AttributeDef(12, 'ciamJoinsDeploymentOf', 'dn', 'intent', True,
                 'DS replicas here join the replication deployment of that environment'),
    AttributeDef(13, 'ciamServerRole', 'vocab', 'intent', True,
                 'What the server runs (a role the product adapters define)'),
    AttributeDef(14, 'ciamProductVersion', 'string', 'intent', True,
                 'Product and version'),
    AttributeDef(15, 'ciamHostname', 'fqdn', 'binding', True,
                 'Server hostname (never used by consumers)'),
    AttributeDef(16, 'ciamPrivateIp', 'ip', 'binding', True,
                 'Private IP address'),
    AttributeDef(17, 'ciamZone', 'string', 'binding', True,
                 'Availability zone'),
    AttributeDef(18, 'ciamInstanceSize', 'string', 'binding', True,
                 'Instance / VM size'),
    AttributeDef(19, 'ciamImageRef', 'string', 'binding', True,
                 'Machine image reference'),
    AttributeDef(20, 'ciamSubnet', 'dn', 'binding', True,
                 'Subnet binding the server is placed in'),
    AttributeDef(21, 'ciamBindingRole', 'string', 'meta', True,
                 'Abstract role this binding fulfils; migrations match roles across environments'),
    AttributeDef(22, 'ciamProviderRef', 'string', 'binding', True,
                 'Provider identifier of the resource (network, subnet, DNS zone, encryption key set)'),
    AttributeDef(23, 'ciamResourceGroup', 'string', 'binding', True,
                 'Provider resource group or container the resources are placed in'),
    AttributeDef(24, 'ciamCidr', 'cidr', 'binding', False,
                 'Address range'),
    AttributeDef(25, 'ciamFqdn', 'fqdn', 'contract', True,
                 'Service DNS name consumers and partners use. Must stay stable across migrations'),
    AttributeDef(26, 'ciamDnsZone', 'fqdn', 'binding', True,
                 'DNS zone the service name is published in'),
    AttributeDef(27, 'ciamDnsZoneRef', 'string', 'binding', True,
                 'Provider id of the DNS zone'),
    AttributeDef(28, 'ciamTargetRole', 'vocab', 'intent', True,
                 'Server role a service or rule targets'),
    AttributeDef(29, 'ciamPort', 'port', 'intent', False,
                 'TCP/UDP port'),
    AttributeDef(30, 'ciamFrontendIp', 'ip', 'binding', True,
                 'Load balancer frontend IP'),
    AttributeDef(31, 'ciamSourceCidr', 'cidr', 'binding', False,
                 'Allowed source range'),
    AttributeDef(32, 'ciamProtocol', 'enum:tcp|udp', 'intent', True,
                 'Transport protocol'),
    AttributeDef(33, 'ciamAllowsConsumer', 'dn', 'binding', False,
                 'Consumer this firewall rule exists for'),
    AttributeDef(34, 'ciamRulePriority', 'int', 'binding', True,
                 'Provider firewall rule priority. Pinned so adding a rule never renumbers others'),
    AttributeDef(35, 'ciamRefUri', 'ref-uri', 'secret-ref', True,
                 "Reference to a secret or key in the environment's store. Never the value"),
    AttributeDef(36, 'ciamInterconnectKind', 'string', 'binding', True,
                 'Cross-environment link type (VPN, dedicated circuit, peering)'),
    AttributeDef(37, 'ciamPeerEnvironment', 'dn', 'binding', True,
                 'Environment at the other end of an interconnect'),
    AttributeDef(38, 'ciamStorageRef', 'string', 'binding', True,
                 'Backup storage location'),
    AttributeDef(39, 'ciamRetentionDays', 'int', 'intent', True,
                 'Retention period in days'),
    AttributeDef(40, 'ciamManagedBy', 'dn', 'meta', True,
                 'Party that operates the external allowlist'),
    AttributeDef(41, 'ciamExternalSystem', 'string', 'meta', True,
                 'Where the allowlist lives (partner firewall, app egress policy, SaaS IP list)'),
    AttributeDef(42, 'ciamAllowlistDirection', 'enum:consumer-egress|partner-ingress|partner-egress', 'meta', True,
                 'consumer-egress: their outbound rule to our service; partner-ingress: they allow our egress in; partner-egress: they send to us'),
    AttributeDef(43, 'ciamRefersToRole', 'string', 'meta', True,
                 'Binding role of OUR address this allowlist contains (resolved per environment)'),
    AttributeDef(44, 'ciamRecordedCidr', 'cidr', 'observed', False,
                 'Addresses the external allowlist contains today'),
    AttributeDef(45, 'ciamLeadTimeDays', 'int', 'meta', True,
                 'Typical lead time for the owner to change it'),
    AttributeDef(46, 'ciamRequestStatus', 'enum:not-needed|to-request|requested|done', 'meta', True,
                 'Status of the change request to the owner'),
    AttributeDef(125, 'ciamTlsCertificate', 'dn', 'binding', True,
                 'Certificate this service name presents in this environment'),
    AttributeDef(126, 'ciamStackRole', 'string', 'binding', True,
                 'Role a stack component fills in its environment (e.g. provider, directory, federation)'),
    AttributeDef(127, 'ciamAdapter', 'string', 'binding', True,
                 'Name of the adapter that fills the role, as its package registers it'),
    AttributeDef(128, 'ciamAdapterVersion', 'string', 'binding', True,
                 'Adapter versions the environment accepts (a PEP 440 range, e.g. >=0.1,<1)'),
    AttributeDef(129, 'ciamAdapterSource', 'string', 'binding', True,
                 'Where to get the adapter package (URL or package name)'),
)
CLASSES = (
    ClassDef(2, 'ciamCloud', 'ciamObject', 'STRUCTURAL', ('cloud', 'ciamCloudProvider', 'ciamRegion'),
             ('ciamCloudEnvironment', 'ciamLifecycle'),
             'A cloud hosting environment'),
    ClassDef(3, 'ciamEnvironment', 'ciamObject', 'STRUCTURAL', ('env',),
             ('ciamLifecycle', 'ciamPlannedCutover', 'ciamJoinsDeploymentOf'),
             'A deployment stage within a cloud'),
    ClassDef(4, 'ciamServer', 'ciamObject', 'STRUCTURAL', ('cn', 'ciamServerRole', 'ciamHostname', 'ciamSubnet'),
             ('ciamProductVersion', 'ciamPrivateIp', 'ciamZone', 'ciamInstanceSize', 'ciamImageRef'),
             'A server instance'),
    ClassDef(5, 'ciamBinding', 'ciamObject', 'ABSTRACT', ('cn', 'ciamBindingRole'),
             ('ciamProviderRef',),
             'Environment-specific binding of an abstract role'),
    ClassDef(6, 'ciamNetwork', 'ciamBinding', 'STRUCTURAL', ('ciamCidr',),
             ('ciamResourceGroup',),
             'Virtual network'),
    ClassDef(7, 'ciamSubnetBinding', 'ciamBinding', 'STRUCTURAL', ('ciamCidr',),
             ('ciamZone',),
             'Subnet'),
    ClassDef(8, 'ciamServiceName', 'ciamBinding', 'STRUCTURAL', ('ciamFqdn', 'ciamTargetRole', 'ciamPort'),
             ('ciamDnsZone', 'ciamDnsZoneRef', 'ciamFrontendIp', 'ciamTlsCertificate'),
             'Stable service name + load balancer'),
    ClassDef(9, 'ciamFirewallRule', 'ciamBinding', 'STRUCTURAL', ('ciamSourceCidr', 'ciamPort', 'ciamTargetRole'),
             ('ciamProtocol', 'ciamAllowsConsumer', 'ciamRulePriority'),
             'Inbound allow rule'),
    ClassDef(10, 'ciamSecretRef', 'ciamBinding', 'STRUCTURAL', ('ciamRefUri',),
             (),
             'Reference to a secret'),
    ClassDef(11, 'ciamKeyRef', 'ciamBinding', 'STRUCTURAL', ('ciamRefUri',),
             (),
             'Reference to an encryption key'),
    ClassDef(12, 'ciamEgress', 'ciamBinding', 'STRUCTURAL', ('ciamCidr',),
             (),
             'Outbound (NAT) addresses our services send from'),
    ClassDef(13, 'ciamExternalAllowlist', 'ciamObject', 'STRUCTURAL', ('cn', 'ciamManagedBy', 'ciamRefersToRole', 'ciamRecordedCidr', 'ciamAllowlistDirection'),
             ('ciamExternalSystem', 'ciamLeadTimeDays', 'ciamRequestStatus', 'ciamAllowsConsumer'),
             "An allowlist in someone else's system that contains our addresses"),
    ClassDef(14, 'ciamBackupTarget', 'ciamBinding', 'STRUCTURAL', ('ciamStorageRef',),
             ('ciamRetentionDays',),
             'Backup destination'),
    ClassDef(15, 'ciamInterconnect', 'ciamBinding', 'STRUCTURAL', ('ciamInterconnectKind', 'ciamPeerEnvironment', 'ciamSourceCidr'),
             ('ciamPort',),
             'Link to another environment'),
    ClassDef(33, 'ciamStackComponent', 'ciamObject', 'STRUCTURAL', ('cn', 'ciamStackRole', 'ciamAdapter'),
             ('ciamAdapterVersion', 'ciamAdapterSource'),
             'One component of an environment stack: the adapter that fills a role'),
)

FRAGMENT = SchemaFragment(ATTRIBUTES, CLASSES)
