"""What the ping-devops adapter renders for the PingFederate workloads an environment runs on Kubernetes: per
namespace, values for Ping's ping-devops chart from the workloads and their bindings (image, replicas, resources,
service account, pod labels, Secret keys as environment variables and the license as a file, storage, ingress), and
what the planner says about licenses, the admin password, admin replicas, lone engines and extra workloads."""
import pathlib
import re
import subprocess

import pytest
import yaml

from opsdir.connectors.registry import core_fragments, services
from opsdir.core.contract import K8sIdentity, PlanContext
from opsdir.core.directory import one
from opsdir.core.environment import env_model
from opsdir.core.interchange.ldif import parse
from opsdir.core.standard import registry_ldif
from opsdir.domains.compute.naming import WORKLOADS, workload_dn
from opsdir_adapter_kubernetes.adapter import ADAPTER as KUBERNETES
from opsdir_adapter_ping_devops import release
from opsdir_adapter_ping_devops.adapter import ADAPTER
from opsdir_adapter_ping_devops.checks import check_ping_devops
from opsdir_adapter_ping_devops.helm import render
from opsdir_adapter_ping_devops.listeners import listeners
from opsdir_adapter_ping_devops.products import applies, placements, unplaced
from opsdir_adapter_pingfederate.schema import FRAGMENT
import mini_estate
from mini_estate import FAKE
from support import build_directory

ALPHA = "env=prod,cloud=alpha,ou=environments,dc=ciam-ops"
ROOT = pathlib.Path(__file__).resolve().parents[3]
CHART = ROOT / "tools" / "ping-devops" / release.VERSION / "ping-devops"
PF_IMAGE = "registry.example.test:5000/ciam/pingfederate:12.2.1@sha256:" + "b" * 64
VALUES = "ping-devops/helm/identity/ping-devops-values.yaml"
REGISTRY = registry_ldif((*core_fragments(), FRAGMENT))       # the record knows PingFederate's discovery binding
QUERY = "pingfederate-pingfederate-cluster.identity.svc.cluster.local"


def _workload(name, role, extra=""):
    return (f"dn: {workload_dn(name)}\nobjectClass: top\nobjectClass: ciamWorkload\ncn: {name}\n"
            f"ciamWorkloadKind: deployment\nciamTargetRole: {role}\nciamClusterRole: k8s\nciamNamespace: identity\n"
            f"ciamWorkloadRole: {name}-workload\n{extra}")


def _binding(cn, oc, role, extra=""):
    return (f"dn: cn={cn},ou=bindings,{ALPHA}\nobjectClass: top\nobjectClass: {oc}\ncn: {cn}\n"
            f"ciamBindingRole: {role}\n{extra}")


BASE = (
    f"dn: {WORKLOADS}\nobjectClass: top\nobjectClass: organizationalUnit\nou: workloads\n",
    _workload("pf-admin", "pf-admin", "ciamServiceAccount: pingfederate\nciamIdentityRole: identity-pf\n"
                                      "ciamIngressHost: pf-admin.example.test\n"
                                      "ciamWorkloadSecret: pf-license/pingfederate.lic <- pf-license\n"
                                      "ciamWorkloadSecret: pf-admin/PING_IDENTITY_PASSWORD <- pf-admin-password\n"),
    _workload("pf-engine", "pf-engine", "ciamServiceAccount: pingfederate\nciamIngressHost: sso.example.test\n"
                                        "ciamWorkloadSecret: pf-license/pingfederate.lic <- pf-license\n"),
    _binding("k8s", "ciamCluster", "k8s", "ciamProviderRef: cluster-1\n"),
    _binding("pf-admin", "ciamWorkloadBinding", "pf-admin-workload",
             f"ciamContainerImage: pingfederate={PF_IMAGE}\nciamCpuRequest: 500m\nciamMemoryLimit: 4Gi\n"
             "ciamStorageSize: 8Gi\nciamStorageClass: managed-csi\n"),
    _binding("pf-engine", "ciamWorkloadBinding", "pf-engine-workload", "ciamWorkloadReplicas: 3\n"),
    _binding("identity-pf", "ciamIdentityBinding", "identity-pf", "ciamProviderRef: pf-identity\n"),
    _binding("pf-discovery", "pingfedClusterDiscovery", "pf-cluster-discovery",
             f"pingfedDiscoveryProtocol: DNS_PING\nciamFqdn: {QUERY}\n"))
CLOUD = FAKE._replace(workload_identity=lambda m, b: K8sIdentity(
    (("cloud.example.test/identity", one(b, "ciamProviderRef")),), (("cloud.example.test/use", "true"),)))
INSTALLED = (CLOUD, KUBERNETES, ADAPTER)


def model(*extra, base=BASE):
    d = build_directory(REGISTRY, tuple(parse("\n".join((mini_estate.LDIF, *base, *extra)))))
    return env_model(d, "alpha/prod")


def _values(m):
    files = render(m, services(INSTALLED))
    assert list(files) == [VALUES]
    assert files[VALUES].startswith("# Generated by opsdir from env=prod,cloud=alpha")
    values = yaml.safe_load(files[VALUES])
    assert values["global"]["envs"]["PING_IDENTITY_ACCEPT_EULA"] == "YES" and "--set" not in files[VALUES]
    return values


def _actions(m):
    return [a[1] for a in check_ping_devops(PlanContext(m.d, m, m, None, None, {}, {}, ())).actions]


def test_it_renders_only_where_pingfederate_runs_on_kubernetes():
    assert applies(model())
    assert not applies(env_model(build_directory(REGISTRY, tuple(parse(mini_estate.LDIF))), "alpha/prod"))
    (p,) = placements(model())
    assert p.namespace == "identity" and [x for x, _ in p.placed] == ["pingfederate-admin", "pingfederate-engine"]


def test_admin_values_come_from_the_record():
    v = _values(model())["pingfederate-admin"]
    assert v["image"] == {"repositoryFqn": "registry.example.test:5000/ciam/pingfederate:12.2.1@sha256",
                          "tag": "b" * 64}
    assert v["container"] == {
        "resources": {"requests": {"cpu": "500m"}, "limits": {"memory": "4Gi"}},
        "env": [{"name": "PING_IDENTITY_PASSWORD",
                 "valueFrom": {"secretKeyRef": {"name": "pf-admin", "key": "PING_IDENTITY_PASSWORD"}}}]}
    assert v["rbac"] == {"serviceAccountName": "pingfederate"}
    assert v["workload"] == {
        "labels": {"opsdir.io/role": "pf-admin", "cloud.example.test/use": "true"}, "type": "StatefulSet",
        "statefulSet": {"persistentvolume": {"enabled": True, "volumes": {"out-dir": {"persistentVolumeClaim": {
            "storageClassName": "managed-csi", "resources": {"requests": {"storage": "8Gi"}}}}}}}}
    assert v["secretVolumes"] == {"pf-license": {"items": {
        "pingfederate.lic": "/opt/in/instance/server/default/conf/pingfederate.lic"}}}
    assert v["ingress"]["hosts"][0]["host"] == "pf-admin.example.test"
    assert v["ingress"]["tls"] == [{"secretName": "_defaultTlsSecret_", "hosts": ["pf-admin.example.test"]}]


def test_the_engine_shares_the_admin_image_and_scales():
    v = _values(model())["pingfederate-engine"]
    assert v["image"]["tag"] == "b" * 64                     # the admin binding's pingfederate container
    assert v["container"] == {"replicaCount": 3}
    assert v["workload"] == {"labels": {"opsdir.io/role": "pf-engine"}}
    assert "env" not in v["container"] and v["ingress"]["hosts"][0]["host"] == "sso.example.test"


def test_an_unnamed_image_is_unbound_and_a_missing_product_is_off():
    base = tuple(b for b in BASE if "pf-admin" not in b)
    v = _values(model(base=base))
    assert v["pingfederate-admin"] == {"enabled": False}
    assert v["pingfederate-engine"]["image"] == {"repositoryFqn": "UNBOUND",
                                                 "tag": "ping-devops-pingfederate-engine-image"}


def test_its_pods_ports():
    found = {(x.server_role, x.port, x.peers) for x in listeners(model())}
    assert ("pf-admin", 9999, ("admin",)) in found and ("pf-engine", 9031, ("clients",)) in found
    assert ("pf-engine", 7600, ("peers", "pf-admin")) in found and len(found) == 6
    assert {x.on for x in listeners(model())} == {"kubernetes"}
    engines_only = model(base=tuple(b for b in BASE if "pf-admin" not in b))
    assert {x.server_role for x in listeners(engines_only)} == {"pf-engine"}


def test_the_planner_names_what_pingfederate_still_needs():
    assert _actions(model()) == []
    no_password = tuple(b.replace("ciamWorkloadSecret: pf-admin/PING_IDENTITY_PASSWORD <- pf-admin-password\n", "")
                        .replace("ciamCpuRequest: 500m\n", "ciamWorkloadReplicas: 2\n") for b in BASE)
    actions = _actions(model(base=no_password))
    assert any("records no `PING_IDENTITY_PASSWORD`" in a for a in actions)
    assert any("records 2 replicas" in a for a in actions)
    lone = tuple(b for b in BASE if "pf-admin" not in b) + (
        _workload("pf-engine-2", "pf-engine"), _binding("pf-engine-2", "ciamWorkloadBinding", "pf-engine-2-workload"))
    m = model(base=lone)
    assert [name for _, name, _ in unplaced(m)] == ["pingfederate-engine"]
    actions = _actions(m)
    assert any("with no admin console there" in a for a in actions)
    assert any(a.startswith("Workload `pf-engine-2` runs `pingfederate-engine` in") and "beside another" in a
               for a in actions)
    assert not any("`pf-engine-2` in" in a and "no license" in a for a in actions)    # not placed, so not deployed
    unlicensed = tuple(b.replace("ciamWorkloadSecret: pf-license/pingfederate.lic <- pf-license\n", "")
                       if "cn: pf-engine\n" in b else b for b in BASE)
    (action,) = _actions(model(base=unlicensed))
    assert action.startswith("PingFederate workload `pf-engine`") and "has no license recorded" in action


def _fixes(m):
    return check_ping_devops(PlanContext(m.d, m, m, None, None, {}, {}, ())).fixes


def test_the_nodes_find_each_other_through_the_charts_cluster_service():
    assert release.cluster_query("identity") == QUERY
    assert _values(model())["global"]["envs"]["DNS_QUERY_LOCATION"] == QUERY       # from the record's binding
    assert _fixes(model()) == ()
    unbound = tuple(b for b in BASE if "pf-cluster-discovery" not in b)
    assert "DNS_QUERY_LOCATION" not in _values(model(base=unbound))["global"]["envs"]   # the chart's own default
    (action,) = _actions(model(base=unbound))
    assert action.startswith("PingFederate runs on Kubernetes in alpha/prod (namespace `identity`): the chart's pods "
                             f"find each other by DNS_PING through its cluster service `{QUERY}`, but the record "
                             "binds no `pf-cluster-discovery` there.")
    (fix,) = _fixes(model(base=unbound))
    (record,) = [r for r in fix.records if r.dn.startswith("cn=pf-discovery,")]
    assert record.attrs["pingfedDiscoveryProtocol"] == ("DNS_PING",) and record.attrs["ciamFqdn"] == (QUERY,)
    s3 = tuple(b.replace("pingfedClusterDiscovery", "ciamObjectStore").replace(
        f"pingfedDiscoveryProtocol: DNS_PING\nciamFqdn: {QUERY}\n", "ciamStorageRef: s3://pf-cluster\n")
        for b in BASE)
    (action,) = _actions(model(base=s3))
    assert action.endswith("but its `pf-cluster-discovery` binding uses NATIVE_S3_PING. Record that binding.")
    elsewhere = tuple(b.replace(QUERY, "pf.example.test") for b in BASE)
    assert _values(model(base=elsewhere))["global"]["envs"]["DNS_QUERY_LOCATION"] == "pf.example.test"
    (action,) = _actions(model(base=elsewhere))
    assert "has them query `pf.example.test`, which the chart's service doesn't answer" in action
    (fix,) = _fixes(model(base=elsewhere))
    assert fix.records[0].mods[0] == ("replace", "pingfedDiscoveryProtocol", ("DNS_PING",))
    assert ("replace", "ciamFqdn", (QUERY,)) in fix.records[0].mods


def test_the_fetch_script_pins_the_chart():
    script = (ROOT / "packages" / "opsdir-adapter-ping-devops" / "scripts" / "fetch-ping-devops.sh").read_text()
    pins = dict(re.findall(r"^(VERSION|SHA256)=(\S+)$", script, re.M))
    assert pins == {"VERSION": release.VERSION, "SHA256": release.SOURCE_SHA256}


@pytest.mark.kubernetes
@pytest.mark.skipif(not (ROOT / "tools" / "bin" / "kubeconform").exists() or not (CHART.parent / ".complete").exists(),
                    reason="no tools (opsdir/scripts/fetch-tools.sh) or chart (fetch-ping-devops.sh)")
def test_the_values_template_to_valid_kubernetes(tmp_path):
    values = tmp_path / "values.yaml"
    values.write_text(render(model(), services(INSTALLED))[VALUES])
    done = subprocess.run([str(ROOT / "opsdir" / "scripts" / "validate-kubernetes.sh"), "--helm", str(CHART),
                           str(values)], capture_output=True, text=True)
    assert done.returncode == 0, done.stdout + done.stderr
