"""What the Kubernetes adapter renders around the workloads an environment runs on Kubernetes: per namespace a
kustomization of the namespace (its pod-security level), service accounts with the provider's workload identity
annotations, network policies from the products' listeners (pods of roles running here by label, servers' subnets
otherwise), and secret delivery: always the list of Secrets required and what delivers them; External Secrets
Operator stores and secrets, or CSI provider classes, when asked. Values never; UNBOUND where the record is silent."""
import pathlib
import subprocess

import pytest
import yaml

from opsdir.connectors.registry import services
from opsdir.core.contract import K8sIdentity, Listener
from opsdir.core.directory import one
from opsdir.core.environment import env_model
from opsdir.core.interchange.ldif import parse
from opsdir.domains.compute.naming import WORKLOADS, workload_dn
from opsdir_adapter_hashicorp_vault.adapter import ADAPTER as VAULT
from opsdir_adapter_kubernetes.adapter import ADAPTER
from opsdir_adapter_kubernetes.render import applies, k8s_name, render
import mini_estate
from mini_estate import FAKE
from support import REGISTRY, build_directory

ALPHA = "env=prod,cloud=alpha,ou=environments,dc=ciam-ops"
ROOT = pathlib.Path(__file__).resolve().parents[3]


def _workload(name, role, extra=""):
    return (f"dn: {workload_dn(name)}\nobjectClass: top\nobjectClass: ciamWorkload\ncn: {name}\n"
            f"ciamWorkloadKind: deployment\nciamTargetRole: {role}\nciamClusterRole: k8s\nciamNamespace: identity\n"
            f"ciamWorkloadRole: {name}-workload\n{extra}")


def _binding(cn, oc, role, extra=""):
    return (f"dn: cn={cn},ou=bindings,{ALPHA}\nobjectClass: top\nobjectClass: {oc}\ncn: {cn}\n"
            f"ciamBindingRole: {role}\n{extra}")


RECORDS = "\n".join((
    f"dn: {WORKLOADS}\nobjectClass: top\nobjectClass: organizationalUnit\nou: workloads\n",
    _workload("am", "am", "ciamServiceAccount: am\nciamIdentityRole: identity-am\nciamPodSecurity: level=restricted\n"
                          "ciamWorkloadSecret: am-passwords/admin <- am-admin\n"
                          "ciamWorkloadSecret: am-passwords/keystore <- am-keystore\n"
                          "ciamWorkloadSecret: am-env/token <- am-token\n"),
    _workload("ig", "ig", "ciamPodSecurity: level=baseline\n"),
    _binding("k8s", "ciamCluster", "k8s", "ciamProviderRef: cluster-1\n"),
    _binding("am", "ciamWorkloadBinding", "am-workload", "ciamWorkloadReplicas: 2\n"),
    _binding("ig", "ciamWorkloadBinding", "ig-workload"),
    _binding("identity-am", "ciamIdentityBinding", "identity-am", "ciamProviderRef: am-identity\n"),
    _binding("am-admin", "ciamSecretRef", "am-admin", "ciamRefUri: vault://secret/ciam/am/admin\n"),
    _binding("am-keystore", "ciamSecretRef", "am-keystore", "ciamRefUri: k8s-secret://identity/am-passwords/keystore\n"),
    _binding("vault", "ciamSecretStore", "secret-store-vault",
             "ciamRefScheme: vault\nciamStoreEndpoint: https://vault.example.test:8200\nciamStoreAuthRole: ciam\n"),
    f"dn: cn=db-1,{ALPHA}\nobjectClass: top\nobjectClass: ciamServer\ncn: db-1\nciamServerRole: db\n"
    f"ciamHostname: db-1.example.test\nciamSubnet: cn=net,ou=bindings,{ALPHA}\n"))
LISTENERS = (Listener("am", 8443, "tcp", "sign-on", ("clients",)), Listener("am", 8081, "tcp", "routes", ("ig",)),
             Listener("am", 5701, "tcp", "cluster", ("peers",)), Listener("am", 1389, "tcp", "store", ("db",)),
             Listener("ig", 8443, "tcp", "gateway", ("clients",)))
CLOUD = FAKE._replace(listeners=lambda m: LISTENERS,
                      workload_identity=lambda m, b: K8sIdentity(
                          (("cloud.example.test/identity", one(b, "ciamProviderRef")),), (("cloud.example.test/use", "true"),)))
INSTALLED = (CLOUD, ADAPTER, VAULT)


def model():
    d = build_directory(REGISTRY, tuple(parse(mini_estate.LDIF + "\n" + RECORDS)))
    return env_model(d, "alpha/prod")


def _docs(files, path):
    text = files[path]
    assert text.startswith("# Generated by opsdir from env=prod,cloud=alpha")
    return [x for x in yaml.safe_load_all(text) if x is not None]


def test_it_renders_only_where_workloads_run_on_kubernetes():
    assert applies(model())
    assert not applies(env_model(build_directory(REGISTRY, tuple(parse(mini_estate.LDIF))), "alpha/prod"))


def test_a_namespace_folder_of_objects_and_its_kustomization():
    files = render(model(), services(INSTALLED))
    assert sorted(files) == [f"kubernetes/identity/{f}" for f in (
        "kustomization.yaml", "namespace.yaml", "networkpolicies.yaml", "secrets-required.yaml",
        "serviceaccounts.yaml")]
    assert _docs(files, "kubernetes/identity/kustomization.yaml")[0]["resources"] == \
        ["namespace.yaml", "serviceaccounts.yaml", "networkpolicies.yaml"]
    (ns,) = _docs(files, "kubernetes/identity/namespace.yaml")
    assert ns["metadata"] == {"name": "identity", "labels": {"pod-security.kubernetes.io/enforce": "baseline"}}


def test_service_accounts_carry_the_cloud_identity():
    am, ig = _docs(render(model(), services(INSTALLED)), "kubernetes/identity/serviceaccounts.yaml")
    assert am["metadata"] == {"name": "am", "namespace": "identity",
                              "annotations": {"cloud.example.test/identity": "am-identity"}}
    assert ig["metadata"] == {"name": "ig", "namespace": "identity"}


def test_network_policies_from_the_listeners():
    deny, am, ig = _docs(render(model(), services(INSTALLED)), "kubernetes/identity/networkpolicies.yaml")
    assert deny["spec"] == {"podSelector": {}, "policyTypes": ["Ingress"]}
    assert am["spec"]["podSelector"] == {"matchLabels": {"opsdir.io/role": "am"}}
    assert am["spec"]["ingress"] == [
        {"ports": [{"port": 8443, "protocol": "TCP"}]},
        {"from": [{"namespaceSelector": {}, "podSelector": {"matchLabels": {"opsdir.io/role": "ig"}}}],
         "ports": [{"port": 8081, "protocol": "TCP"}]},
        {"from": [{"namespaceSelector": {}, "podSelector": {"matchLabels": {"opsdir.io/role": "am"}}}],
         "ports": [{"port": 5701, "protocol": "TCP"}]},
        {"from": [{"ipBlock": {"cidr": "10.1.0.0/16"}}], "ports": [{"port": 1389, "protocol": "TCP"}]}]
    assert ig["spec"]["ingress"] == [{"ports": [{"port": 8443, "protocol": "TCP"}]}]


def test_a_kits_container_ports_replace_the_products_for_its_pods():
    kit = (*LISTENERS, Listener("am", 8080, "tcp", "HTTP", ("clients",), "kubernetes"),
           Listener("ig", 9443, "tcp", "on its servers", ("clients",), "servers"))
    cloud = CLOUD._replace(listeners=lambda m: kit)
    _, am, ig = _docs(render(model(), services((cloud, ADAPTER, VAULT))), "kubernetes/identity/networkpolicies.yaml")
    assert am["spec"]["ingress"] == [{"ports": [{"port": 8080, "protocol": "TCP"}]}]
    assert ig["spec"]["ingress"] == [{"ports": [{"port": 8443, "protocol": "TCP"}]}]


def test_the_secrets_required_and_what_delivers_them():
    (doc,) = _docs(render(model(), services(INSTALLED)), "kubernetes/identity/secrets-required.yaml")
    (passwords, env) = doc["secrets"]
    assert [(k["key"], k["ref"], k["delivered by"]) for k in passwords["keys"]] == [
        ("admin", "vault://secret/ciam/am/admin",
         "you: create it (render with --target kubernetes=external-secrets or csi to have it delivered)"),
        ("keystore", "k8s-secret://identity/am-passwords/keystore", "it is the Kubernetes Secret itself")]
    assert env["keys"][0]["ref"] == "UNBOUND:am-token" and env["keys"][0]["read by"] == ["am"]


def test_external_secrets_when_asked():
    files = render(model(), services(INSTALLED), ("external-secrets",))
    store, secret = _docs(files, "kubernetes/identity/externalsecrets.yaml")
    assert store["metadata"]["name"] == "vault-secret-am" and store["spec"]["provider"]["vault"]["server"] == \
        "https://vault.example.test:8200"
    assert secret["spec"]["target"] == {"name": "am-passwords", "creationPolicy": "Owner"}
    assert secret["spec"]["data"] == [{"secretKey": "admin", "remoteRef": {"key": "ciam/am/admin", "property": "value"}}]
    assert "externalsecrets.yaml" in _docs(files, "kubernetes/identity/kustomization.yaml")[0]["resources"]


def test_csi_provider_classes_when_asked():
    (spc,) = _docs(render(model(), services(INSTALLED), ("csi",)), "kubernetes/identity/secretproviderclasses.yaml")
    assert (spc["metadata"]["name"], spc["spec"]["provider"]) == ("am-vault-secret", "vault")
    assert spc["spec"]["secretObjects"] == [{"secretName": "am-passwords", "type": "Opaque",
                                             "data": [{"objectName": "am-passwords-admin", "key": "admin"}]}]
    assert yaml.safe_load(spc["spec"]["parameters"]["objects"]) == [
        {"objectName": "am-passwords-admin", "secretPath": "secret/data/ciam/am/admin", "secretKey": "value"}]


def test_names_kubernetes_accepts():
    assert k8s_name("Vault-secret/ciam_AM--") == "vault-secret-ciam-am" and k8s_name("///") == "x"


@pytest.mark.kubernetes
@pytest.mark.skipif(not (ROOT / "tools" / "bin" / "kubeconform").exists(), reason="no tools (fetch-tools.sh)")
def test_the_render_is_valid_kubernetes(tmp_path):
    for path, text in render(model(), services(INSTALLED), ("external-secrets", "csi")).items():
        (tmp_path / path).parent.mkdir(parents=True, exist_ok=True)
        (tmp_path / path).write_text(text)
    done = subprocess.run([str(ROOT / "opsdir" / "scripts" / "validate-kubernetes.sh"), str(tmp_path)],
                          capture_output=True, text=True)
    assert done.returncode == 0, done.stdout + done.stderr
