# Generated by opsdir from env=prod,cloud=target,ou=environments,dc=ciam-ops
# Azure infrastructure for the CIAM platform
# Do not edit. Change the operations directory (under an approved change) and re-render.
# Interconnect 'link-source' to env=prod,cloud=source,ou=environments,dc=ciam-ops: site-to-site VPN (landing-zone managed). Provided by the landing zone; not managed here.

data "azurerm_resource_group" "main" {
  name = "rg-ciam-prod"
}

data "azurerm_virtual_network" "main" {
  name                = "vnet-ciam-prod"
  resource_group_name = data.azurerm_resource_group.main.name
}

data "azurerm_subnet" "snet_am" {
  name                 = "snet-am"
  virtual_network_name = "vnet-ciam-prod"
  resource_group_name  = data.azurerm_resource_group.main.name
}

data "azurerm_subnet" "snet_db" {
  name                 = "snet-db"
  virtual_network_name = "vnet-ciam-prod"
  resource_group_name  = data.azurerm_resource_group.main.name
}

data "azurerm_subnet" "snet_ds" {
  name                 = "snet-ds"
  virtual_network_name = "vnet-ciam-prod"
  resource_group_name  = data.azurerm_resource_group.main.name
}

data "azurerm_subnet" "snet_edge" {
  name                 = "snet-appgw"
  virtual_network_name = "vnet-ciam-prod"
  resource_group_name  = data.azurerm_resource_group.main.name
}

data "azurerm_subnet" "snet_idm" {
  name                 = "snet-idm"
  virtual_network_name = "vnet-ciam-prod"
  resource_group_name  = data.azurerm_resource_group.main.name
}

data "azurerm_subnet" "snet_ig" {
  name                 = "snet-ig"
  virtual_network_name = "vnet-ciam-prod"
  resource_group_name  = data.azurerm_resource_group.main.name
}

data "azurerm_subnet" "snet_pf" {
  name                 = "snet-pf"
  virtual_network_name = "vnet-ciam-prod"
  resource_group_name  = data.azurerm_resource_group.main.name
}

resource "azurerm_network_security_group" "am" {
  name                = "nsg-ciam-prod-am"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "azurerm_network_security_group" "ds" {
  name                = "nsg-ciam-prod-ds"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "azurerm_network_security_group" "idm" {
  name                = "nsg-ciam-prod-idm"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "azurerm_network_security_group" "ig" {
  name                = "nsg-ciam-prod-ig"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "azurerm_network_security_group" "pf_admin" {
  name                = "nsg-ciam-prod-pf-admin"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "azurerm_network_security_group" "pf_engine" {
  name                = "nsg-ciam-prod-pf-engine"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "azurerm_network_security_rule" "fw_admin" {
  name                        = "fw-admin"
  description                 = "fw-admin"
  priority                    = 150
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_ranges     = ["4444"]
  source_address_prefixes     = ["10.60.9.0/28"]
  destination_address_prefix  = "*"
  resource_group_name         = data.azurerm_resource_group.main.name
  network_security_group_name = azurerm_network_security_group.ds.name
}

resource "azurerm_network_security_rule" "fw_apps_public" {
  name                        = "fw-apps-public"
  description                 = "fw-apps-public"
  priority                    = 180
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_ranges     = ["443"]
  source_address_prefixes     = ["0.0.0.0/0"]
  destination_address_prefix  = "*"
  resource_group_name         = data.azurerm_resource_group.main.name
  network_security_group_name = azurerm_network_security_group.ig.name
}

resource "azurerm_network_security_rule" "fw_customer_portal" {
  name                        = "fw-customer-portal"
  description                 = "consumer customer-portal-svc"
  priority                    = 110
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_ranges     = ["1636"]
  source_address_prefixes     = ["10.30.8.0/24"]
  destination_address_prefix  = "*"
  resource_group_name         = data.azurerm_resource_group.main.name
  network_security_group_name = azurerm_network_security_group.ds.name
}

resource "azurerm_network_security_rule" "fw_idm_sync" {
  name                        = "fw-idm-sync"
  description                 = "consumer idm-sync"
  priority                    = 130
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_ranges     = ["1636"]
  source_address_prefixes     = ["10.60.6.0/24"]
  destination_address_prefix  = "*"
  resource_group_name         = data.azurerm_resource_group.main.name
  network_security_group_name = azurerm_network_security_group.ds.name
}

resource "azurerm_network_security_rule" "fw_login_public" {
  name                        = "fw-login-public"
  description                 = "fw-login-public"
  priority                    = 170
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_ranges     = ["443"]
  source_address_prefixes     = ["0.0.0.0/0"]
  destination_address_prefix  = "*"
  resource_group_name         = data.azurerm_resource_group.main.name
  network_security_group_name = azurerm_network_security_group.am.name
}

resource "azurerm_network_security_rule" "fw_mro_batch" {
  name                        = "fw-mro-batch"
  description                 = "consumer mro-batch-export"
  priority                    = 170
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_ranges     = ["1636"]
  source_address_prefixes     = ["10.40.12.0/24"]
  destination_address_prefix  = "*"
  resource_group_name         = data.azurerm_resource_group.main.name
  network_security_group_name = azurerm_network_security_group.ds.name
}

resource "azurerm_network_security_rule" "fw_pf_cluster" {
  name                        = "fw-pf-cluster"
  description                 = "fw-pf-cluster"
  priority                    = 190
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_ranges     = ["7600", "7700"]
  source_address_prefixes     = ["10.60.2.0/24"]
  destination_address_prefix  = "*"
  resource_group_name         = data.azurerm_resource_group.main.name
  network_security_group_name = azurerm_network_security_group.pf_engine.name
}

resource "azurerm_network_security_rule" "fw_pf_cluster_admin" {
  name                        = "fw-pf-cluster-admin"
  description                 = "fw-pf-cluster-admin"
  priority                    = 200
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_ranges     = ["7600", "7700"]
  source_address_prefixes     = ["10.60.2.0/24"]
  destination_address_prefix  = "*"
  resource_group_name         = data.azurerm_resource_group.main.name
  network_security_group_name = azurerm_network_security_group.pf_admin.name
}

resource "azurerm_network_security_rule" "fw_pf_ds_svc" {
  name                        = "fw-pf-ds-svc"
  description                 = "consumer pf-ds-svc"
  priority                    = 100
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_ranges     = ["1636"]
  source_address_prefixes     = ["10.60.2.0/24"]
  destination_address_prefix  = "*"
  resource_group_name         = data.azurerm_resource_group.main.name
  network_security_group_name = azurerm_network_security_group.ds.name
}

resource "azurerm_network_security_rule" "fw_replication" {
  name                        = "fw-replication"
  description                 = "fw-replication"
  priority                    = 140
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_ranges     = ["8989"]
  source_address_prefixes     = ["10.60.1.0/24", "10.20.0.0/16"]
  destination_address_prefix  = "*"
  resource_group_name         = data.azurerm_resource_group.main.name
  network_security_group_name = azurerm_network_security_group.ds.name
}

resource "azurerm_network_security_rule" "fw_sso_public" {
  name                        = "fw-sso-public"
  description                 = "fw-sso-public"
  priority                    = 160
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_ranges     = ["443"]
  source_address_prefixes     = ["0.0.0.0/0"]
  destination_address_prefix  = "*"
  resource_group_name         = data.azurerm_resource_group.main.name
  network_security_group_name = azurerm_network_security_group.pf_engine.name
}

resource "azurerm_network_security_rule" "fw_supplier_portal" {
  name                        = "fw-supplier-portal"
  description                 = "consumer supplier-portal-svc"
  priority                    = 120
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_ranges     = ["1636"]
  source_address_prefixes     = ["10.31.2.0/24"]
  destination_address_prefix  = "*"
  resource_group_name         = data.azurerm_resource_group.main.name
  network_security_group_name = azurerm_network_security_group.ds.name
}

resource "azurerm_user_assigned_identity" "identity_ds" {
  name                = "id-ciam-prod-ds"
  resource_group_name = data.azurerm_resource_group.main.name
  location            = data.azurerm_resource_group.main.location
  tags = {
    Principal = "pingds"
    Role      = "identity-ds"
    ManagedBy = "opsdir"
  }
}

resource "azurerm_role_assignment" "identity_ds_read_secret_ds_root_password" {
  scope                = "${data.azurerm_key_vault.kv_ciam_prod.id}/secrets/ds-root-password"
  role_definition_name = "Key Vault Secrets User"
  principal_id         = azurerm_user_assigned_identity.identity_ds.principal_id
}

resource "azurerm_role_assignment" "identity_ds_use_key_disk_encryption" {
  scope                = "${data.azurerm_key_vault.kv_ciam_prod.id}/keys/disk-cmk"
  role_definition_name = "Key Vault Crypto User"
  principal_id         = azurerm_user_assigned_identity.identity_ds.principal_id
}

resource "azurerm_role_assignment" "identity_ds_write_logs_audit_logs" {
  scope                = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-prod/providers/Microsoft.OperationalInsights/workspaces/law-ciam-prod-audit"
  role_definition_name = "Monitoring Metrics Publisher"
  principal_id         = azurerm_user_assigned_identity.identity_ds.principal_id
}

resource "azurerm_role_assignment" "identity_ds_write_storage_backup_target" {
  scope                = "${azurerm_storage_account.stciamprodbackups.id}/blobServices/default/containers/ds-backups"
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = azurerm_user_assigned_identity.identity_ds.principal_id
}

resource "azurerm_user_assigned_identity" "identity_pf" {
  name                = "id-ciam-prod-pf"
  resource_group_name = data.azurerm_resource_group.main.name
  location            = data.azurerm_resource_group.main.location
  tags = {
    Principal = "pingfederate"
    Role      = "identity-pf"
    ManagedBy = "opsdir"
  }
}

resource "azurerm_role_assignment" "identity_pf_read_secret_pf_admin_password" {
  scope                = "${data.azurerm_key_vault.kv_ciam_prod.id}/secrets/pf-admin-password"
  role_definition_name = "Key Vault Secrets User"
  principal_id         = azurerm_user_assigned_identity.identity_pf.principal_id
}

resource "azurerm_role_assignment" "identity_pf_read_secret_pf_ds_bind_password" {
  scope                = "${data.azurerm_key_vault.kv_ciam_prod.id}/secrets/pf-ds-bind-password"
  role_definition_name = "Key Vault Secrets User"
  principal_id         = azurerm_user_assigned_identity.identity_pf.principal_id
}

resource "azurerm_role_assignment" "identity_pf_read_secret_pf_signing_key" {
  scope                = "${data.azurerm_key_vault.kv_ciam_prod.id}/secrets/pf-signing-key"
  role_definition_name = "Key Vault Secrets User"
  principal_id         = azurerm_user_assigned_identity.identity_pf.principal_id
}

resource "azurerm_role_assignment" "identity_pf_write_logs_audit_logs" {
  scope                = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-prod/providers/Microsoft.OperationalInsights/workspaces/law-ciam-prod-audit"
  role_definition_name = "Monitoring Metrics Publisher"
  principal_id         = azurerm_user_assigned_identity.identity_pf.principal_id
}

resource "azurerm_network_interface" "am_1" {
  name                = "nic-am-1"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  ip_configuration {
    name                          = "primary"
    subnet_id                     = data.azurerm_subnet.snet_am.id
    private_ip_address_allocation = "Static"
    private_ip_address            = "10.60.3.21"
  }
}

resource "azurerm_network_interface_security_group_association" "am_1" {
  network_interface_id      = azurerm_network_interface.am_1.id
  network_security_group_id = azurerm_network_security_group.am.id
}

resource "azurerm_linux_virtual_machine" "am_1" {
  name                  = "am-1"
  computer_name         = "am-1"
  resource_group_name   = data.azurerm_resource_group.main.name
  location              = data.azurerm_resource_group.main.location
  size                  = "Standard_D2s_v5"
  zone                  = "1"
  admin_username        = "ciamadmin"
  network_interface_ids = [azurerm_network_interface.am_1.id]
  source_image_id       = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-images/providers/Microsoft.Compute/images/pingam-7.5.1-rhel9"
  admin_ssh_key {
    username   = "ciamadmin"
    public_key = var.admin_ssh_public_key
  }
  os_disk {
    caching                = "ReadWrite"
    storage_account_type   = "Premium_LRS"
    disk_encryption_set_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-prod/providers/Microsoft.Compute/diskEncryptionSets/des-ciam-prod"
  }
  tags = {
    Role      = "am"
    Hostname  = "am-1.az.internal.example-aero.test"
    Product   = "PingAM 7.5.1"
    ManagedBy = "opsdir"
  }
}

resource "azurerm_network_interface" "am_2" {
  name                = "nic-am-2"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  ip_configuration {
    name                          = "primary"
    subnet_id                     = data.azurerm_subnet.snet_am.id
    private_ip_address_allocation = "Static"
    private_ip_address            = "10.60.3.22"
  }
}

resource "azurerm_network_interface_security_group_association" "am_2" {
  network_interface_id      = azurerm_network_interface.am_2.id
  network_security_group_id = azurerm_network_security_group.am.id
}

resource "azurerm_linux_virtual_machine" "am_2" {
  name                  = "am-2"
  computer_name         = "am-2"
  resource_group_name   = data.azurerm_resource_group.main.name
  location              = data.azurerm_resource_group.main.location
  size                  = "Standard_D2s_v5"
  zone                  = "2"
  admin_username        = "ciamadmin"
  network_interface_ids = [azurerm_network_interface.am_2.id]
  source_image_id       = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-images/providers/Microsoft.Compute/images/pingam-7.5.1-rhel9"
  admin_ssh_key {
    username   = "ciamadmin"
    public_key = var.admin_ssh_public_key
  }
  os_disk {
    caching                = "ReadWrite"
    storage_account_type   = "Premium_LRS"
    disk_encryption_set_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-prod/providers/Microsoft.Compute/diskEncryptionSets/des-ciam-prod"
  }
  tags = {
    Role      = "am"
    Hostname  = "am-2.az.internal.example-aero.test"
    Product   = "PingAM 7.5.1"
    ManagedBy = "opsdir"
  }
}

resource "azurerm_network_interface" "ds_1" {
  name                = "nic-ds-1"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  ip_configuration {
    name                          = "primary"
    subnet_id                     = data.azurerm_subnet.snet_ds.id
    private_ip_address_allocation = "Static"
    private_ip_address            = "10.60.1.11"
  }
}

resource "azurerm_network_interface_security_group_association" "ds_1" {
  network_interface_id      = azurerm_network_interface.ds_1.id
  network_security_group_id = azurerm_network_security_group.ds.id
}

resource "azurerm_linux_virtual_machine" "ds_1" {
  name                  = "ds-1"
  computer_name         = "ds-1"
  resource_group_name   = data.azurerm_resource_group.main.name
  location              = data.azurerm_resource_group.main.location
  size                  = "Standard_D4s_v5"
  zone                  = "1"
  admin_username        = "ciamadmin"
  network_interface_ids = [azurerm_network_interface.ds_1.id]
  source_image_id       = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-images/providers/Microsoft.Compute/images/pingds-7.5.1-rhel9"
  admin_ssh_key {
    username   = "ciamadmin"
    public_key = var.admin_ssh_public_key
  }
  os_disk {
    caching                = "ReadWrite"
    storage_account_type   = "Premium_LRS"
    disk_encryption_set_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-prod/providers/Microsoft.Compute/diskEncryptionSets/des-ciam-prod"
  }
  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.identity_ds.id]
  }
  tags = {
    Role      = "ds"
    Hostname  = "ds-1.az.internal.example-aero.test"
    Product   = "PingDS 7.5.1"
    ManagedBy = "opsdir"
  }
}

# ds-1 mounts vol-ds-data at /opt/ds/db (its own configuration, not Terraform)

resource "azurerm_managed_disk" "ds_1_vol_ds_data" {
  name                   = "disk-ds-1-vol-ds-data"
  location               = data.azurerm_resource_group.main.location
  resource_group_name    = data.azurerm_resource_group.main.name
  zone                   = "1"
  storage_account_type   = "PremiumV2_LRS"
  create_option          = "Empty"
  disk_size_gb           = 500
  disk_iops_read_write   = 6000
  disk_mbps_read_write   = 250
  disk_encryption_set_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-prod/providers/Microsoft.Compute/diskEncryptionSets/des-ciam-prod"
  tags = {
    Volume    = "vol-ds-data"
    Role      = "volume-ds-data"
    Server    = "ds-1"
    ManagedBy = "opsdir"
  }
}

resource "azurerm_virtual_machine_data_disk_attachment" "ds_1_vol_ds_data" {
  managed_disk_id    = azurerm_managed_disk.ds_1_vol_ds_data.id
  virtual_machine_id = azurerm_linux_virtual_machine.ds_1.id
  lun                = 0
  caching            = "None"
}

resource "azurerm_network_interface" "ds_2" {
  name                = "nic-ds-2"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  ip_configuration {
    name                          = "primary"
    subnet_id                     = data.azurerm_subnet.snet_ds.id
    private_ip_address_allocation = "Static"
    private_ip_address            = "10.60.1.12"
  }
}

resource "azurerm_network_interface_security_group_association" "ds_2" {
  network_interface_id      = azurerm_network_interface.ds_2.id
  network_security_group_id = azurerm_network_security_group.ds.id
}

resource "azurerm_linux_virtual_machine" "ds_2" {
  name                  = "ds-2"
  computer_name         = "ds-2"
  resource_group_name   = data.azurerm_resource_group.main.name
  location              = data.azurerm_resource_group.main.location
  size                  = "Standard_D4s_v5"
  zone                  = "2"
  admin_username        = "ciamadmin"
  network_interface_ids = [azurerm_network_interface.ds_2.id]
  source_image_id       = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-images/providers/Microsoft.Compute/images/pingds-7.5.1-rhel9"
  admin_ssh_key {
    username   = "ciamadmin"
    public_key = var.admin_ssh_public_key
  }
  os_disk {
    caching                = "ReadWrite"
    storage_account_type   = "Premium_LRS"
    disk_encryption_set_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-prod/providers/Microsoft.Compute/diskEncryptionSets/des-ciam-prod"
  }
  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.identity_ds.id]
  }
  tags = {
    Role      = "ds"
    Hostname  = "ds-2.az.internal.example-aero.test"
    Product   = "PingDS 7.5.1"
    ManagedBy = "opsdir"
  }
}

# ds-2 mounts vol-ds-data at /opt/ds/db (its own configuration, not Terraform)

resource "azurerm_managed_disk" "ds_2_vol_ds_data" {
  name                   = "disk-ds-2-vol-ds-data"
  location               = data.azurerm_resource_group.main.location
  resource_group_name    = data.azurerm_resource_group.main.name
  zone                   = "2"
  storage_account_type   = "PremiumV2_LRS"
  create_option          = "Empty"
  disk_size_gb           = 500
  disk_iops_read_write   = 6000
  disk_mbps_read_write   = 250
  disk_encryption_set_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-prod/providers/Microsoft.Compute/diskEncryptionSets/des-ciam-prod"
  tags = {
    Volume    = "vol-ds-data"
    Role      = "volume-ds-data"
    Server    = "ds-2"
    ManagedBy = "opsdir"
  }
}

resource "azurerm_virtual_machine_data_disk_attachment" "ds_2_vol_ds_data" {
  managed_disk_id    = azurerm_managed_disk.ds_2_vol_ds_data.id
  virtual_machine_id = azurerm_linux_virtual_machine.ds_2.id
  lun                = 0
  caching            = "None"
}

resource "azurerm_network_interface" "ds_3" {
  name                = "nic-ds-3"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  ip_configuration {
    name                          = "primary"
    subnet_id                     = data.azurerm_subnet.snet_ds.id
    private_ip_address_allocation = "Static"
    private_ip_address            = "10.60.1.13"
  }
}

resource "azurerm_network_interface_security_group_association" "ds_3" {
  network_interface_id      = azurerm_network_interface.ds_3.id
  network_security_group_id = azurerm_network_security_group.ds.id
}

resource "azurerm_linux_virtual_machine" "ds_3" {
  name                  = "ds-3"
  computer_name         = "ds-3"
  resource_group_name   = data.azurerm_resource_group.main.name
  location              = data.azurerm_resource_group.main.location
  size                  = "Standard_D4s_v5"
  zone                  = "3"
  admin_username        = "ciamadmin"
  network_interface_ids = [azurerm_network_interface.ds_3.id]
  source_image_id       = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-images/providers/Microsoft.Compute/images/pingds-7.5.1-rhel9"
  admin_ssh_key {
    username   = "ciamadmin"
    public_key = var.admin_ssh_public_key
  }
  os_disk {
    caching                = "ReadWrite"
    storage_account_type   = "Premium_LRS"
    disk_encryption_set_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-prod/providers/Microsoft.Compute/diskEncryptionSets/des-ciam-prod"
  }
  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.identity_ds.id]
  }
  tags = {
    Role      = "ds"
    Hostname  = "ds-3.az.internal.example-aero.test"
    Product   = "PingDS 7.5.1"
    ManagedBy = "opsdir"
  }
}

# ds-3 mounts vol-ds-data at /opt/ds/db (its own configuration, not Terraform)

resource "azurerm_managed_disk" "ds_3_vol_ds_data" {
  name                   = "disk-ds-3-vol-ds-data"
  location               = data.azurerm_resource_group.main.location
  resource_group_name    = data.azurerm_resource_group.main.name
  zone                   = "3"
  storage_account_type   = "PremiumV2_LRS"
  create_option          = "Empty"
  disk_size_gb           = 500
  disk_iops_read_write   = 6000
  disk_mbps_read_write   = 250
  disk_encryption_set_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-prod/providers/Microsoft.Compute/diskEncryptionSets/des-ciam-prod"
  tags = {
    Volume    = "vol-ds-data"
    Role      = "volume-ds-data"
    Server    = "ds-3"
    ManagedBy = "opsdir"
  }
}

resource "azurerm_virtual_machine_data_disk_attachment" "ds_3_vol_ds_data" {
  managed_disk_id    = azurerm_managed_disk.ds_3_vol_ds_data.id
  virtual_machine_id = azurerm_linux_virtual_machine.ds_3.id
  lun                = 0
  caching            = "None"
}

resource "azurerm_network_interface" "idm_1" {
  name                = "nic-idm-1"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  ip_configuration {
    name                          = "primary"
    subnet_id                     = data.azurerm_subnet.snet_idm.id
    private_ip_address_allocation = "Static"
    private_ip_address            = "10.60.6.21"
  }
}

resource "azurerm_network_interface_security_group_association" "idm_1" {
  network_interface_id      = azurerm_network_interface.idm_1.id
  network_security_group_id = azurerm_network_security_group.idm.id
}

resource "azurerm_linux_virtual_machine" "idm_1" {
  name                  = "idm-1"
  computer_name         = "idm-1"
  resource_group_name   = data.azurerm_resource_group.main.name
  location              = data.azurerm_resource_group.main.location
  size                  = "Standard_D2s_v5"
  zone                  = "1"
  admin_username        = "ciamadmin"
  network_interface_ids = [azurerm_network_interface.idm_1.id]
  source_image_id       = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-images/providers/Microsoft.Compute/images/pingidm-7.5.0-rhel9"
  admin_ssh_key {
    username   = "ciamadmin"
    public_key = var.admin_ssh_public_key
  }
  os_disk {
    caching                = "ReadWrite"
    storage_account_type   = "Premium_LRS"
    disk_encryption_set_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-prod/providers/Microsoft.Compute/diskEncryptionSets/des-ciam-prod"
  }
  tags = {
    Role      = "idm"
    Hostname  = "idm-1.az.internal.example-aero.test"
    Product   = "PingIDM 7.5.0"
    ManagedBy = "opsdir"
  }
}

resource "azurerm_network_interface" "ig_1" {
  name                = "nic-ig-1"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  ip_configuration {
    name                          = "primary"
    subnet_id                     = data.azurerm_subnet.snet_ig.id
    private_ip_address_allocation = "Static"
    private_ip_address            = "10.60.10.21"
  }
}

resource "azurerm_network_interface_security_group_association" "ig_1" {
  network_interface_id      = azurerm_network_interface.ig_1.id
  network_security_group_id = azurerm_network_security_group.ig.id
}

resource "azurerm_linux_virtual_machine" "ig_1" {
  name                  = "ig-1"
  computer_name         = "ig-1"
  resource_group_name   = data.azurerm_resource_group.main.name
  location              = data.azurerm_resource_group.main.location
  size                  = "Standard_D2s_v5"
  zone                  = "1"
  admin_username        = "ciamadmin"
  network_interface_ids = [azurerm_network_interface.ig_1.id]
  source_image_id       = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-images/providers/Microsoft.Compute/images/pinggateway-2024.11.0-rhel9"
  admin_ssh_key {
    username   = "ciamadmin"
    public_key = var.admin_ssh_public_key
  }
  os_disk {
    caching                = "ReadWrite"
    storage_account_type   = "Premium_LRS"
    disk_encryption_set_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-prod/providers/Microsoft.Compute/diskEncryptionSets/des-ciam-prod"
  }
  tags = {
    Role      = "ig"
    Hostname  = "ig-1.az.internal.example-aero.test"
    Product   = "PingGateway 2024.11.0"
    ManagedBy = "opsdir"
  }
}

resource "azurerm_network_interface" "pf_admin_1" {
  name                = "nic-pf-admin-1"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  ip_configuration {
    name                          = "primary"
    subnet_id                     = data.azurerm_subnet.snet_pf.id
    private_ip_address_allocation = "Static"
    private_ip_address            = "10.60.2.10"
  }
}

resource "azurerm_network_interface_security_group_association" "pf_admin_1" {
  network_interface_id      = azurerm_network_interface.pf_admin_1.id
  network_security_group_id = azurerm_network_security_group.pf_admin.id
}

resource "azurerm_linux_virtual_machine" "pf_admin_1" {
  name                  = "pf-admin-1"
  computer_name         = "pf-admin-1"
  resource_group_name   = data.azurerm_resource_group.main.name
  location              = data.azurerm_resource_group.main.location
  size                  = "Standard_D2s_v5"
  zone                  = "1"
  admin_username        = "ciamadmin"
  network_interface_ids = [azurerm_network_interface.pf_admin_1.id]
  source_image_id       = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-images/providers/Microsoft.Compute/images/pingfederate-12.1.4-rhel9"
  admin_ssh_key {
    username   = "ciamadmin"
    public_key = var.admin_ssh_public_key
  }
  os_disk {
    caching                = "ReadWrite"
    storage_account_type   = "Premium_LRS"
    disk_encryption_set_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-prod/providers/Microsoft.Compute/diskEncryptionSets/des-ciam-prod"
  }
  tags = {
    Role      = "pf-admin"
    Hostname  = "pf-admin-1.az.internal.example-aero.test"
    Product   = "PingFederate 12.1.4"
    ManagedBy = "opsdir"
  }
}

resource "azurerm_network_interface" "pf_engine_1" {
  name                = "nic-pf-engine-1"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  ip_configuration {
    name                          = "primary"
    subnet_id                     = data.azurerm_subnet.snet_pf.id
    private_ip_address_allocation = "Static"
    private_ip_address            = "10.60.2.21"
  }
}

resource "azurerm_network_interface_security_group_association" "pf_engine_1" {
  network_interface_id      = azurerm_network_interface.pf_engine_1.id
  network_security_group_id = azurerm_network_security_group.pf_engine.id
}

resource "azurerm_linux_virtual_machine" "pf_engine_1" {
  name                  = "pf-engine-1"
  computer_name         = "pf-engine-1"
  resource_group_name   = data.azurerm_resource_group.main.name
  location              = data.azurerm_resource_group.main.location
  size                  = "Standard_D2s_v5"
  zone                  = "1"
  admin_username        = "ciamadmin"
  network_interface_ids = [azurerm_network_interface.pf_engine_1.id]
  source_image_id       = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-images/providers/Microsoft.Compute/images/pingfederate-12.1.4-rhel9"
  admin_ssh_key {
    username   = "ciamadmin"
    public_key = var.admin_ssh_public_key
  }
  os_disk {
    caching                = "ReadWrite"
    storage_account_type   = "Premium_LRS"
    disk_encryption_set_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-prod/providers/Microsoft.Compute/diskEncryptionSets/des-ciam-prod"
  }
  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.identity_pf.id]
  }
  tags = {
    Role      = "pf-engine"
    Hostname  = "pf-engine-1.az.internal.example-aero.test"
    Product   = "PingFederate 12.1.4"
    ManagedBy = "opsdir"
  }
}

resource "azurerm_network_interface" "pf_engine_2" {
  name                = "nic-pf-engine-2"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  ip_configuration {
    name                          = "primary"
    subnet_id                     = data.azurerm_subnet.snet_pf.id
    private_ip_address_allocation = "Static"
    private_ip_address            = "10.60.2.22"
  }
}

resource "azurerm_network_interface_security_group_association" "pf_engine_2" {
  network_interface_id      = azurerm_network_interface.pf_engine_2.id
  network_security_group_id = azurerm_network_security_group.pf_engine.id
}

resource "azurerm_linux_virtual_machine" "pf_engine_2" {
  name                  = "pf-engine-2"
  computer_name         = "pf-engine-2"
  resource_group_name   = data.azurerm_resource_group.main.name
  location              = data.azurerm_resource_group.main.location
  size                  = "Standard_D2s_v5"
  zone                  = "2"
  admin_username        = "ciamadmin"
  network_interface_ids = [azurerm_network_interface.pf_engine_2.id]
  source_image_id       = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-images/providers/Microsoft.Compute/images/pingfederate-12.1.4-rhel9"
  admin_ssh_key {
    username   = "ciamadmin"
    public_key = var.admin_ssh_public_key
  }
  os_disk {
    caching                = "ReadWrite"
    storage_account_type   = "Premium_LRS"
    disk_encryption_set_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-prod/providers/Microsoft.Compute/diskEncryptionSets/des-ciam-prod"
  }
  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.identity_pf.id]
  }
  tags = {
    Role      = "pf-engine"
    Hostname  = "pf-engine-2.az.internal.example-aero.test"
    Product   = "PingFederate 12.1.4"
    ManagedBy = "opsdir"
  }
}

data "azurerm_public_ip" "svc_apps" {
  name                = "pip-ciam-apps-prod"
  resource_group_name = data.azurerm_resource_group.main.name
}

resource "azurerm_lb" "svc_apps" {
  name                = "lb-ciam-prod-svc-apps"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  sku                 = "Standard"
  frontend_ip_configuration {
    name                 = "frontend"
    public_ip_address_id = data.azurerm_public_ip.svc_apps.id
  }
  tags = {
    Service   = "apps.example-aero.test"
    ManagedBy = "opsdir"
  }
}

resource "azurerm_lb_backend_address_pool" "svc_apps" {
  name            = "servers"
  loadbalancer_id = azurerm_lb.svc_apps.id
}

resource "azurerm_network_interface_backend_address_pool_association" "svc_apps_ig_1" {
  network_interface_id    = azurerm_network_interface.ig_1.id
  ip_configuration_name   = "primary"
  backend_address_pool_id = azurerm_lb_backend_address_pool.svc_apps.id
}

resource "azurerm_lb_probe" "svc_apps_443" {
  name            = "tcp-443"
  loadbalancer_id = azurerm_lb.svc_apps.id
  protocol        = "Tcp"
  port            = 443
}

resource "azurerm_lb_rule" "svc_apps_443" {
  name                           = "tcp-443"
  loadbalancer_id                = azurerm_lb.svc_apps.id
  protocol                       = "Tcp"
  frontend_port                  = 443
  backend_port                   = 443
  frontend_ip_configuration_name = "frontend"
  backend_address_pool_ids       = [azurerm_lb_backend_address_pool.svc_apps.id]
  probe_id                       = azurerm_lb_probe.svc_apps_443.id
}

# `apps.example-aero.test` is in a zone corporate-dns runs: not rendered here (the plan drafts the request to them)

resource "azurerm_lb" "svc_ldaps" {
  name                = "lb-ciam-prod-svc-ldaps"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  sku                 = "Standard"
  frontend_ip_configuration {
    name                          = "frontend"
    zones                         = ["1", "2", "3"]
    subnet_id                     = data.azurerm_subnet.snet_ds.id
    private_ip_address_allocation = "Static"
    private_ip_address            = "10.60.1.100"
  }
  tags = {
    Service   = "ldap.id.example-aero.test"
    ManagedBy = "opsdir"
  }
}

resource "azurerm_lb_backend_address_pool" "svc_ldaps" {
  name            = "servers"
  loadbalancer_id = azurerm_lb.svc_ldaps.id
}

resource "azurerm_network_interface_backend_address_pool_association" "svc_ldaps_ds_1" {
  network_interface_id    = azurerm_network_interface.ds_1.id
  ip_configuration_name   = "primary"
  backend_address_pool_id = azurerm_lb_backend_address_pool.svc_ldaps.id
}

resource "azurerm_network_interface_backend_address_pool_association" "svc_ldaps_ds_2" {
  network_interface_id    = azurerm_network_interface.ds_2.id
  ip_configuration_name   = "primary"
  backend_address_pool_id = azurerm_lb_backend_address_pool.svc_ldaps.id
}

resource "azurerm_network_interface_backend_address_pool_association" "svc_ldaps_ds_3" {
  network_interface_id    = azurerm_network_interface.ds_3.id
  ip_configuration_name   = "primary"
  backend_address_pool_id = azurerm_lb_backend_address_pool.svc_ldaps.id
}

resource "azurerm_lb_probe" "svc_ldaps_1636" {
  name            = "tcp-1636"
  loadbalancer_id = azurerm_lb.svc_ldaps.id
  protocol        = "Tcp"
  port            = 1636
}

resource "azurerm_lb_rule" "svc_ldaps_1636" {
  name                           = "tcp-1636"
  loadbalancer_id                = azurerm_lb.svc_ldaps.id
  protocol                       = "Tcp"
  frontend_port                  = 1636
  backend_port                   = 1636
  frontend_ip_configuration_name = "frontend"
  backend_address_pool_ids       = [azurerm_lb_backend_address_pool.svc_ldaps.id]
  probe_id                       = azurerm_lb_probe.svc_ldaps_1636.id
}

resource "azurerm_private_dns_a_record" "svc_ldaps" {
  name                = "ldap"
  zone_name           = "id.example-aero.test"
  resource_group_name = data.azurerm_resource_group.main.name
  ttl                 = 300
  records             = ["10.60.1.100"]
}

data "azurerm_public_ip" "svc_login" {
  name                = "pip-ciam-login-prod"
  resource_group_name = data.azurerm_resource_group.main.name
}

resource "azurerm_web_application_firewall_policy" "svc_login" {
  name                = "waf-ciam-prod-svc_login"
  resource_group_name = data.azurerm_resource_group.main.name
  location            = data.azurerm_resource_group.main.location
  policy_settings {
    enabled            = true
    mode               = "Prevention"
    request_body_check = true
  }
  custom_rules {
    name                 = "ratelogin"
    priority             = 1
    rule_type            = "RateLimitRule"
    rate_limit_duration  = "FiveMins"
    rate_limit_threshold = 300
    group_rate_limit_by  = "ClientAddr"
    match_conditions {
      match_variables {
        variable_name = "RequestUri"
      }
      operator     = "Regex"
      match_values = ["^/am/json/realms/[^?#]+/authenticate$"]
    }
    action = "Block"
  }
  custom_rules {
    name                 = "ratetoken"
    priority             = 2
    rule_type            = "RateLimitRule"
    rate_limit_duration  = "FiveMins"
    rate_limit_threshold = 600
    group_rate_limit_by  = "ClientAddr"
    match_conditions {
      match_variables {
        variable_name = "RequestUri"
      }
      operator     = "Regex"
      match_values = ["^/am/oauth2/access_token$", "^/am/oauth2/realms/[^?#]+/access_token$"]
    }
    action = "Block"
  }
  managed_rules {
    # exclusions apply on every path, not only the endpoint kind named
    exclusion {
      match_variable          = "RequestArgNames"
      selector                = "SAMLResponse"
      selector_match_operator = "Equals"
      excluded_rule_set {
        type    = "Microsoft_DefaultRuleSet"
        version = "2.1"
      }
    }
    managed_rule_set {
      type    = "Microsoft_DefaultRuleSet"
      version = "2.1"
    }
    managed_rule_set {
      type    = "Microsoft_BotManagerRuleSet"
      version = "1.1"
    }
  }
  tags = {
    ManagedBy = "opsdir"
  }
}

# DDoS network-advanced: DDoS Network Protection is a plan linked to the virtual network the landing zone keeps (or IP Protection on the public address): ask its owners

resource "azurerm_application_gateway" "svc_login" {
  name                = "agw-ciam-prod-svc-login"
  resource_group_name = data.azurerm_resource_group.main.name
  location            = data.azurerm_resource_group.main.location
  zones               = ["1", "2", "3"]
  sku {
    name = "WAF_v2"
    tier = "WAF_v2"
  }
  autoscale_configuration {
    min_capacity = 2
    max_capacity = 10
  }
  gateway_ip_configuration {
    name      = "gateway"
    subnet_id = data.azurerm_subnet.snet_edge.id
  }
  frontend_ip_configuration {
    name                 = "frontend"
    public_ip_address_id = data.azurerm_public_ip.svc_login.id
  }
  frontend_port {
    name = "port-443"
    port = 443
  }
  backend_address_pool {
    name         = "servers"
    ip_addresses = ["10.60.3.21", "10.60.3.22"]
  }
  backend_http_settings {
    name                  = "servers-443"
    port                  = 443
    protocol              = "Https"
    cookie_based_affinity = "Enabled"
    request_timeout       = 30
    host_name             = "login.example-aero.test"
    # Application Gateway v2 validates the servers' certificates (chain and name)
    probe_name = "health-443"
  }
  probe {
    name                = "health-443"
    protocol            = "Https"
    host                = "login.example-aero.test"
    path                = "/am/json/health/ready"
    interval            = 30
    timeout             = 30
    unhealthy_threshold = 3
    match {
      status_code = ["200-399"]
    }
  }
  http_listener {
    name                           = "listener-443"
    frontend_ip_configuration_name = "frontend"
    frontend_port_name             = "port-443"
    protocol                       = "Https"
  }
  request_routing_rule {
    name                       = "route-443"
    priority                   = 100
    rule_type                  = "Basic"
    http_listener_name         = "listener-443"
    backend_address_pool_name  = "servers"
    backend_http_settings_name = "servers-443"
  }
  # UNBOUND: no Key Vault certificate holds this service's certificate in this environment
  ssl_policy {
    policy_type = "Predefined"
    policy_name = "AppGwSslPolicy20220101"
  }
  firewall_policy_id = azurerm_web_application_firewall_policy.svc_login.id
  tags = {
    Service   = "login.example-aero.test"
    ManagedBy = "opsdir"
  }
}

# `login.example-aero.test` is in a zone corporate-dns runs: not rendered here (the plan drafts the request to them)

data "azurerm_public_ip" "svc_sso" {
  name                = "pip-ciam-sso-prod"
  resource_group_name = data.azurerm_resource_group.main.name
}

resource "azurerm_user_assigned_identity" "svc_sso_gateway" {
  name                = "id-agw-ciam-prod-svc_sso"
  resource_group_name = data.azurerm_resource_group.main.name
  location            = data.azurerm_resource_group.main.location
}

data "azurerm_key_vault" "svc_sso_tls" {
  name                = "kv-ciam-prod"
  resource_group_name = data.azurerm_resource_group.main.name
}

resource "azurerm_role_assignment" "svc_sso_gateway_certificate" {
  scope                = data.azurerm_key_vault.svc_sso_tls.id
  role_definition_name = "Key Vault Secrets User"
  principal_id         = azurerm_user_assigned_identity.svc_sso_gateway.principal_id
}

resource "azurerm_web_application_firewall_policy" "svc_sso" {
  name                = "waf-ciam-prod-svc_sso"
  resource_group_name = data.azurerm_resource_group.main.name
  location            = data.azurerm_resource_group.main.location
  policy_settings {
    enabled            = true
    mode               = "Prevention"
    request_body_check = true
  }
  custom_rules {
    name                 = "ratelogin"
    priority             = 1
    rule_type            = "RateLimitRule"
    rate_limit_duration  = "FiveMins"
    rate_limit_threshold = 300
    group_rate_limit_by  = "ClientAddr"
    match_conditions {
      match_variables {
        variable_name = "RequestUri"
      }
      operator     = "Regex"
      match_values = ["^/as/authorization\\.oauth2$", "^/idp/SSO\\.saml2$"]
    }
    action = "Block"
  }
  custom_rules {
    name                 = "ratetoken"
    priority             = 2
    rule_type            = "RateLimitRule"
    rate_limit_duration  = "FiveMins"
    rate_limit_threshold = 600
    group_rate_limit_by  = "ClientAddr"
    match_conditions {
      match_variables {
        variable_name = "RequestUri"
      }
      operator     = "Regex"
      match_values = ["^/as/token\\.oauth2$"]
    }
    action = "Block"
  }
  managed_rules {
    # exclusions apply on every path, not only the endpoint kind named
    exclusion {
      match_variable          = "RequestArgNames"
      selector                = "SAMLResponse"
      selector_match_operator = "Equals"
      excluded_rule_set {
        type    = "Microsoft_DefaultRuleSet"
        version = "2.1"
      }
    }
    managed_rule_set {
      type    = "Microsoft_DefaultRuleSet"
      version = "2.1"
    }
    managed_rule_set {
      type    = "Microsoft_BotManagerRuleSet"
      version = "1.1"
    }
  }
  tags = {
    ManagedBy = "opsdir"
  }
}

# DDoS network-advanced: DDoS Network Protection is a plan linked to the virtual network the landing zone keeps (or IP Protection on the public address): ask its owners

resource "azurerm_application_gateway" "svc_sso" {
  name                = "agw-ciam-prod-svc-sso"
  resource_group_name = data.azurerm_resource_group.main.name
  location            = data.azurerm_resource_group.main.location
  zones               = ["1", "2", "3"]
  sku {
    name = "WAF_v2"
    tier = "WAF_v2"
  }
  autoscale_configuration {
    min_capacity = 2
    max_capacity = 10
  }
  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.svc_sso_gateway.id]
  }
  gateway_ip_configuration {
    name      = "gateway"
    subnet_id = data.azurerm_subnet.snet_edge.id
  }
  frontend_ip_configuration {
    name                 = "frontend"
    public_ip_address_id = data.azurerm_public_ip.svc_sso.id
  }
  frontend_port {
    name = "port-443"
    port = 443
  }
  backend_address_pool {
    name         = "servers"
    ip_addresses = ["10.60.2.21", "10.60.2.22"]
  }
  backend_http_settings {
    name                  = "servers-443"
    port                  = 443
    protocol              = "Https"
    cookie_based_affinity = "Enabled"
    request_timeout       = 30
    host_name             = "sso.example-aero.test"
    # Application Gateway v2 validates the servers' certificates (chain and name)
    probe_name = "health-443"
  }
  probe {
    name                = "health-443"
    protocol            = "Https"
    host                = "sso.example-aero.test"
    path                = "/pf/heartbeat.ping"
    interval            = 30
    timeout             = 30
    unhealthy_threshold = 3
    match {
      status_code = ["200-399"]
    }
  }
  http_listener {
    name                           = "listener-443"
    frontend_ip_configuration_name = "frontend"
    frontend_port_name             = "port-443"
    protocol                       = "Https"
    ssl_certificate_name           = "tls"
  }
  request_routing_rule {
    name                       = "route-443"
    priority                   = 100
    rule_type                  = "Basic"
    http_listener_name         = "listener-443"
    backend_address_pool_name  = "servers"
    backend_http_settings_name = "servers-443"
  }
  ssl_certificate {
    name                = "tls"
    key_vault_secret_id = "${data.azurerm_key_vault.svc_sso_tls.vault_uri}secrets/sso-tls-2026"
  }
  ssl_policy {
    policy_type = "Predefined"
    policy_name = "AppGwSslPolicy20220101"
  }
  firewall_policy_id = azurerm_web_application_firewall_policy.svc_sso.id
  tags = {
    Service   = "sso.example-aero.test"
    ManagedBy = "opsdir"
  }
  depends_on = [azurerm_role_assignment.svc_sso_gateway_certificate]
}

# `sso.example-aero.test` is in a zone corporate-dns runs: not rendered here (the plan drafts the request to them)

# Egress firewall 'egress-firewall' is kept by network-security; its allowlist is rendered in their root, not here.

# Egress forward-proxy 'hub-proxy' is kept by network-security; its allowlist is rendered in their root, not here.

data "azurerm_key_vault" "pe_secrets_kv_ciam_prod" {
  name                = "kv-ciam-prod"
  resource_group_name = data.azurerm_resource_group.main.name
}

resource "azurerm_private_endpoint" "pe_secrets" {
  name                = "pe-ciam-prod-pe-secrets"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  subnet_id           = data.azurerm_subnet.snet_pf.id
  private_service_connection {
    name                           = "pe-secrets"
    private_connection_resource_id = data.azurerm_key_vault.pe_secrets_kv_ciam_prod.id
    subresource_names              = ["vault"]
    is_manual_connection           = false
  }
  ip_configuration {
    name               = "primary"
    private_ip_address = "10.60.2.50"
    subresource_name   = "vault"
    member_name        = "default"
  }
  private_dns_zone_group {
    name                 = "default"
    private_dns_zone_ids = ["/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-hub-dns/providers/Microsoft.Network/privateDnsZones/privatelink.vaultcore.azure.net"]
  }
  tags = {
    Role      = "private-secrets"
    ManagedBy = "opsdir"
  }
}

resource "azurerm_private_link_service" "ldaps_link" {
  name                                        = "pls-ciam-prod-ldaps-link"
  location                                    = data.azurerm_resource_group.main.location
  resource_group_name                         = data.azurerm_resource_group.main.name
  load_balancer_frontend_ip_configuration_ids = [azurerm_lb.svc_ldaps.frontend_ip_configuration[0].id]
  nat_ip_configuration {
    name      = "primary"
    primary   = true
    subnet_id = data.azurerm_subnet.snet_ds.id
  }
  visibility_subscription_ids = ["55555555-6666-7777-8888-999999999999"]
  tags = {
    Role      = "ldaps-endpoint-service"
    ManagedBy = "opsdir"
  }
}

variable "psql_ciam_prod_pf_grants_admin_login" {
  type        = string
  description = "The administrator login of database psql-ciam-prod-pf-grants"
}

variable "psql_ciam_prod_pf_grants_private_dns_zone_id" {
  type        = string
  description = "The private DNS zone ID database psql-ciam-prod-pf-grants registers in (privatelink.postgresql.database.azure.com)"
}

data "azurerm_key_vault" "psql_ciam_prod_pf_grants_cmk" {
  name                = "kv-ciam-prod"
  resource_group_name = data.azurerm_resource_group.main.name
}

data "azurerm_key_vault_key" "psql_ciam_prod_pf_grants_cmk" {
  name         = "disk-cmk"
  key_vault_id = data.azurerm_key_vault.psql_ciam_prod_pf_grants_cmk.id
}

resource "azurerm_user_assigned_identity" "psql_ciam_prod_pf_grants_cmk" {
  name                = "id-psql-ciam-prod-pf-grants-cmk"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  tags = {
    Role      = "pf-grants-db"
    ManagedBy = "opsdir"
  }
}

resource "azurerm_role_assignment" "psql_ciam_prod_pf_grants_cmk" {
  scope                = data.azurerm_key_vault_key.psql_ciam_prod_pf_grants_cmk.resource_versionless_id
  role_definition_name = "Key Vault Crypto Service Encryption User"
  principal_id         = azurerm_user_assigned_identity.psql_ciam_prod_pf_grants_cmk.principal_id
}

# psql-ciam-prod-pf-grants: its administrator password is read when applied and written write-only: no Terraform state holds it

data "azurerm_key_vault" "psql_ciam_prod_pf_grants_admin" {
  name                = "kv-ciam-prod"
  resource_group_name = data.azurerm_resource_group.main.name
}

ephemeral "azurerm_key_vault_secret" "psql_ciam_prod_pf_grants_admin" {
  name         = "pf-grants-db-password"
  key_vault_id = data.azurerm_key_vault.psql_ciam_prod_pf_grants_admin.id
}

resource "azurerm_network_security_group" "pf_grants_db" {
  name                = "nsg-ciam-prod-pf-grants-db"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  tags = {
    Role      = "pf-grants-db"
    ManagedBy = "opsdir"
  }
}

resource "azurerm_network_security_rule" "pf_grants_db_clients" {
  name                        = "pf-grants-db-clients"
  description                 = "clients of database psql-ciam-prod-pf-grants"
  priority                    = 100
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_ranges     = ["5432"]
  source_address_prefixes     = ["10.60.2.0/24"]
  destination_address_prefix  = "*"
  resource_group_name         = data.azurerm_resource_group.main.name
  network_security_group_name = azurerm_network_security_group.pf_grants_db.name
}

resource "azurerm_subnet_network_security_group_association" "pf_grants_db" {
  subnet_id                 = data.azurerm_subnet.snet_db.id
  network_security_group_id = azurerm_network_security_group.pf_grants_db.id
}

resource "azurerm_postgresql_flexible_server" "psql_ciam_prod_pf_grants" {
  name                              = "psql-ciam-prod-pf-grants"
  resource_group_name               = data.azurerm_resource_group.main.name
  location                          = data.azurerm_resource_group.main.location
  version                           = "16"
  sku_name                          = "GP_Standard_D2ds_v5"
  storage_mb                        = 131072
  zone                              = "1"
  backup_retention_days             = 14
  delegated_subnet_id               = data.azurerm_subnet.snet_db.id
  private_dns_zone_id               = var.psql_ciam_prod_pf_grants_private_dns_zone_id
  public_network_access_enabled     = false
  administrator_login               = var.psql_ciam_prod_pf_grants_admin_login
  administrator_password_wo         = ephemeral.azurerm_key_vault_secret.psql_ciam_prod_pf_grants_admin.value
  administrator_password_wo_version = 1
  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.psql_ciam_prod_pf_grants_cmk.id]
  }
  customer_managed_key {
    key_vault_key_id                  = data.azurerm_key_vault_key.psql_ciam_prod_pf_grants_cmk.id
    primary_user_assigned_identity_id = azurerm_user_assigned_identity.psql_ciam_prod_pf_grants_cmk.id
  }
  depends_on = [azurerm_role_assignment.psql_ciam_prod_pf_grants_cmk]
  tags = {
    Role      = "pf-grants-db"
    ManagedBy = "opsdir"
  }
}

resource "azurerm_postgresql_flexible_server_configuration" "psql_ciam_prod_pf_grants_idle_in_transaction_session_timeout" {
  name      = "idle_in_transaction_session_timeout"
  server_id = azurerm_postgresql_flexible_server.psql_ciam_prod_pf_grants.id
  value     = "60000"
}

resource "azurerm_postgresql_flexible_server_configuration" "psql_ciam_prod_pf_grants_log_min_duration_statement" {
  name      = "log_min_duration_statement"
  server_id = azurerm_postgresql_flexible_server.psql_ciam_prod_pf_grants.id
  value     = "1000"
}

resource "azurerm_management_lock" "psql_ciam_prod_pf_grants" {
  name       = "psql-ciam-prod-pf-grants-no-delete"
  scope      = azurerm_postgresql_flexible_server.psql_ciam_prod_pf_grants.id
  lock_level = "CanNotDelete"
  notes      = "Deletion protection of database psql-ciam-prod-pf-grants (role pf-grants-db)"
}

import {
  to = azurerm_postgresql_flexible_server.psql_ciam_prod_pf_grants
  id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-prod/providers/Microsoft.DBforPostgreSQL/flexibleServers/psql-ciam-prod-pf-grants"
}

data "azurerm_key_vault" "stciamprodbackups_storage_cmk" {
  name                = "kv-ciam-prod"
  resource_group_name = data.azurerm_resource_group.main.name
}

data "azurerm_key_vault_key" "stciamprodbackups_storage_cmk" {
  name         = "disk-cmk"
  key_vault_id = data.azurerm_key_vault.stciamprodbackups_storage_cmk.id
}

resource "azurerm_user_assigned_identity" "stciamprodbackups_storage_cmk" {
  name                = "id-backup-cmk"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  tags = {
    Role      = "backup-target"
    ManagedBy = "opsdir"
  }
}

resource "azurerm_role_assignment" "stciamprodbackups_storage_cmk" {
  scope                = data.azurerm_key_vault_key.stciamprodbackups_storage_cmk.resource_versionless_id
  role_definition_name = "Key Vault Crypto Service Encryption User"
  principal_id         = azurerm_user_assigned_identity.stciamprodbackups_storage_cmk.principal_id
}

resource "azurerm_storage_account" "stciamprodbackups" {
  name                            = "stciamprodbackups"
  resource_group_name             = data.azurerm_resource_group.main.name
  location                        = data.azurerm_resource_group.main.location
  account_tier                    = "Standard"
  account_replication_type        = "ZRS"
  min_tls_version                 = "TLS1_2"
  https_traffic_only_enabled      = true
  allow_nested_items_to_be_public = false
  blob_properties {
    versioning_enabled = true
  }
  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.stciamprodbackups_storage_cmk.id]
  }
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "azurerm_storage_account_customer_managed_key" "stciamprodbackups" {
  storage_account_id        = azurerm_storage_account.stciamprodbackups.id
  key_vault_id              = data.azurerm_key_vault_key.stciamprodbackups_storage_cmk.key_vault_id
  key_name                  = data.azurerm_key_vault_key.stciamprodbackups_storage_cmk.name
  user_assigned_identity_id = azurerm_user_assigned_identity.stciamprodbackups_storage_cmk.id
  depends_on                = [azurerm_role_assignment.stciamprodbackups_storage_cmk]
}

resource "azurerm_storage_management_policy" "stciamprodbackups" {
  storage_account_id = azurerm_storage_account.stciamprodbackups.id
  rule {
    name    = "ciam-ds-backups"
    enabled = true
    filters {
      blob_types   = ["blockBlob"]
      prefix_match = ["ds-backups/"]
    }
    actions {
      base_blob {
        tier_to_cold_after_days_since_modification_greater_than = 30
        delete_after_days_since_modification_greater_than       = 90
      }
      version {
        delete_after_days_since_creation = 7
      }
    }
  }
}

resource "azurerm_storage_container" "backup" {
  name                  = "ds-backups"
  storage_account_id    = azurerm_storage_account.stciamprodbackups.id
  container_access_type = "private"
  metadata = {
    role      = "backup-target"
    managedby = "opsdir"
  }
}

resource "azurerm_private_dns_resolver_forwarding_rule" "fwd_corp_ad_0" {
  name                      = "fwd-corp-ad-0"
  dns_forwarding_ruleset_id = var.dns_forwarding_ruleset_id
  domain_name               = "corp.example-aero.internal."
  enabled                   = true
  target_dns_servers {
    ip_address = "10.40.0.53"
    port       = 53
  }
  target_dns_servers {
    ip_address = "10.40.0.54"
    port       = 53
  }
}

data "azurerm_key_vault" "kv_ciam_prod" {
  name                = "kv-ciam-prod"
  resource_group_name = data.azurerm_resource_group.main.name
}

data "azurerm_key_vault_secrets" "kv_ciam_prod" {
  # names only: no secret value enters Terraform state
  key_vault_id = data.azurerm_key_vault.kv_ciam_prod.id
  lifecycle {
    postcondition {
      condition     = contains(self.names, "am-admin-password")
      error_message = "Key Vault kv-ciam-prod has no secret am-admin-password (role am-admin-password)"
    }
    postcondition {
      condition     = contains(self.names, "am-ds-bind-password")
      error_message = "Key Vault kv-ciam-prod has no secret am-ds-bind-password (role am-ds-bind-password)"
    }
    postcondition {
      condition     = contains(self.names, "am-keystore")
      error_message = "Key Vault kv-ciam-prod has no secret am-keystore (role am-keystore)"
    }
    postcondition {
      condition     = contains(self.names, "ds-deployment-id")
      error_message = "Key Vault kv-ciam-prod has no secret ds-deployment-id (role ds-deployment-id)"
    }
    postcondition {
      condition     = contains(self.names, "ds-deployment-password")
      error_message = "Key Vault kv-ciam-prod has no secret ds-deployment-password (role ds-deployment-password)"
    }
    postcondition {
      condition     = contains(self.names, "ds-root-password")
      error_message = "Key Vault kv-ciam-prod has no secret ds-root-password (role ds-root-password)"
    }
    postcondition {
      condition     = contains(self.names, "ds-tls-keystore")
      error_message = "Key Vault kv-ciam-prod has no secret ds-tls-keystore (role ds-tls-keystore)"
    }
    postcondition {
      condition     = contains(self.names, "idm-admin-password")
      error_message = "Key Vault kv-ciam-prod has no secret idm-admin-password (role idm-admin-password)"
    }
    postcondition {
      condition     = contains(self.names, "idm-ds-bind-password")
      error_message = "Key Vault kv-ciam-prod has no secret idm-ds-bind-password (role idm-ds-bind-password)"
    }
    postcondition {
      condition     = contains(self.names, "idm-hrdb-password")
      error_message = "Key Vault kv-ciam-prod has no secret idm-hrdb-password (role idm-hrdb-password)"
    }
    postcondition {
      condition     = contains(self.names, "idm-keystore")
      error_message = "Key Vault kv-ciam-prod has no secret idm-keystore (role idm-keystore)"
    }
    postcondition {
      condition     = contains(self.names, "ig-keystore")
      error_message = "Key Vault kv-ciam-prod has no secret ig-keystore (role ig-keystore)"
    }
    postcondition {
      condition     = contains(self.names, "pf-admin-password")
      error_message = "Key Vault kv-ciam-prod has no secret pf-admin-password (role pf-admin-password)"
    }
    postcondition {
      condition     = contains(self.names, "pf-captcha-secret")
      error_message = "Key Vault kv-ciam-prod has no secret pf-captcha-secret (role pf-captcha-secret)"
    }
    postcondition {
      condition     = contains(self.names, "pf-corp-ad-bind-password")
      error_message = "Key Vault kv-ciam-prod has no secret pf-corp-ad-bind-password (role pf-corp-ad-bind-password)"
    }
    postcondition {
      condition     = contains(self.names, "pf-ds-bind-password")
      error_message = "Key Vault kv-ciam-prod has no secret pf-ds-bind-password (role pf-ds-bind-password)"
    }
    postcondition {
      condition     = contains(self.names, "pf-grants-db-password")
      error_message = "Key Vault kv-ciam-prod has no secret pf-grants-db-password (role pf-grants-db-password)"
    }
    postcondition {
      condition     = contains(self.names, "pf-signing-key")
      error_message = "Key Vault kv-ciam-prod has no secret pf-signing-key (role pf-signing-key)"
    }
    postcondition {
      condition     = contains(self.names, "pf-smtp-password")
      error_message = "Key Vault kv-ciam-prod has no secret pf-smtp-password (role pf-smtp-password)"
    }
    postcondition {
      condition     = contains(self.names, "sso-tls-keystore")
      error_message = "Key Vault kv-ciam-prod has no secret sso-tls-keystore (role sso-tls-keystore)"
    }
  }
}
