# Generated by opsdir from env=prod,cloud=target,ou=environments,dc=ciam-ops
# Azure network kept by network-security for the CIAM platform: applied by them, not by the platform's pipeline
# Do not edit. Change the operations directory (under an approved change) and re-render.

data "azurerm_resource_group" "main" {
  name = "rg-ciam-prod"
}

data "azurerm_virtual_network" "main" {
  name                = "vnet-ciam-prod"
  resource_group_name = data.azurerm_resource_group.main.name
}

data "azurerm_subnet" "snet_aks" {
  name                 = "snet-aks"
  virtual_network_name = "vnet-ciam-prod"
  resource_group_name  = data.azurerm_resource_group.main.name
}

data "azurerm_subnet" "snet_am" {
  name                 = "snet-am"
  virtual_network_name = "vnet-ciam-prod"
  resource_group_name  = data.azurerm_resource_group.main.name
}

data "azurerm_subnet" "snet_db" {
  name                 = "snet-db"
  virtual_network_name = "vnet-ciam-prod"
  resource_group_name  = data.azurerm_resource_group.main.name
}

data "azurerm_subnet" "snet_ds" {
  name                 = "snet-ds"
  virtual_network_name = "vnet-ciam-prod"
  resource_group_name  = data.azurerm_resource_group.main.name
}

data "azurerm_subnet" "snet_edge" {
  name                 = "snet-appgw"
  virtual_network_name = "vnet-ciam-prod"
  resource_group_name  = data.azurerm_resource_group.main.name
}

data "azurerm_subnet" "snet_idm" {
  name                 = "snet-idm"
  virtual_network_name = "vnet-ciam-prod"
  resource_group_name  = data.azurerm_resource_group.main.name
}

data "azurerm_subnet" "snet_ig" {
  name                 = "snet-ig"
  virtual_network_name = "vnet-ciam-prod"
  resource_group_name  = data.azurerm_resource_group.main.name
}

data "azurerm_subnet" "snet_pf" {
  name                 = "snet-pf"
  virtual_network_name = "vnet-ciam-prod"
  resource_group_name  = data.azurerm_resource_group.main.name
}

data "azurerm_log_analytics_workspace" "ops_logs" {
  name                = "law-ciam-prod-ops"
  resource_group_name = "rg-ciam-prod"
}

resource "azurerm_route_table" "rt_private" {
  name                = "rt-ciam-prod-rt-private"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  # 0.0.0.0/0 nat: not a next hop in Azure (subnets reach it without a route); not rendered
  tags = {
    CostCenter  = "CC-1001"
    Environment = "target/prod"
    Owner       = "ciam-platform"
    Role        = "routes-private"
    ManagedBy   = "opsdir"
  }
}

resource "azurerm_subnet_route_table_association" "rt_private_snet_ds" {
  subnet_id      = data.azurerm_subnet.snet_ds.id
  route_table_id = azurerm_route_table.rt_private.id
}

resource "azurerm_subnet_route_table_association" "rt_private_snet_pf" {
  subnet_id      = data.azurerm_subnet.snet_pf.id
  route_table_id = azurerm_route_table.rt_private.id
}

resource "azurerm_subnet_route_table_association" "rt_private_snet_am" {
  subnet_id      = data.azurerm_subnet.snet_am.id
  route_table_id = azurerm_route_table.rt_private.id
}

resource "azurerm_subnet_route_table_association" "rt_private_snet_idm" {
  subnet_id      = data.azurerm_subnet.snet_idm.id
  route_table_id = azurerm_route_table.rt_private.id
}

resource "azurerm_subnet_route_table_association" "rt_private_snet_ig" {
  subnet_id      = data.azurerm_subnet.snet_ig.id
  route_table_id = azurerm_route_table.rt_private.id
}

resource "azurerm_network_watcher_flow_log" "flow_vnet" {
  name                 = "fl-ciam-prod-flow-vnet"
  network_watcher_name = var.network_watcher_name
  resource_group_name  = var.network_watcher_resource_group
  target_resource_id   = data.azurerm_virtual_network.main.id
  storage_account_id   = var.flow_logs_storage_account_id
  enabled              = true
  version              = 2
  retention_policy {
    enabled = true
    days    = 14
  }
  traffic_analytics {
    enabled               = true
    workspace_id          = data.azurerm_log_analytics_workspace.ops_logs.workspace_id
    workspace_region      = data.azurerm_log_analytics_workspace.ops_logs.location
    workspace_resource_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-ciam-prod/providers/Microsoft.OperationalInsights/workspaces/law-ciam-prod-ops"
    interval_in_minutes   = 10
  }
  tags = {
    CostCenter  = "CC-1001"
    Environment = "target/prod"
    Owner       = "ciam-platform"
    Role        = "flow-logs"
    ManagedBy   = "opsdir"
  }
}

resource "azurerm_firewall_policy_rule_collection_group" "egress_firewall_sites" {
  name               = "ciam-prod-sites"
  firewall_policy_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-hub-net/providers/Microsoft.Network/firewallPolicies/fwp-hub"
  priority           = 500
  application_rule_collection {
    name     = "ciam-prod-sites"
    priority = 500
    action   = "Allow"
    rule {
      name = "sites-80"
      protocols {
        type = "Http"
        port = 80
      }
      source_addresses  = ["10.60.0.0/16"]
      destination_fqdns = ["ocsp.example-ca.test", "crl.example-ca.test"]
    }
    rule {
      name = "sites-443"
      protocols {
        type = "Https"
        port = 443
      }
      source_addresses  = ["10.60.0.0/16"]
      destination_fqdns = ["metadata.skyline-air.test", "sso.harbor-mro.test"]
    }
  }
}
