#!/usr/bin/env bash
# Generated by opsdir for ds-1 in env=lab,cloud=hq,ou=environments,dc=ciam-ops
# PingDS 7.5.1; new or existing deployment.
# Secrets are resolved at run time from references; no secret value is stored in this file.
# The TLS keystore (binding role ds-tls-keystore) is materialized by the secrets agent before this runs.
set -euo pipefail
DEPLOYMENT_ID="$(clipasswordsdk GetPassword -p AppDescs.AppID='ciam-lab' -p Query='Safe=CIAM-Lab;Object=ds-deployment-id' -o Password)"
DEPLOYMENT_ID_PASSWORD="$(clipasswordsdk GetPassword -p AppDescs.AppID='ciam-lab' -p Query='Safe=CIAM-Lab;Object=ds-deployment-password' -o Password)"
ROOT_PASSWORD="$(clipasswordsdk GetPassword -p AppDescs.AppID='ciam-lab' -p Query='Safe=CIAM-Lab;Object=ds-root-password' -o Password)"

./setup \
  --serverId ds-1 \
  --deploymentId "$DEPLOYMENT_ID" \
  --deploymentIdPassword "$DEPLOYMENT_ID_PASSWORD" \
  --rootUserDn uid=admin \
  --rootUserPassword "$ROOT_PASSWORD" \
  --hostname ds-1.lab.example-aero.test \
  --adminConnectorPort 4444 \
  --ldapsPort 1636 \
  --httpsPort 8443 \
  --replicationPort 8989 \
  --bootstrapReplicationServer ds-1.lab.example-aero.test:8989 \
  --bootstrapReplicationServer ds-2.lab.example-aero.test:8989 \
  --profile ds-user-data \
  --set ds-user-data/baseDn:dc=partners,dc=example-aero,dc=test \
  --acceptLicense

# Then apply the environment-neutral configuration, in this order (indexes need the schema):
#   ldapmodify ... -f ../ldap/schema.ldif
#   ldapadd -c ... -f ../ldap/dit.ldif
#   dsconfig ... --batchFilePath ../ds/dsconfig.batch
#   ldapmodify ... -f ../ds/acis.ldif
