"""What the ForgeOps adapter renders for the workloads an environment runs with ForgeOps: per namespace, Helm values
for the identity-platform and ping-gateway charts and an overlay in ForgeOps' Kustomize layout, from the workloads and
their bindings (images never ForgeOps' public ones; UNBOUND where the record is silent), the DS AM uses when DS runs
on servers, and what the planner says about Secrets, service accounts, DS placement and public images."""
import pathlib
import re
import shutil
import subprocess

import pytest
import yaml

from opsdir.connectors.registry import services
from opsdir.core.contract import K8sIdentity, PlanContext
from opsdir.core.directory import one
from opsdir.core.environment import env_model
from opsdir.core.interchange.ldif import parse
from opsdir.domains.compute.naming import WORKLOADS, workload_dn
from opsdir_adapter_forgeops import release
from opsdir_adapter_forgeops.adapter import ADAPTER
from opsdir_adapter_forgeops.checks import check_forgeops
from opsdir_adapter_forgeops.components import image_of, placements
from opsdir_adapter_kubernetes.kits import split_image
from opsdir_adapter_forgeops.helm import helm_image
from opsdir_adapter_forgeops.listeners import listeners
from opsdir_adapter_forgeops.render import applies, render
from opsdir_adapter_kubernetes.adapter import ADAPTER as KUBERNETES
import mini_estate
from mini_estate import FAKE
from support import REGISTRY, build_directory

ALPHA = "env=prod,cloud=alpha,ou=environments,dc=ciam-ops"
ROOT = pathlib.Path(__file__).resolve().parents[3]
SOURCE = ROOT / "tools" / "forgeops" / release.VERSION
AM_IMAGE = "registry.example.test:5000/ciam/am:7.5.1@sha256:" + "a" * 64


def _workload(name, role, extra=""):
    return (f"dn: {workload_dn(name)}\nobjectClass: top\nobjectClass: ciamWorkload\ncn: {name}\n"
            f"ciamWorkloadKind: deployment\nciamTargetRole: {role}\nciamClusterRole: k8s\nciamNamespace: identity\n"
            f"ciamWorkloadRole: {name}-workload\n{extra}")


def _binding(cn, oc, role, extra=""):
    return (f"dn: cn={cn},ou=bindings,{ALPHA}\nobjectClass: top\nobjectClass: {oc}\ncn: {cn}\n"
            f"ciamBindingRole: {role}\n{extra}")


BASE = (
    f"dn: {WORKLOADS}\nobjectClass: top\nobjectClass: organizationalUnit\nou: workloads\n",
    _workload("am", "am", "ciamServiceAccount: identity\nciamIdentityRole: identity-am\n"
                          "ciamIngressHost: id.example.test\n"
                          "ciamWorkloadSecret: am-env-secrets/AM_ENCRYPTION_KEY <- am-encryption\n"),
    _workload("idm", "idm", "ciamServiceAccount: identity\n"),
    _workload("ig", "ig", "ciamIngressHost: gw.example.test\n"),
    _binding("k8s", "ciamCluster", "k8s", "ciamProviderRef: cluster-1\n"),
    _binding("am", "ciamWorkloadBinding", "am-workload",
             f"ciamContainerImage: openam={AM_IMAGE}\nciamContainerImage: amster=registry.example.test/ciam/amster:7.5.1\n"
             "ciamContainerImage: admin-ui=registry.example.test/ciam/admin-ui:7.5.1\n"
             "ciamWorkloadReplicas: 2\nciamCpuRequest: 500m\nciamMemoryLimit: 2Gi\n"),
    _binding("idm", "ciamWorkloadBinding", "idm-workload", "ciamContainerImage: main=registry.example.test/ciam/idm:7.5.1\n"),
    _binding("ig", "ciamWorkloadBinding", "ig-workload",
             "ciamContainerImage: ig=us-docker.pkg.dev/forgeops-public/images/ig:2026.3.1\n"),
    _binding("identity-am", "ciamIdentityBinding", "identity-am", "ciamProviderRef: am-identity\n"),
    _binding("ldap", "ciamServiceName", "ds-ldaps-service",
             "ciamFqdn: ldap.example.test\nciamTargetRole: ds\nciamPort: 1636\n"))
DS = (_workload("ds-idrepo", "ds"),
      _binding("ds-idrepo", "ciamWorkloadBinding", "ds-idrepo-workload",
               "ciamContainerImage: ds=registry.example.test/ciam/ds:8.0.1\nciamStorageSize: 100Gi\n"
               "ciamStorageClass: managed-csi-premium\n"))
CLOUD = FAKE._replace(workload_identity=lambda m, b: K8sIdentity(
    (("cloud.example.test/identity", one(b, "ciamProviderRef")),), (("cloud.example.test/use", "true"),)))
INSTALLED = (CLOUD, KUBERNETES, ADAPTER)


def model(*extra):
    d = build_directory(REGISTRY, tuple(parse("\n".join((mini_estate.LDIF, *BASE, *extra)))))
    return env_model(d, "alpha/prod")


def _doc(files, path):
    text = files[path]
    assert text.startswith("# Generated by opsdir from env=prod,cloud=alpha")
    return yaml.safe_load(text)


def test_it_renders_only_where_forgeops_runs_workloads():
    assert applies(model())
    assert not applies(env_model(build_directory(REGISTRY, tuple(parse(mini_estate.LDIF))), "alpha/prod"))


def test_components_come_with_the_workloads_they_serve():
    (p,) = placements(model())
    assert p.namespace == "identity" and [c for c, _ in p.placed] == ["am", "idm", "ig"]
    assert p.on == ("am", "amster", "idm", "keystore-create", "admin-ui", "end-user-ui", "login-ui", "ig")
    (p,) = placements(model(*DS))
    assert "ds-idrepo" in p.on and "ds-set-passwords" in p.on and "ds-cts" not in p.on


def test_images_come_from_the_record_never_forgeops_public_ones():
    (p,) = placements(model())
    m = model()
    assert image_of(m, p, "am") == AM_IMAGE and image_of(m, p, "keystore-create") == AM_IMAGE
    assert image_of(m, p, "idm") == "registry.example.test/ciam/idm:7.5.1"     # its workload's only image
    assert image_of(m, p, "admin-ui") == "registry.example.test/ciam/admin-ui:7.5.1"
    assert image_of(m, p, "login-ui") == "UNBOUND:forgeops-login-ui-image"
    assert split_image(AM_IMAGE) == ("registry.example.test:5000/ciam/am", "7.5.1", "sha256:" + "a" * 64)
    assert split_image("UNBOUND:forgeops-x-image") == ("UNBOUND", "forgeops-x-image", None)
    assert helm_image(AM_IMAGE) == {"repository": "registry.example.test:5000/ciam/am:7.5.1@sha256", "tag": "a" * 64}
    assert helm_image("ds") == {"repository": "ds", "tag": "latest"}


def test_identity_platform_values():
    files = render(model(), services(INSTALLED), ("helm",))
    assert sorted(files) == ["forgeops/helm/identity/identity-platform-values.yaml",
                             "forgeops/helm/identity/ping-gateway-values.yaml"]
    v = _doc(files, "forgeops/helm/identity/identity-platform-values.yaml")
    assert v["serviceAccount"] == {"create": False, "name": "identity"}
    assert v["platform"] == {
        "disable_secret_agent_config": True, "secrets_enabled": True, "base_generate": True, "secrets": {},
        "ds_certs": {"enabled": False},                     # no DS in the cluster: the servers' CA comes from the record
        "ingress": {"hosts": ["id.example.test"]},
        "external_ds": {"enabled": True, "cts_hosts": ["ldap.example.test:1636"],
                        "idrepo_hosts": ["ldap.example.test:1636"]}}
    assert v["am"] == {"enabled": True, "image": helm_image(AM_IMAGE), "replicaCount": 2,
                       "resources": {"requests": {"cpu": "500m"}, "limits": {"memory": "2Gi"}},
                       "podLabels": {"opsdir.io/role": "am", "cloud.example.test/use": "true"}}
    assert v["idm"]["podLabels"] == {"opsdir.io/role": "idm"}
    assert v["idm"]["env"] == [{"name": "OPENIDM_REPO_HOST", "value": "ldap.example.test"},
                               {"name": "OPENIDM_REPO_PORT", "value": "1636"},
                               {"name": "USERSTORE_HOST", "value": "ldap.example.test"},
                               {"name": "USERSTORE_PORT", "value": "1636"}]   # IDM's repository on the DS servers
    assert v["keystore_create"] == {"enabled": True, "initImage": helm_image(AM_IMAGE), "force": True}
    assert v["login_ui"]["image"] == {"repository": "UNBOUND", "tag": "forgeops-login-ui-image"}
    assert [v[k] for k in ("ds_idrepo", "ds_cts", "ds_set_passwords")] == [{"enabled": False}] * 3
    assert v["ssh_keygen"] == {"enabled": True}


def test_ds_in_the_cluster_takes_its_storage_from_the_record():
    v = _doc(render(model(*DS), services(INSTALLED), ("helm",)), "forgeops/helm/identity/identity-platform-values.yaml")
    assert v["ds_idrepo"]["volumeClaimSpec"] == {"storageClassName": "managed-csi-premium",
                                                 "resources": {"requests": {"storage": "100Gi"}}}
    assert v["platform"]["external_ds"] == {"enabled": True, "cts_hosts": ["ldap.example.test:1636"],
                                            "idrepo_hosts": ["ds-idrepo-0.ds-idrepo:1636"]}
    assert "ds_certs" not in v["platform"] and "env" not in v["idm"]       # IDM's repository is in the cluster


def test_ping_gateway_values():
    v = _doc(render(model(), services(INSTALLED), ("helm",)), "forgeops/helm/identity/ping-gateway-values.yaml")
    assert v["serviceAccount"] == {"create": False, "name": "ig"}
    assert v["platform"] == {"ingress": {"hosts": ["gw.example.test"]}}
    assert v["ig"]["image"] == {"repository": "us-docker.pkg.dev/forgeops-public/images/ig", "tag": "2026.3.1"}


def test_the_kustomize_overlay_in_forgeops_layout():
    files = render(model(), services(INSTALLED), ("kustomize",))
    root = "forgeops/kustomize/overlay/identity"
    top = _doc(files, f"{root}/kustomization.yaml")
    assert top["namespace"] == "identity" and top["resources"] == [
        "./base", "./am", "./amster", "./idm", "./keystore-create", "./admin-ui", "./end-user-ui", "./login-ui", "./ig"]
    assert top["images"] == [{"name": "am-custom", "newName": "busybox", "newTag": "musl"},
                             {"name": "idm-custom", "newName": "busybox", "newTag": "musl"},
                             {"name": "kubectl", "newName": "us-docker.pkg.dev/forgeops-public/images/kubectl",
                              "newTag": "1.36.1"}]
    assert _doc(files, f"{root}/base/platform-config.yaml")["data"] == {
        "FQDN": "id.example.test", "AM_SERVER_FQDN": "id.example.test",
        "AM_STORES_CTS_SERVERS": "ldap.example.test:1636", "AM_STORES_USER_SERVERS": "ldap.example.test:1636"}
    am = _doc(files, f"{root}/am/kustomization.yaml")
    assert am["resources"] == ["../../../base/am/secret-generator"]
    assert am["images"] == [{"name": "am", "newName": "registry.example.test:5000/ciam/am", "newTag": "7.5.1",
                             "digest": "sha256:" + "a" * 64}]
    assert am["labels"] == [{"pairs": {"opsdir.io/role": "am", "cloud.example.test/use": "true"},
                             "includeSelectors": False, "includeTemplates": True}]
    workload, ingress = am["patches"]
    assert yaml.safe_load(workload["patch"])["spec"] == {
        "replicas": 2, "template": {"spec": {"serviceAccountName": "identity", "containers": [
            {"name": "openam", "resources": {"requests": {"cpu": "500m"}, "limits": {"memory": "2Gi"}}}]}}}
    idm, _ = _doc(files, f"{root}/idm/kustomization.yaml")["patches"]
    (container,) = yaml.safe_load(idm["patch"])["spec"]["template"]["spec"]["containers"]
    assert container["name"] == "openidm" and container["env"][0] == {"name": "OPENIDM_REPO_HOST",
                                                                      "value": "ldap.example.test"}
    assert yaml.safe_load(ingress["patch"])[0] == {"op": "replace", "path": "/spec/rules/0/host",
                                                   "value": "id.example.test"}
    assert yaml.safe_load(_doc(files, f"{root}/ig/kustomization.yaml")["patches"][-1]["patch"])[1]["value"] == \
        ["gw.example.test"]


def test_its_pods_ports_and_the_companions_role_labels():
    assert {(x.server_role, x.port, x.on) for x in listeners(model())} == {
        ("am", 8080, "kubernetes"), ("idm", 8080, "kubernetes"), ("ig", 8080, "kubernetes")}
    assert {x.port for x in listeners(model(*DS)) if x.server_role == "ds"} == {1389, 1636, 4444, 8989}
    files = render(model(*DS), services(INSTALLED), ("helm", "kustomize"))
    v = _doc(files, "forgeops/helm/identity/identity-platform-values.yaml")
    assert v["admin_ui"]["podLabels"] == {"opsdir.io/role": "am"}                  # served through the ingress
    assert v["ds_set_passwords"]["podLabels"] == {"opsdir.io/role": "ds"}         # reaches DS as its peers do
    assert "podLabels" not in v["amster"] and "podLabels" not in v["keystore_create"]      # only call out
    ui = _doc(files, "forgeops/kustomize/overlay/identity/login-ui/kustomization.yaml")
    assert ui["labels"][0]["pairs"] == {"opsdir.io/role": "am"}


def _context(m):
    return PlanContext(m.d, m, m, None, None, {}, {}, ())


def test_the_planner_names_what_forgeops_still_needs():
    actions = [a[1] for a in check_forgeops(_context(model(_workload("ds-main", "ds"),
                                                           _binding("ds-main", "ciamWorkloadBinding",
                                                                    "ds-main-workload")))).actions]
    (env,) = [a for a in actions if "Secret `am-env-secrets`" in a]
    assert "AM_SESSION_STATELESS_SIGNING_KEY" in env and "AM_ENCRYPTION_KEY" not in env    # recorded by am
    assert not any("`keystore`" in a for a in actions)                         # the keystore-create job makes it
    assert any("Secret `ds-ssl-keypair` key(s) ca.crt" in a for a in actions)    # the DS servers' CA
    assert any("Secret `amster`" in a and "under helm the ssh-keygen job makes it" in a for a in actions)
    assert any("public image `us-docker.pkg.dev/forgeops-public/images/ig:2026.3.1`" in a for a in actions)
    assert any("Workload `ds-main` runs DS" in a for a in actions)
    assert not any("service account" in a for a in actions)


def test_the_planner_names_a_ds_layout_split_between_the_cluster_and_servers():
    actions = [a[1] for a in check_forgeops(_context(model(*DS))).actions]
    (split,) = [a for a in actions if "on servers" in a]
    assert split.startswith("ForgeOps in alpha/prod (namespace `identity`) runs `ds-idrepo` in the cluster and "
                            "`ds-cts` on servers")
    cts = (_workload("ds-cts", "ds"), _binding("ds-cts", "ciamWorkloadBinding", "ds-cts-workload"))
    assert not any("on servers:" in a for a in [a[1] for a in check_forgeops(_context(model(*DS, *cts))).actions])
    assert not any("on servers:" in a for a in [a[1] for a in check_forgeops(_context(model())).actions])


def test_the_planner_names_a_second_service_account():
    text = "\n".join((mini_estate.LDIF, *(b.replace("ciamServiceAccount: identity\n", "") if "cn: idm\n" in b else b
                                          for b in BASE)))
    m = env_model(build_directory(REGISTRY, tuple(parse(text))), "alpha/prod")
    actions = [a[1] for a in check_forgeops(_context(m)).actions]
    assert any("one service account" in a and "(identity, idm)" in a for a in actions)


def test_the_fetch_script_pins_the_release():
    script = (ROOT / "packages" / "opsdir-adapter-forgeops" / "scripts" / "fetch-forgeops.sh").read_text()
    pins = dict(re.findall(r"^(VERSION|COMMIT|SHA256)=(\S+)$", script, re.M))
    assert pins == {"VERSION": release.VERSION, "COMMIT": release.COMMIT, "SHA256": release.SOURCE_SHA256}


@pytest.mark.kubernetes
@pytest.mark.skipif(not (ROOT / "tools" / "bin" / "kubeconform").exists() or not (SOURCE / ".complete").exists(),
                    reason="no tools (opsdir/scripts/fetch-tools.sh) or ForgeOps source (fetch-forgeops.sh)")
@pytest.mark.parametrize("extra", [(), DS], ids=["ds-on-servers", "ds-in-the-cluster"])
def test_the_render_builds_and_is_valid_kubernetes(tmp_path, extra):
    files = render(model(*extra), services(INSTALLED), ("helm", "kustomize"))
    shutil.copytree(SOURCE / "kustomize" / "base", tmp_path / "kustomize" / "base")
    for path, text in files.items():
        target = tmp_path / path.replace("forgeops/", "", 1)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text)
    helm = [x for chart in ("identity-platform", "ping-gateway")
            for x in ("--helm", str(SOURCE / "charts" / chart), str(tmp_path / "helm" / "identity" / f"{chart}-values.yaml"))]
    done = subprocess.run([str(ROOT / "opsdir" / "scripts" / "validate-kubernetes.sh"), *helm,
                           str(tmp_path / "kustomize" / "overlay")], capture_output=True, text=True)
    assert done.returncode == 0, done.stdout + done.stderr
    built = subprocess.run([str(ROOT / "tools" / "bin" / "kustomize"), "build",
                            str(tmp_path / "kustomize" / "overlay" / "identity")], capture_output=True, text=True)
    images = set(re.findall(r"^\s+image: (\S+)$", built.stdout, re.M))
    assert images and not [i for i in images if not re.search(r"[:@]", i)], images    # no base placeholder left
