"""The user directory's tree as standard LDIF: its naming contexts (the declared backends' base DNs) and every
container the record refers to in them (any `extdn` value, such as an ACI target, a subtree consumers read, the
parent of a bind DN, a provisioning base). Containers are the standard entries their RDN type names:
dc → domain, ou → organizationalUnit, o → organization. Environment-neutral; no user data.
"""
from types import MappingProxyType

from opsdir.core.directory import norm_dn, one, subtree, value_type, within
from opsdir.core.interchange.ldif import write_entry
from opsdir.domains.directory.naming import DECLARED

CONTAINER_CLASSES = MappingProxyType({"dc": "domain", "ou": "organizationalUnit", "o": "organization"})


def naming_contexts(d):
    """Base DNs of the declared backends, in DN order of the backends."""
    return tuple(dict.fromkeys(one(b, "ciamBaseDn") for b in subtree(d, f"ou=backends,{DECLARED}", "ciamBackend")))


def _rdn(dn):
    attr, value = dn.split(",", 1)[0].split("=", 1)
    return attr.strip().lower(), value.strip()


def _lineage(dn):
    """The DN and each of its ancestors, nearest first."""
    parts = dn.split(",")
    return tuple(",".join(parts[i:]).strip() for i in range(len(parts)))


def _referenced(d):
    return (v for e in d.entries.values() for name, vals in e.attrs.items() if value_type(d, name) == "extdn"
            for v in vals)


def _containers_up_to(dn, nc):
    """The containers from the naming context down to dn (dn's own entry only if it is a container), or () when a
    non-container lies in between (nothing below it can be created from the record)."""
    chain = tuple(x for x in _lineage(dn) if within(x, nc) and norm_dn(x) != norm_dn(nc))
    if not chain:
        return ()
    inner = chain if _rdn(chain[0])[0] in CONTAINER_CLASSES else chain[1:]
    return inner if all(_rdn(x)[0] in CONTAINER_CLASSES for x in inner) else ()


def tree(d):
    """Every entry to create, parents first: each naming context, then the containers the record refers to."""
    ncs = naming_contexts(d)
    found = {norm_dn(x): x for v in _referenced(d) for nc in ncs if within(v, nc) for x in _containers_up_to(v, nc)}
    return (*ncs, *sorted(found.values(), key=lambda x: (x.count(","), norm_dn(x))))


def _entry(dn):
    attr, value = _rdn(dn)
    cls = CONTAINER_CLASSES.get(attr)
    return (f"# {dn}: RDN type {attr} has no standard container class; create it by hand\n" if not cls
            else write_entry(dn, ("top", cls), {attr: (value,)}))


def dit_ldif(d):
    head = ("# User-directory tree: its naming contexts and the containers the record refers to. Generated by opsdir.",
            "# Environment-neutral; no user data. Apply with ldapadd -c (entries that exist are skipped).", "")
    return "\n".join((*head, *(_entry(dn) for dn in tree(d))))
