"""The user directory's schema as standard LDIF: the attribute types and object classes the record defines (the
standard ones every compliant server already has), added to the subschema subentry with one modify.

Environment-neutral. Written as RFC 4512 definitions in an RFC 2849 modify of the subschema subentry, which
servers of the DS lineage and 389 Directory Server accept online at cn=schema; a server that keeps its schema
elsewhere (e.g. under cn=config) has its own adapter.
"""
from opsdir.core.directory import follow_all, one, rdn_value
from opsdir.core.interchange.ldif import LdifRecord, write_record
from opsdir.core.interchange.rfc4512 import attribute_type_definition, object_class_definition
from opsdir.domains.directory.naming import USER_SCHEMA
from opsdir.domains.directory.user_schema import defined_attributes, defined_classes

SUBSCHEMA_DN = "cn=schema"
ORIGIN = "opsdir"


def attribute_definition(e):
    """RFC 4512 attributeTypes value for a recorded, non-standard user-directory attribute."""
    return attribute_type_definition(
        one(e, "ciamLdapOid"), one(e, "ciamLdapName"), one(e, "ciamPurpose"), one(e, "ciamLdapEquality"),
        one(e, "ciamLdapSyntax"), one(e, "ciamLdapSingleValue") == "TRUE", (("X-ORIGIN", ORIGIN),),
        ordering=one(e, "ciamLdapOrdering"), substr=one(e, "ciamLdapSubstring"))


def _names(d, e, attr):
    return tuple(one(a, "ciamLdapName") for a in follow_all(d, e, attr))


def class_definition(d, e):
    """RFC 4512 objectClasses value for a recorded, non-standard user-directory object class."""
    return object_class_definition(
        one(e, "ciamLdapOid"), one(e, "ciamLdapName"), one(e, "ciamPurpose"), one(e, "ciamLdapSuperior") or "top",
        one(e, "ciamLdapClassKind").upper(), _names(d, e, "ciamLdapMust"), _names(d, e, "ciamLdapMay"),
        (("X-ORIGIN", ORIGIN),))


def _depth(e, by_name):
    """How many recorded classes lie above this one (so superclasses are added first)."""
    sup = by_name.get((one(e, "ciamLdapSuperior") or "").lower())
    return 1 + _depth(sup, by_name) if sup else 0


def superclasses_first(classes):
    by_name = {one(c, "ciamLdapName").lower(): c for c in classes}
    return tuple(sorted(classes, key=lambda c: (_depth(c, by_name), rdn_value(c))))


def schema_record(d, subschema_dn=SUBSCHEMA_DN):
    """The modify record adding every defined attribute type and object class, or None when there are none."""
    mods = tuple((op, attr, vals) for op, attr, vals in (
        ("add", "attributeTypes", tuple(attribute_definition(a) for a in defined_attributes(d))),
        ("add", "objectClasses", tuple(class_definition(d, c) for c in superclasses_first(defined_classes(d)))))
        if vals)
    return LdifRecord(subschema_dn, "modify", {}, mods) if mods else None


def schema_ldif(d, subschema_dn=SUBSCHEMA_DN):
    head = (f"# User-directory schema. Generated by opsdir from {USER_SCHEMA}.",
            "# Only definitions the standards do not provide; every compliant server has the standard ones.",
            "# Environment-neutral. Apply with ldapmodify under change control.")
    record = schema_record(d, subschema_dn)
    return "\n".join((*head, "", *((write_record(record),) if record else ())))
