"""Compose the Example Aero estate from every domain's fixture data (pure: builds text, writes nothing)."""
import json

from opsdir.core.interchange.ldif import write_entry

from . import (access, access_logs, base, cloud, config, custom, directory, edge, estate, federation, governance,
               infrastructure, messaging, observability, pki, recovery, user_data)
from .expected import expected_findings

HEADER = "# Generated by scripts/gen-synthetic.py. Synthetic, fictional data. Do not edit by hand.\n\n"
GENERATED = ("ds-config", "ds-access-logs", "cloud", "ds-data", "regions", "quotas")    # the folders of exports/ exports() writes


def specs():
    """Every entry spec, in the order entries appear within their data files."""
    return (*base.entries(), *custom.definitions(), *governance.owners(), *estate.entries(), *governance.changes(),
            *directory.user_attributes(), *directory.user_classes(), *directory.declared_config(),
            *infrastructure.environments(), *directory.consumers(), *directory.acis(), *governance.runbooks(), *pki.certificates(), *pki.credentials(),
            *federation.identity_services(), *federation.integrations(), *messaging.entries(),
            *observability.entries(), *access.entries(), *edge.entries(),
            *infrastructure.external_allowlists(), *governance.incidents(), *governance.restore_tests(),
            *recovery.entries(), *custom.feature_flags(), *config.config_files(), *config.bundles())


def data_files(all_specs):
    """{file name: LDIF text}, files in order of first use, entries in spec order."""
    names = dict.fromkeys(s.file for s in all_specs)
    return {f"{name}.ldif": HEADER + "\n".join(write_entry(s.dn, s.classes, s.attrs) for s in all_specs
                                               if s.file == name)
            for name in names}


def exports():
    """{path under exports/: text} of the product exports built from the estate (the directory servers' config/
    directories and access logs, what the clouds report the environments run, each provider's region list and the
    quotas it grants, the production directory's data as ldapsearch prints it); a path ending .gz is the text the file holds compressed."""
    return {**{f"ds-config/{path}": HEADER + text for path, text in directory.server_exports().items()},
            **{f"ds-access-logs/{path}": text for path, text in access_logs.access_logs().items()},
            **{f"cloud/{path}": text for path, text in cloud.cloud_exports().items()},
            **estate.region_exports(), **estate.quota_exports(),
            **user_data.user_data()}


def build():
    """(entry count, {relative path: text}) for the whole estate, including expected-findings.json."""
    all_specs = specs()
    return len(all_specs), {**data_files(all_specs),
                            "expected-findings.json": json.dumps(expected_findings(), indent=2) + "\n"}
