"""What the tools should find: every problem planted in the estate, and how the migration planner reports it.
The demo checks the planner against this list, so "NOT READY" reads as "found what was planted", not as a failure.
"""

EXPECTED = {
    "blockers": [
        ("B1", "Contract", "`ds-ldaps-service` changes name", "the target environment binds a new LDAPS name (landing-zone DNS default)", "CHG-2003"),
        ("B2", "Binding", "Role `backup-target`", "the target environment has no backup target", None),
        ("B3", "Binding", "Consumer `legacy-rptuser`", "no target firewall rule for the unowned legacy account", None),
        ("B4", "Binding", "Consumer `mro-batch-export`", "no target firewall rule for the MRO export", "CHG-2001"),
        ("B5", "Consumer", "Consumer `legacy-rptuser`", "legacy account: unknown status, no owner, no TLS", None),
        ("B6", "Consumer", "Consumer `mro-batch-export`", "MRO export only 'identified', not tested", None),
        ("B7", "Consumer", "Consumer `supplier-portal-svc`", "supplier portal only 'contacted', not tested", None),
        ("B8", "Key", "`disk-encryption` must be kept in an HSM", "the target's disk key is software-protected", None),
        ("B9", "IDM", "Connector `hrdb` has withheld credentials but no credential role",
         "imported HR database connector names no secret", "CHG-2005"),
        ("B10", "IDM", "Connector `ldap` has withheld credentials but no credential role",
         "imported directory connector names no secret", "CHG-2005"),
        ("B11", "PingFederate", "Data store `grant-store` has withheld credentials but no credential role",
         "imported grant database store names no secret", "CHG-2005"),
        ("B12", "PingFederate", "Data store `user-directory` has withheld credentials but no credential role",
         "imported directory data store names no secret", "CHG-2005"),
        ("B13", "Binding", "Role `pf-cluster-discovery`",
         "the target binds no PingFederate cluster discovery: the nodes' tcp.xml uses S3 on AWS", None),
    ],
    "actions": [
        ("A1", "Certificate", "`skyline-air-idp-signing`", "partner cert expires 2026-11-02", None),
        ("A2", "Certificate", "`supplier-portal-sp-signing`", "SP cert expires 2026-11-30", None),
        ("A3", "Certificate", "`ds-ldaps-2026`", "LDAPS cert expires 2026-12-20", None),
        ("A4", "Certificate", "`sso-tls-2026`", "SSO TLS cert expires within 30 days after cutover", None),
        ("A5", "Allowlist", "`skyline-air-ingress`", "partner allowlist pins our old egress IP", None),
        ("A6", "Allowlist", "`mro-dc-egress-to-ldaps`", "consumer firewall pins our old LDAPS IP", None),
        ("A7", "Allowlist", "`supplier-portal-egress-sg`", "consumer security group pins our old LDAPS IP", None),
        ("A8", "Drift", "ds-2: missing on server: `cn=mail", "mail index missing on ds-2 (INC-2231)", None),
        ("A9", "Drift", "ds-3: not declared (unrecorded change): `cn=description", "unrecorded index on ds-3", None),
        ("A10", "Drift", "ds-3: differs: `cn=customers", "lockout threshold changed on ds-3", None),
        ("A11", "Access", "ACI `aci-legacy-all`", "ACI with no owner or justification", None),
        ("A12", "Key", "Copy `pf-signing-key`", "signing key must be carried over, not recorded as carried over", None),
        ("A13", "Key", "`pf-admin-password` loses automatic rotation", "target secret has no rotation function", None),
        ("A14", "Key", "`disk-encryption` loses automatic rotation and replicas",
         "target disk key neither rotates nor replicates", None),
        ("A15", "IDM", "Connector `hrdb` reaches a fixed host", "HR database reached at the same host everywhere", None),
        ("A16", "Gateway", "Route `partner-portal` sends requests to a fixed backend",
         "the partner portal application is reached at the same host everywhere", None),
        ("A17", "Hard-coded", "`opt/scripts/nightly-export.sh` on ds-2 holds source/prod values",
         "the MRO export script names ds-1 by hostname and address", None),
        ("A18", "Hard-coded", "`etc/hosts` on pf-engine-1 holds source/prod values",
         "PingFederate's engine pins ds-1's address in /etc/hosts", None),
        ("A19", "Hard-coded", "`apps/customer-portal/application.properties` holds source/prod values",
         "the portal names the LDAPS service, which the target renames (B1)", "CHG-2003"),
        ("A20", "PingFederate", "Data store `grant-store` reaches a fixed host",
         "the grant database is reached at the same host everywhere", None),
        ("A21", "PingFederate", "Data store `user-directory` reaches a fixed host",
         "PingFederate's LDAP data store lists ds-1 by hostname next to the LDAPS service", None),
    ],
}

KEYS = ("id", "area", "match", "planted", "cleared_by")


def expected_findings():
    """The data/expected-findings.json document."""
    return {"_comment": "Generated by scripts/gen-synthetic.py: the problems planted in the synthetic data.",
            **{kind: [dict(zip(KEYS, row)) for row in rows] for kind, rows in EXPECTED.items()}}
