"""What the tools should find: every problem planted in the estate, and how the migration planner reports it.
The demo checks the planner against this list, so "NOT READY" reads as "found what was planted", not as a failure.
"""
from types import MappingProxyType


EXPECTED = MappingProxyType({
    "blockers": [
        ("B1", "Contract", "`ds-ldaps-service` changes name", "the target environment binds a new LDAPS name (landing-zone DNS default)", "CHG-2003"),
        ("B2", "Binding", "Role `backup-target`", "the target environment has no backup target", None),
        ("B3", "Binding", "Consumer `legacy-rptuser`", "no target firewall rule for the unowned legacy account", None),
        ("B4", "Binding", "Consumer `mro-batch-export`", "no target firewall rule for the MRO export", "CHG-2001"),
        ("B5", "Consumer", "Consumer `legacy-rptuser`", "legacy account: unknown status, no owner, no TLS", None),
        ("B6", "Consumer", "Consumer `mro-batch-export`", "MRO export only 'identified', not tested", None),
        ("B7", "Consumer", "Consumer `supplier-portal-svc`", "supplier portal only 'contacted', not tested", None),
        ("B8", "Key", "`disk-encryption` must be kept in an HSM", "the target's disk key is software-protected", None),
        ("B9", "IDM", "Connector `hrdb` has withheld credentials but no credential role",
         "imported HR database connector names no secret", "CHG-2005"),
        ("B10", "IDM", "Connector `ldap` has withheld credentials but no credential role",
         "imported directory connector names no secret", "CHG-2005"),
        ("B11", "PingFederate", "Data store `grant-store` has withheld credentials but no credential role",
         "imported grant database store names no secret", "CHG-2005"),
        ("B12", "PingFederate", "Data store `user-directory` has withheld credentials but no credential role",
         "imported directory data store names no secret", "CHG-2005"),
        ("B13", "Binding", "Role `pf-cluster-discovery`",
         "the target binds no PingFederate cluster discovery: the nodes' tcp.xml uses S3 on AWS", None),
        ("B14", "PingFederate", "Notification publisher `smtp` has withheld credentials but no credential role",
         "imported SMTP publisher names no secret", "CHG-2005"),
        ("B15", "PingFederate", "CAPTCHA provider `recaptcha` has withheld credentials but no credential role",
         "imported CAPTCHA provider names no secret", "CHG-2005"),
        ("B16", "Mail", "Sender `noreply@example-aero.test`: target/prod's sending identity for example-aero.test isn't "
         "DKIM-verified", "the target's Communication Services domain isn't DKIM-verified yet: reset mail lands in spam",
         None),
        ("B17", "Binding", "Role `audit-events` is bound in source/prod but not in target/prod",
         "no bus carries the identity audit stream in the target", None),
        ("B18", "Binding", "Role `alarm-disk-free` is bound in source/prod but not in target/prod",
         "the target doesn't run the disk-space alarm CloudWatch runs (nobody described it: A36)", None),
        ("B19", "Logs", "Log route `audit-logs` must keep logs 400 days; target/prod's `audit-logs` keeps them 90",
         "the target's audit workspace keeps logs 90 days, short of the 400-day obligation", None),
        ("B20", "Binding", "Role `identity-idm` is bound in source/prod but not in target/prod",
         "the target doesn't bind the IDM role the source runs (nobody records what acts as it: A39)", None),
        ("B21", "Binding", "Role `forwarder-corp.example-aero.internal` is bound in source/prod but not in target/prod",
         "the source forwards the AD domain to the domain controllers; nothing in the target does", "CHG-2015"),
        ("B22", "Binding", "Role `acl-ds` is bound in source/prod but not in target/prod",
         "the source's network ACL on the directory subnet has no counterpart in the target (Azure has none: its "
         "NSGs do that work); decide, and record why", None),
        ("B23", "PingFederate", "Data store `corp-directory` has withheld credentials but no credential role",
         "imported corporate directory store names no secret", "CHG-2005"),
    ],
    "actions": [
        ("A1", "Certificate", "`skyline-air-idp-signing`", "partner cert expires 2026-11-02", None),
        ("A2", "Certificate", "`supplier-portal-sp-signing`", "SP cert expires 2026-11-30", None),
        ("A3", "Certificate", "`ds-ldaps-2026`", "LDAPS cert expires 2026-12-20", None),
        ("A4", "Certificate", "`sso-tls-2026`", "SSO TLS cert expires within 30 days after cutover", None),
        ("A5", "Allowlist", "`skyline-air-ingress`", "partner allowlist pins our old egress IP", None),
        ("A6", "Allowlist", "`mro-dc-egress-to-ldaps`", "consumer firewall pins our old LDAPS IP", None),
        ("A7", "Allowlist", "`supplier-portal-egress-sg`", "consumer security group pins our old LDAPS IP", None),
        ("A8", "Drift", "ds-2: missing on server: `cn=mail", "mail index missing on ds-2 (INC-2231)", None),
        ("A9", "Drift", "ds-3: not declared (unrecorded change): `cn=description", "unrecorded index on ds-3", None),
        ("A10", "Drift", "ds-3: differs: `cn=customers", "lockout threshold changed on ds-3", None),
        ("A11", "Access", "ACI `aci-legacy-all`", "ACI with no owner or justification", None),
        ("A12", "Key", "Copy `pf-signing-key`", "signing key must be carried over, not recorded as carried over", None),
        ("A13", "Key", "`pf-admin-password` loses automatic rotation", "target secret has no rotation function", None),
        ("A14", "Key", "`disk-encryption` loses automatic rotation and replicas",
         "target disk key neither rotates nor replicates", None),
        ("A15", "IDM", "Connector `hrdb` reaches a fixed host", "HR database reached at the same host everywhere", None),
        ("A16", "Gateway", "Route `partner-portal` sends requests to a fixed backend",
         "the partner portal application is reached at the same host everywhere", None),
        ("A17", "Hard-coded", "`opt/scripts/nightly-export.sh` on ds-2 holds source/prod values",
         "the MRO export script names ds-1 by hostname and address", None),
        ("A18", "Hard-coded", "`etc/hosts` on pf-engine-1 holds source/prod values",
         "PingFederate's engine pins ds-1's address in /etc/hosts", None),
        ("A19", "Hard-coded", "`apps/customer-portal/application.properties` holds source/prod values",
         "the portal names the LDAPS service, which the target renames (B1)", "CHG-2003"),
        ("A20", "PingFederate", "Data store `grant-store` reaches a fixed host",
         "the grant database is reached at the same host everywhere", None),
        ("A21", "PingFederate", "Data store `user-directory` reaches a fixed host",
         "PingFederate's LDAP data store lists ds-1 by hostname next to the LDAPS service", None),
        ("A22", "Job", "Job `ds-nightly-export` has no owner", "the MRO nightly export on ds-2's cron nobody owns",
         "CHG-2011"),
        ("A23", "Job", "Job `github-actions-ciam-ops-directory-backup` has no owner",
         "the nightly directory backup pipeline nobody owns", "CHG-2011"),
        ("A24", "Job", "Job `pf-engine-pf-audit-ship` has no owner",
         "the PingFederate engines' audit shipping timer nobody owns", "CHG-2011"),
        ("A25", "Host", "Servers of role `ds` pin 1 name(s) in /etc/hosts",
         "ds-2 pins the legacy reports host to its address", None),
        ("A26", "Host", "Servers of role `pf-engine` trust 1 certificate(s)",
         "the engines' truststore adds the corporate root CA, which the record lacks", "CHG-2013"),
        ("A27", "Host", "Servers of role `pf-admin` trust 1 certificate(s)",
         "the admin node's truststore adds it too", "CHG-2013"),
        ("A28", "Compute", "Compute group `vmss-pf-engine` (role `pf-engine`) in target/prod spans 1 zone(s)",
         "the target's engine scale set sits in one zone; the source spreads them over two", None),
        ("A29", "Mail", "Sender `noreply@example-aero.test`: target/prod's DMARC policy for example-aero.test is "
         "quarantine", "the target's DMARC policy is weaker than the source's reject", None),
        ("A30", "Data", "24 password value(s) in source/prod are hashed with SSHA512",
         "customers migrated from the old portal, and the legacy reports account, still hold salted SHA-512 hashes; "
         "every declared policy stores PBKDF2", None),
        ("A31", "Data", "attribute(s) in source/prod's user data have no ou=user-schema record",
         "a CRM integration nobody recorded writes crmContactId on suppliers; cn has no PII class either", None),
        ("A32", "Data", "1 member DN(s) of source/prod's groups name entries that don't exist",
         "the supplier approvers group still lists a supplier deleted last year", None),
        ("A33", "Data", "37 entries in source/prod hold challenge questions (KBA)",
         "customers registered before 2022 still hold challenge answers", None),
        ("A34", "Alert", "Alert rule `login-failures` names no runbook",
         "the login-failures rule pages without saying what to do", None),
        ("A35", "Logs", "Log route `audit-logs` is under legal hold",
         "the audit logs are under legal hold: the source's log group must outlive decommissioning", None),
        ("A36", "Monitoring", "source/prod runs alarm `ds-disk-free`",
         "CloudWatch runs a disk-space alarm no recorded rule describes", None),
        ("A37", "Access", "Principal `break-glass-root`: break-glass: last tested 2025-11-03",
         "the break-glass procedure was last exercised over 180 days ago", None),
        ("A38", "Access", "Principal `ciam-admins`: review overdue",
         "the platform admins' access review is over a year old", None),
        ("A39", "Access", "source/prod runs identity `identity-idm`",
         "the source runs an IDM role nobody records as acting as it", None),
        ("A40", "Access", "Operators come into source/prod by session",
         "operators reach the target's servers by a bastion; nothing records a session manager there", None),
        ("A41", "Access", "identity `identity-ds` is granted `s3:* on *`",
         "the source's directory role may do anything in S3, wider than writing its backups", None),
        ("A42", "Access", "whether identity `identity-admins` may `manage pf-admin-password` can't be told",
         "the target's admins hold Key Vault Administrator only as PIM-eligible", None),
        ("A43", "Access", "whether identity `identity-admins` may `manage-key disk-encryption` can't be told",
         "the same eligible assignment covers the disk key", None),
        ("A44", "Guardrail", "guardrail `org-guardrails` prevents `audit-log-disable`",
         "the target's policy assignments don't stop audit logs being disabled (a request to the landing zone team)",
         None),
        ("A45", "Edge", "source/prod runs `stickiness source-ip` in front of `ig-service`",
         "the gateway's source load balancer keeps clients on one server by source address, which no policy states",
         None),
        ("A46", "Edge", "Clients can send header `X-Partner-User` themselves",
         "the gateway doesn't strip the partner user header from incoming requests", None),
        ("A47", "Edge", "`am-service` changes from TLS passthrough",
         "login moves to a TLS-terminating gateway: PingAM must trust its X-Forwarded-For", None),
        ("A48", "Edge", "`pf-sso-service` changes from TLS passthrough",
         "sso moves to a TLS-terminating gateway: PingFederate must trust its X-Forwarded-For", None),
        ("A49", "DNS", "Lower the TTL of `apps.example-aero.test`", "the corporate DNS team's 3600 s TTL", None),
        ("A50", "DNS", "Lower the TTL of `login.example-aero.test`", "the corporate DNS team's 3600 s TTL", None),
        ("A51", "DNS", "Lower the TTL of `sso.example-aero.test`", "the corporate DNS team's 3600 s TTL", None),
        ("A52", "DNS", "corporate-dns runs zone `example-aero.test`: ask them to point `apps.example-aero.test`",
         "the public zone is on the corporate DNS team's Infoblox (a request drafted to them)", None),
        ("A53", "DNS", "corporate-dns runs zone `example-aero.test`: ask them to point `login.example-aero.test`",
         "the same zone", None),
        ("A54", "DNS", "corporate-dns runs zone `example-aero.test`: ask them to point `sso.example-aero.test`",
         "the same zone", None),
        ("A55", "DNS", "source/prod has private zone `id.example-aero.test`",
         "the target publishes LDAPS in the landing zone's default private zone (B1)", "CHG-2003"),
        ("A56", "Edge", "sets no rate limit on password-reset",
         "PingFederate's self-service password reset has no rate limit; the policy limits sign-in and tokens", None),
        ("A57", "Endpoint services", "Consumer `supplier-portal-svc` connects to `ldaps-link` privately",
         "the supplier portal reaches LDAPS through the source's endpoint service; the target's has another name",
         None),
        ("A58", "Endpoint services", "source/prod allows `arn:aws:iam::444455556666:root` to connect to `ldaps-link`",
         "the target's Private Link Service allows the portal's Azure subscription, not its AWS account", None),
        ("A59", "Egress", "doesn't allow `email-smtp.us-east-1.amazonaws.com`",
         "the hub firewall in the target doesn't allow the mail relay the platform sends through", None),
        *((f"A{60 + i}", "Egress proxy", f"so `{role}` must be told",
           f"the target's outside traffic goes through the hub's forward proxy; {what}", None)
          for i, (role, what) in enumerate((
              ("am", "PingAM's HTTP client and JVM options don't name it"),
              ("pf-engine", "the engines' captured run.properties lacks the proxy keys (a fix links them)"),
              ("pf-admin", "the admin node's run.properties and revocation checking don't name it"),
              ("ig", "PingGateway's ProxyOptions and JVM options don't name it"),
              ("idm", "PingIDM's boot.properties and JVM options don't name it")))),
        ("A65", "Flow logs", "`flow-vnet` keeps flow logs 14 days in target/prod",
         "the target's flow log (still to be built by the network team) keeps 14 days; the source keeps 30", None),
        ("A66", "Egress", "no route sends internet egress through `egress-firewall`",
         "the target's route table sends internet traffic straight to the NAT gateway, around the hub firewall whose "
         "domain rules the stack relies on", None),
        ("A67", "PingFederate", "Data store `corp-directory` reaches a fixed host",
         "PingFederate's corporate directory store lists two domain controllers, the same from every environment "
         "(its fix records both, in order, as one role's hosts)", None),
    ],
})

KEYS = ("id", "area", "match", "planted", "cleared_by")


def expected_findings():
    """The data/expected-findings.json document."""
    return {"_comment": "Generated by scripts/gen-synthetic.py: the problems planted in the synthetic data.",
            **{kind: [dict(zip(KEYS, row)) for row in rows] for kind, rows in EXPECTED.items()}}
