#!/usr/bin/env bash
# Generated by opsdir for ds-2 in env=prod,cloud=source,ou=environments,dc=ciam-ops
# PingDS 7.5.1; new or existing deployment.
# Secrets are resolved at run time from references; no secret value is stored in this file.
# The TLS keystore (binding role ds-tls-keystore) is materialized by the secrets agent before this runs.
set -euo pipefail
DEPLOYMENT_ID="$(aws secretsmanager get-secret-value --secret-id 'arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/ds-deployment-id' --query SecretString --output text)"
DEPLOYMENT_ID_PASSWORD="$(aws secretsmanager get-secret-value --secret-id 'arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/ds-deployment-password' --query SecretString --output text)"
ROOT_PASSWORD="$(aws secretsmanager get-secret-value --secret-id 'arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/prod/ds-root-password' --query SecretString --output text)"

./setup \
  --serverId ds-2 \
  --deploymentId "$DEPLOYMENT_ID" \
  --deploymentIdPassword "$DEPLOYMENT_ID_PASSWORD" \
  --rootUserDn uid=admin \
  --rootUserPassword "$ROOT_PASSWORD" \
  --hostname ds-2.aws.internal.example-aero.test \
  --adminConnectorPort 4444 \
  --ldapsPort 1636 \
  --httpsPort 8443 \
  --replicationPort 8989 \
  --bootstrapReplicationServer ds-1.aws.internal.example-aero.test:8989 \
  --bootstrapReplicationServer ds-2.aws.internal.example-aero.test:8989 \
  --bootstrapReplicationServer ds-3.aws.internal.example-aero.test:8989 \
  --profile ds-user-data \
  --set ds-user-data/baseDn:dc=partners,dc=example-aero,dc=test \
  --acceptLicense

# Then apply the environment-neutral configuration:
#   dsconfig ... --batchFilePath ../ds/dsconfig.batch
