"""The Ansible inventory of an environment's servers, and how a playbook reads a secret reference at run time: the
native lookup of the adapter owning its scheme, else a pipe to the scheme's resolver command."""
import yaml

from opsdir.connectors.registry import services
from opsdir.core.environment import env_model
from opsdir.core.interchange.ldif import parse
from opsdir_adapter_ansible.names import ansible_name
from opsdir_adapter_ansible.render import render
from network_fixtures import ALPHA, entry, model
from support import REGISTRY, build_directory
import mini_estate


def _files(m):
    return {p: yaml.safe_load(t) for p, t in render(m, services()).items()}


def test_one_group_per_role_hosts_by_name():
    _, alpha, _ = model()
    files = _files(alpha)
    assert files["ansible/inventory/hosts.yml"] == {"all": {"children": {
        "ds": {"hosts": {"ds-1.example.test": None, "ds-2.example.test": None}},
        "web": {"hosts": {"web-1.example.test": None}}}}}
    assert files["ansible/inventory/group_vars/all.yml"] == {
        "ciam_environment": "alpha/prod", "ciam_provider": "fakecloud", "ciam_region": "region-1"}
    assert files["ansible/inventory/group_vars/ds.yml"] == {"ciam_role": "ds"}
    assert files["ansible/inventory/host_vars/ds-1.example.test.yml"] == {
        "ciam_server": "ds-1", "ciam_zone": "zone-a", "ciam_subnet": "10.1.1.0/24"}


def test_a_recorded_address_is_ansible_host_and_every_file_has_its_header():
    _, alpha, _ = model(alpha=(entry(ALPHA, "pf-1", "ciamServer", ciamServerRole="pf-engine",
                                     ciamHostname="pf-1.example.test", ciamPrivateIp="10.1.2.9",
                                     ciamSubnet=f"cn=subnet-web,ou=bindings,{ALPHA}"),))
    files = render(alpha, services())
    assert yaml.safe_load(files["ansible/inventory/hosts.yml"])["all"]["children"]["pf_engine"] == {
        "hosts": {"pf-1.example.test": {"ansible_host": "10.1.2.9"}}}
    assert all(t.startswith("# Generated by opsdir from env=prod,cloud=alpha") for t in files.values())


def test_group_names_are_identifiers():
    assert (ansible_name("pf-engine"), ansible_name("ds"), ansible_name("2fa.web")) == ("pf_engine", "ds", "_2fa_web")


def _with_stores(*stores):
    return env_model(build_directory(REGISTRY, tuple(parse("\n".join((mini_estate.LDIF, *stores))))), "alpha/prod")


def _store(cn, scheme, **attrs):
    return entry(ALPHA, cn, "ciamSecretStore", ciamBindingRole=f"secret-store-{scheme}", ciamRefScheme=scheme,
                 **attrs)


def test_native_lookups_where_the_scheme_owner_has_one():
    lookup = services().ansible_lookup
    m = _with_stores()
    assert lookup(m, "aws-sm://ciam/prod/pf-admin") == 'lookup("amazon.aws.aws_secret", "ciam/prod/pf-admin")'
    assert lookup(m, "k8s-secret://ciam/pf-admin/password") == (
        '(lookup("kubernetes.core.k8s", kind="Secret", namespace="ciam", resource_name="pf-admin")'
        '.data["password"] | b64decode)')
    assert lookup(m, "vault://secret/ciam/pf-admin") == (
        'lookup("community.hashi_vault.vault_kv2_get", "ciam/pf-admin", engine_mount_point="secret").secret.value')


def test_the_store_binding_shapes_the_lookup():
    lookup = services().ansible_lookup
    m = _with_stores(_store("kv", "azkv", ciamStoreEndpoint="https://kv-ciam.vault.usgovcloudapi.net/"),
                     _store("vault", "vault", ciamStoreEndpoint="https://vault.example.test:8200",
                            ciamStoreKvVersion="1"))
    assert lookup(m, "azkv://kv-prod/pf-admin") == ('lookup("azure.azcollection.azure_keyvault_secret", "pf-admin", '
                                                    'vault_url="https://kv-prod.vault.usgovcloudapi.net/")')
    assert lookup(m, "vault://kv/ciam/pf-admin") == (
        'lookup("community.hashi_vault.vault_kv1_get", "ciam/pf-admin", engine_mount_point="kv", '
        'url="https://vault.example.test:8200").secret.value')


def test_otherwise_a_pipe_to_the_schemes_resolver_command():
    lookup = services().ansible_lookup
    m = _with_stores()
    assert lookup(m, "azkv://kv-prod/pf-admin") == (
        'lookup("ansible.builtin.pipe", "az keyvault secret show --vault-name \'kv-prod\' --name \'pf-admin\' '
        '--query value -o tsv")')
    assert lookup(m, "cyberark://ciam/Ping/pf-admin").startswith(
        'lookup("ansible.builtin.pipe", "clipasswordsdk GetPassword -p AppDescs.AppID=\'ciam\'')
