# Generated by opsdir from env=prod,cloud=standby,ou=environments,dc=ciam-ops
# Google Cloud landing zone for the CIAM platform, kept by cloud-landing-zone: applied by the landing zone, not by the platform's pipeline
# Do not edit. Change the operations directory (under an approved change) and re-render.

resource "google_iam_workload_identity_pool" "ci" {
  workload_identity_pool_id = "ciam-prod-ci"
  display_name              = "CIAM prod CI"
}

resource "google_iam_workload_identity_pool_provider" "token_actions_githubusercontent_com" {
  workload_identity_pool_id          = google_iam_workload_identity_pool.ci.workload_identity_pool_id
  workload_identity_pool_provider_id = "token-actions-githubusercontent"
  attribute_mapping = {
    "google.subject" = "assertion.sub"
  }
  attribute_condition = "assertion.sub in ['repo:example-aero/ciam-ops:environment:standby']"
  oidc {
    issuer_uri = "https://token.actions.githubusercontent.com"
  }
}

resource "google_service_account" "identity_ci" {
  account_id   = "ciam-standby-deploy"
  display_name = "ciam-ops-ci (identity-ci)"
}

resource "google_service_account_iam_member" "identity_ci_ci" {
  service_account_id = google_service_account.identity_ci.name
  role               = "roles/iam.workloadIdentityUser"
  member             = "principal://iam.googleapis.com/${google_iam_workload_identity_pool.ci.name}/subject/repo:example-aero/ciam-ops:environment:standby"
}

resource "google_project_iam_member" "identity_ci_manage_pf_sso_service" {
  # granted on the project: the narrowest scope Google Cloud allows for it
  project = var.project_id
  role    = "roles/compute.loadBalancerAdmin"
  member  = "serviceAccount:${google_service_account.identity_ci.email}"
}

resource "google_secret_manager_secret_iam_member" "identity_ci_write_secret_pf_admin_password" {
  project   = "example-aero-ciam-standby"
  secret_id = "pf-admin-password"
  role      = "roles/secretmanager.secretVersionAdder"
  member    = "serviceAccount:${google_service_account.identity_ci.email}"
}

resource "google_secret_manager_secret_iam_member" "identity_admins_manage_pf_admin_password" {
  project   = "example-aero-ciam-standby"
  secret_id = "pf-admin-password"
  role      = "roles/secretmanager.admin"
  member    = "group:ciam-admins@example-aero.test"
}

resource "google_kms_crypto_key_iam_member" "identity_admins_manage_key_disk_encryption" {
  crypto_key_id = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  role          = "roles/cloudkms.admin"
  member        = "group:ciam-admins@example-aero.test"
}

resource "google_project_iam_member" "identity_admins_read_logs_audit_logs" {
  # granted on the project: the narrowest scope Google Cloud allows for it
  project = "example-aero-ciam-standby"
  role    = "roles/logging.viewer"
  member  = "group:ciam-admins@example-aero.test"
}

resource "google_org_policy_policy" "gcp_resourcelocations" {
  name   = "projects/${var.project_id}/policies/gcp.resourceLocations"
  parent = "projects/${var.project_id}"
  spec {
    rules {
      values {
        allowed_values = ["in:us-central1-locations"]
      }
    }
  }
}

resource "google_org_policy_policy" "storage_publicaccessprevention" {
  name   = "projects/${var.project_id}/policies/storage.publicAccessPrevention"
  parent = "projects/${var.project_id}"
  spec {
    rules {
      enforce = "TRUE"
    }
  }
}

resource "google_org_policy_policy" "iam_disableauditloggingexemption" {
  # Admin Activity audit logs can't be disabled; this stops new audit-logging exemptions
  name   = "projects/${var.project_id}/policies/iam.disableAuditLoggingExemption"
  parent = "projects/${var.project_id}"
  spec {
    rules {
      enforce = "TRUE"
    }
  }
}

resource "google_org_policy_policy" "iam_disableserviceaccountkeycreation" {
  name   = "projects/${var.project_id}/policies/iam.disableServiceAccountKeyCreation"
  parent = "projects/${var.project_id}"
  spec {
    rules {
      enforce = "TRUE"
    }
  }
}

resource "google_org_policy_policy" "iam_disableserviceaccountkeyupload" {
  name   = "projects/${var.project_id}/policies/iam.disableServiceAccountKeyUpload"
  parent = "projects/${var.project_id}"
  spec {
    rules {
      enforce = "TRUE"
    }
  }
}

resource "google_org_policy_policy" "cloudkms_disablebeforedestroy" {
  name   = "projects/${var.project_id}/policies/cloudkms.disableBeforeDestroy"
  parent = "projects/${var.project_id}"
  spec {
    rules {
      enforce = "TRUE"
    }
  }
}

data "google_project" "budgets" {
  project_id = var.project_id
}

resource "google_billing_budget" "monthly_spend" {
  billing_account = "01A2B3-C4D5E6-F7A8B9"
  display_name    = "standby-prod-monthly-spend"
  budget_filter {
    projects = ["projects/${data.google_project.budgets.number}"]
    labels = {
      environment = "standby-prod"
    }
    calendar_period = "MONTH"
  }
  amount {
    specified_amount {
      currency_code = "USD"
      units         = "12000"
    }
  }
  threshold_rules {
    threshold_percent = 0.8
    spend_basis       = "CURRENT_SPEND"
  }
  threshold_rules {
    threshold_percent = 1.0
    spend_basis       = "CURRENT_SPEND"
  }
  threshold_rules {
    threshold_percent = 1.0
    spend_basis       = "FORECASTED_SPEND"
  }
  all_updates_rule {
    monitoring_notification_channels = ["projects/example-aero-ciam-standby/notificationChannels/1001"]
  }
}
