# Generated by opsdir from env=prod,cloud=standby,ou=environments,dc=ciam-ops
# Providers and inputs (landing zone)
# Do not edit. Change the operations directory (under an approved change) and re-render.

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 8.0"
    }
  }
}

provider "google" {
  project               = var.project_id
  billing_project       = var.project_id
  user_project_override = true
  default_labels = {
    costcenter         = "cc-1001"
    dataclassification = "confidential"
    environment        = "standby-prod"
    owner              = "ciam-platform"
  }
}

variable "project_id" {
  type        = string
  description = "The project prod runs in"
  default     = "example-aero-ciam-standby"
}
