# Generated by opsdir from env=stage,cloud=source,ou=environments,dc=ciam-ops
# AWS infrastructure for the CIAM platform
# Do not edit. Change the operations directory (under an approved change) and re-render.

data "aws_vpc" "main" {
  id = "vpc-0a1b2c3d4e5f67890"
}

data "aws_subnet" "subnet_am_a" {
  id = "subnet-0c77d88e99fa00b1a"
}

data "aws_subnet" "subnet_am_b" {
  id = "subnet-0c77d88e99fa00b1b"
}

data "aws_subnet" "subnet_ds_a" {
  id = "subnet-0a11b22c33d44e55a"
}

data "aws_subnet" "subnet_ds_b" {
  id = "subnet-0a11b22c33d44e55b"
}

data "aws_subnet" "subnet_ds_c" {
  id = "subnet-0a11b22c33d44e55c"
}

data "aws_subnet" "subnet_idm_a" {
  id = "subnet-0d88e99fa00b11c2a"
}

data "aws_subnet" "subnet_ig_a" {
  id = "subnet-0e99fa00b11c22d3a"
}

data "aws_subnet" "subnet_pf_a" {
  id = "subnet-0f66e77d88c99b00a"
}

data "aws_subnet" "subnet_pf_b" {
  id = "subnet-0f66e77d88c99b00b"
}

resource "aws_security_group" "am" {
  name        = "ciam-stage-am"
  description = "CIAM am (source/stage)"
  vpc_id      = data.aws_vpc.main.id
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "aws_security_group" "ds" {
  name        = "ciam-stage-ds"
  description = "CIAM ds (source/stage)"
  vpc_id      = data.aws_vpc.main.id
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "aws_security_group" "idm" {
  name        = "ciam-stage-idm"
  description = "CIAM idm (source/stage)"
  vpc_id      = data.aws_vpc.main.id
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "aws_security_group" "ig" {
  name        = "ciam-stage-ig"
  description = "CIAM ig (source/stage)"
  vpc_id      = data.aws_vpc.main.id
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "aws_security_group" "pf_admin" {
  name        = "ciam-stage-pf-admin"
  description = "CIAM pf-admin (source/stage)"
  vpc_id      = data.aws_vpc.main.id
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "aws_security_group" "pf_engine" {
  name        = "ciam-stage-pf-engine"
  description = "CIAM pf-engine (source/stage)"
  vpc_id      = data.aws_vpc.main.id
  tags = {
    ManagedBy = "opsdir"
  }
}

resource "aws_vpc_security_group_ingress_rule" "fw_admin_0_4444" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.20.9.0/28"
  from_port         = 4444
  to_port           = 4444
  ip_protocol       = "tcp"
  description       = "fw-admin (fw-admin)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_apps_public_0_443" {
  security_group_id = aws_security_group.ig.id
  cidr_ipv4         = "0.0.0.0/0"
  from_port         = 443
  to_port           = 443
  ip_protocol       = "tcp"
  description       = "fw-apps-public (fw-apps-public)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_login_public_0_443" {
  security_group_id = aws_security_group.am.id
  cidr_ipv4         = "0.0.0.0/0"
  from_port         = 443
  to_port           = 443
  ip_protocol       = "tcp"
  description       = "fw-login-public (fw-login-public)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_pf_ds_svc_0_1636" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.20.4.0/24"
  from_port         = 1636
  to_port           = 1636
  ip_protocol       = "tcp"
  description       = "consumer pf-ds-svc (fw-pf-ds-svc)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_pf_ds_svc_1_1636" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.20.5.0/24"
  from_port         = 1636
  to_port           = 1636
  ip_protocol       = "tcp"
  description       = "consumer pf-ds-svc (fw-pf-ds-svc)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_replication_0_8989" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.20.1.0/24"
  from_port         = 8989
  to_port           = 8989
  ip_protocol       = "tcp"
  description       = "fw-replication (fw-replication)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_replication_1_8989" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.20.2.0/24"
  from_port         = 8989
  to_port           = 8989
  ip_protocol       = "tcp"
  description       = "fw-replication (fw-replication)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_replication_2_8989" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.20.3.0/24"
  from_port         = 8989
  to_port           = 8989
  ip_protocol       = "tcp"
  description       = "fw-replication (fw-replication)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_replication_3_8989" {
  security_group_id = aws_security_group.ds.id
  cidr_ipv4         = "10.60.1.0/24"
  from_port         = 8989
  to_port           = 8989
  ip_protocol       = "tcp"
  description       = "fw-replication (fw-replication)"
}

resource "aws_vpc_security_group_ingress_rule" "fw_sso_public_0_443" {
  security_group_id = aws_security_group.pf_engine.id
  cidr_ipv4         = "0.0.0.0/0"
  from_port         = 443
  to_port           = 443
  ip_protocol       = "tcp"
  description       = "fw-sso-public (fw-sso-public)"
}

resource "aws_instance" "am_s1" {
  ami                    = "ami-0a9b8c7d6e5f40321"
  instance_type          = "m6i.large"
  subnet_id              = data.aws_subnet.subnet_am_a.id
  private_ip             = "10.20.7.31"
  vpc_security_group_ids = [aws_security_group.am.id]
  root_block_device {
    encrypted  = true
    kms_key_id = "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
  }
  tags = {
    Name      = "am-s1"
    Role      = "am"
    Hostname  = "am-s1.aws.internal.example-aero.test"
    Product   = "PingAM 7.5.1"
    ManagedBy = "opsdir"
  }
}

resource "aws_instance" "ds_s1" {
  ami                    = "ami-0abcdef1234567890"
  instance_type          = "m6i.large"
  subnet_id              = data.aws_subnet.subnet_ds_a.id
  private_ip             = "10.20.1.31"
  vpc_security_group_ids = [aws_security_group.ds.id]
  root_block_device {
    encrypted  = true
    kms_key_id = "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
  }
  tags = {
    Name      = "ds-s1"
    Role      = "ds"
    Hostname  = "ds-s1.aws.internal.example-aero.test"
    Product   = "PingDS 7.5.1"
    ManagedBy = "opsdir"
  }
}

resource "aws_instance" "idm_s1" {
  ami                    = "ami-0b1c2d3e4f5a60987"
  instance_type          = "m6i.large"
  subnet_id              = data.aws_subnet.subnet_idm_a.id
  private_ip             = "10.20.6.31"
  vpc_security_group_ids = [aws_security_group.idm.id]
  root_block_device {
    encrypted  = true
    kms_key_id = "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
  }
  tags = {
    Name      = "idm-s1"
    Role      = "idm"
    Hostname  = "idm-s1.aws.internal.example-aero.test"
    Product   = "PingIDM 7.5.0"
    ManagedBy = "opsdir"
  }
}

resource "aws_instance" "ig_s1" {
  ami                    = "ami-0c2d3e4f5a6b70123"
  instance_type          = "m6i.large"
  subnet_id              = data.aws_subnet.subnet_ig_a.id
  private_ip             = "10.20.10.31"
  vpc_security_group_ids = [aws_security_group.ig.id]
  root_block_device {
    encrypted  = true
    kms_key_id = "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
  }
  tags = {
    Name      = "ig-s1"
    Role      = "ig"
    Hostname  = "ig-s1.aws.internal.example-aero.test"
    Product   = "PingGateway 2024.11.0"
    ManagedBy = "opsdir"
  }
}

resource "aws_instance" "pf_admin_s1" {
  ami                    = "ami-0fedcba9876543210"
  instance_type          = "m6i.large"
  subnet_id              = data.aws_subnet.subnet_pf_a.id
  private_ip             = "10.20.4.32"
  vpc_security_group_ids = [aws_security_group.pf_admin.id]
  root_block_device {
    encrypted  = true
    kms_key_id = "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
  }
  tags = {
    Name      = "pf-admin-s1"
    Role      = "pf-admin"
    Hostname  = "pf-admin-s1.aws.internal.example-aero.test"
    Product   = "PingFederate 12.1.4"
    ManagedBy = "opsdir"
  }
}

resource "aws_instance" "pf_engine_s1" {
  ami                    = "ami-0fedcba9876543210"
  instance_type          = "m6i.large"
  subnet_id              = data.aws_subnet.subnet_pf_a.id
  private_ip             = "10.20.4.31"
  vpc_security_group_ids = [aws_security_group.pf_engine.id]
  root_block_device {
    encrypted  = true
    kms_key_id = "arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab"
  }
  tags = {
    Name      = "pf-engine-s1"
    Role      = "pf-engine"
    Hostname  = "pf-engine-s1.aws.internal.example-aero.test"
    Product   = "PingFederate 12.1.4"
    ManagedBy = "opsdir"
  }
}

resource "aws_lb" "svc_apps" {
  name               = "ciam-stage-svc-apps"
  internal           = false
  load_balancer_type = "network"
  subnet_mapping {
    subnet_id     = data.aws_subnet.subnet_ig_a.id
    allocation_id = "eipalloc-0a1b2c3d4e5f60006"
  }
  tags = {
    Service   = "apps.stage.example-aero.test"
    ManagedBy = "opsdir"
  }
}

resource "aws_lb_target_group" "svc_apps_443" {
  name        = "ciam-stage-svc-apps-443"
  port        = 443
  protocol    = "TCP"
  vpc_id      = data.aws_vpc.main.id
  target_type = "instance"
  health_check {
    protocol = "TCP"
  }
}

resource "aws_lb_target_group_attachment" "svc_apps_443_ig_s1" {
  target_group_arn = aws_lb_target_group.svc_apps_443.arn
  target_id        = aws_instance.ig_s1.id
  port             = 443
}

resource "aws_lb_listener" "svc_apps_443" {
  load_balancer_arn = aws_lb.svc_apps.arn
  port              = 443
  protocol          = "TCP"
  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.svc_apps_443.arn
  }
}

resource "aws_route53_record" "svc_apps" {
  zone_id = "Z0EXAMPLE2PUBLIC"
  name    = "apps.stage.example-aero.test"
  type    = "A"
  alias {
    name                   = aws_lb.svc_apps.dns_name
    zone_id                = aws_lb.svc_apps.zone_id
    evaluate_target_health = true
  }
}

resource "aws_lb" "svc_ldaps" {
  name               = "ciam-stage-svc-ldaps"
  internal           = true
  load_balancer_type = "network"
  subnet_mapping {
    subnet_id            = data.aws_subnet.subnet_ds_a.id
    private_ipv4_address = "10.20.1.150"
  }
  tags = {
    Service   = "ldap.stage.id.example-aero.test"
    ManagedBy = "opsdir"
  }
}

resource "aws_lb_target_group" "svc_ldaps_1636" {
  name        = "ciam-stage-svc-ldaps-1636"
  port        = 1636
  protocol    = "TCP"
  vpc_id      = data.aws_vpc.main.id
  target_type = "instance"
  health_check {
    protocol = "TCP"
  }
}

resource "aws_lb_target_group_attachment" "svc_ldaps_1636_ds_s1" {
  target_group_arn = aws_lb_target_group.svc_ldaps_1636.arn
  target_id        = aws_instance.ds_s1.id
  port             = 1636
}

resource "aws_lb_listener" "svc_ldaps_1636" {
  load_balancer_arn = aws_lb.svc_ldaps.arn
  port              = 1636
  protocol          = "TCP"
  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.svc_ldaps_1636.arn
  }
}

resource "aws_route53_record" "svc_ldaps" {
  zone_id = "Z0EXAMPLE1PRIVATE"
  name    = "ldap.stage.id.example-aero.test"
  type    = "A"
  alias {
    name                   = aws_lb.svc_ldaps.dns_name
    zone_id                = aws_lb.svc_ldaps.zone_id
    evaluate_target_health = true
  }
}

resource "aws_lb" "svc_login" {
  name               = "ciam-stage-svc-login"
  internal           = false
  load_balancer_type = "network"
  subnet_mapping {
    subnet_id     = data.aws_subnet.subnet_am_a.id
    allocation_id = "eipalloc-0a1b2c3d4e5f60004"
  }
  tags = {
    Service   = "login.stage.example-aero.test"
    ManagedBy = "opsdir"
  }
}

resource "aws_lb_target_group" "svc_login_443" {
  name        = "ciam-stage-svc-login-443"
  port        = 443
  protocol    = "TCP"
  vpc_id      = data.aws_vpc.main.id
  target_type = "instance"
  health_check {
    protocol = "TCP"
  }
}

resource "aws_lb_target_group_attachment" "svc_login_443_am_s1" {
  target_group_arn = aws_lb_target_group.svc_login_443.arn
  target_id        = aws_instance.am_s1.id
  port             = 443
}

resource "aws_lb_listener" "svc_login_443" {
  load_balancer_arn = aws_lb.svc_login.arn
  port              = 443
  protocol          = "TCP"
  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.svc_login_443.arn
  }
}

resource "aws_route53_record" "svc_login" {
  zone_id = "Z0EXAMPLE2PUBLIC"
  name    = "login.stage.example-aero.test"
  type    = "A"
  alias {
    name                   = aws_lb.svc_login.dns_name
    zone_id                = aws_lb.svc_login.zone_id
    evaluate_target_health = true
  }
}

resource "aws_lb" "svc_sso" {
  name               = "ciam-stage-svc-sso"
  internal           = false
  load_balancer_type = "network"
  subnet_mapping {
    subnet_id     = data.aws_subnet.subnet_pf_a.id
    allocation_id = "eipalloc-0a1b2c3d4e5f60002"
  }
  tags = {
    Service   = "sso.stage.example-aero.test"
    ManagedBy = "opsdir"
  }
}

resource "aws_lb_target_group" "svc_sso_443" {
  name        = "ciam-stage-svc-sso-443"
  port        = 443
  protocol    = "TCP"
  vpc_id      = data.aws_vpc.main.id
  target_type = "instance"
  health_check {
    protocol = "TCP"
  }
}

resource "aws_lb_target_group_attachment" "svc_sso_443_pf_engine_s1" {
  target_group_arn = aws_lb_target_group.svc_sso_443.arn
  target_id        = aws_instance.pf_engine_s1.id
  port             = 443
}

resource "aws_lb_listener" "svc_sso_443" {
  load_balancer_arn = aws_lb.svc_sso.arn
  port              = 443
  protocol          = "TCP"
  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.svc_sso_443.arn
  }
}

resource "aws_route53_record" "svc_sso" {
  zone_id = "Z0EXAMPLE2PUBLIC"
  name    = "sso.stage.example-aero.test"
  type    = "A"
  alias {
    name                   = aws_lb.svc_sso.dns_name
    zone_id                = aws_lb.svc_sso.zone_id
    evaluate_target_health = true
  }
}

data "aws_secretsmanager_secret" "am_admin_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/am-admin-password"
}

data "aws_secretsmanager_secret" "am_ds_bind_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/am-ds-bind-password"
}

data "aws_secretsmanager_secret" "am_keystore" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/am-keystore"
}

data "aws_secretsmanager_secret" "ds_deployment_id" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/ds-deployment-id"
}

data "aws_secretsmanager_secret" "ds_deployment_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/ds-deployment-password"
}

data "aws_secretsmanager_secret" "ds_root_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/ds-root-password"
}

data "aws_secretsmanager_secret" "ds_tls_keystore" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/ds-tls-keystore"
}

data "aws_secretsmanager_secret" "idm_admin_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/idm-admin-password"
}

data "aws_secretsmanager_secret" "idm_ds_bind_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/idm-ds-bind-password"
}

data "aws_secretsmanager_secret" "idm_hrdb_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/idm-hrdb-password"
}

data "aws_secretsmanager_secret" "idm_keystore" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/idm-keystore"
}

data "aws_secretsmanager_secret" "ig_keystore" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/ig-keystore"
}

data "aws_secretsmanager_secret" "pf_admin_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/pf-admin-password"
}

data "aws_secretsmanager_secret" "pf_captcha_secret" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/pf-captcha-secret"
}

data "aws_secretsmanager_secret" "pf_ds_bind_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/pf-ds-bind-password"
}

data "aws_secretsmanager_secret" "pf_grants_db_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/pf-grants-db-password"
}

data "aws_secretsmanager_secret" "pf_signing_key" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/pf-signing-key"
}

data "aws_secretsmanager_secret" "pf_smtp_password" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/pf-smtp-password"
}

data "aws_secretsmanager_secret" "sso_tls_keystore" {
  arn = "arn:aws:secretsmanager:us-east-1:111122223333:secret:ciam/stage/sso-tls-keystore"
}

data "aws_s3_bucket" "ds_backups" {
  bucket = "example-aero-ciam-stage-ds-backups"
}

data "aws_nat_gateway" "pf_egress" {
  id = "nat-0123456789abcdef0"
}
