# Generated by opsdir from env=stage,cloud=source,ou=environments,dc=ciam-ops
# Providers
# Do not edit. Change the operations directory (under an approved change) and re-render.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region              = "us-east-1"
  allowed_account_ids = ["111122223333"]
  default_tags {
    tags = {
      CostCenter         = "CC-1001"
      DataClassification = "internal"
      Environment        = "source/stage"
      Owner              = "ciam-platform"
    }
  }
}

variable "resolver_endpoint_id" {
  description = "The landing zone's outbound Route 53 Resolver endpoint the forwarding rules use"
  type        = string
}
