"""Core records read against the showcase data and the installed adapters."""
import hashlib
import json

import pytest

from opsdir.connectors.registry import (ADAPTERS, KIND_ORDER, definition_files, ref_schemes, schema_fragments,
                                       secret_command)
from opsdir.core.directory import get
from opsdir.core.environment import env_model
from opsdir.core.findings import owner_label, responsible
from opsdir.core.formats import JSON, SHELL, XML
from opsdir.core.manifest import header, manifest
from opsdir.core.standard import CORE
from opsdir.domains.governance.domain import display_name, operator


def test_owners_come_from_the_directory(estate):
    d = estate["before"]
    owned = get(d, "env=prod,cloud=source,ou=environments,dc=ciam-ops")
    unowned = get(d, "cn=legacy-rptuser,ou=consumers,dc=ciam-ops")
    assert owner_label(d, owned) == "ciam-platform"
    assert owner_label(d, unowned) == "**NO OWNER**"
    assert responsible(d, None, unowned, owned) == "ciam-platform"      # first entry that has an owner
    assert responsible(d, unowned) == "**NO OWNER**"


def test_operator_and_display_names_are_data(estate):
    d = estate["before"]
    assert display_name(get(d, "cn=ciam-platform,ou=owners,dc=ciam-ops")) == "CIAM platform team"
    assert display_name(get(d, "cn=network-security,ou=owners,dc=ciam-ops")) == "network-security"   # no display name
    assert operator(d).dn == "cn=example-aero,ou=owners,dc=ciam-ops"


def test_manifest_lists_scope_format_and_hash_of_every_file(estate):
    m = env_model(estate["before"], "target/prod", ("backup-target",))
    doc = json.loads(manifest(m, {"b.txt": "neutral"}, {"a.txt": "specific"}, {"a.txt": "text", "b.txt": "text"}))
    assert doc["environment"] == m.dn and doc["provider"] == "azure" and doc["unbound_roles"] == ["backup-target"]
    assert list(doc["files"]) == ["a.txt", "b.txt"]
    assert doc["files"]["b.txt"] == {"scope": "environment-neutral", "format": "text",
                                     "sha256": hashlib.sha256(b"neutral").hexdigest()}
    assert doc["files"]["a.txt"]["scope"] == "environment-specific"
    assert header(m, "what", SHELL).splitlines()[0] == f"# Generated by opsdir from {m.dn}"
    assert header(m, "what", XML).splitlines()[:2] == ["<!--", f"  Generated by opsdir from {m.dn}"]
    assert header(m, "what", JSON) == ""


def test_registry_composition():
    assert schema_fragments()[0] is CORE
    files = definition_files()
    assert files[0].name == "graph.sql" and files[-1].name == "connectors.sql"
    assert all(f.is_file() for f in files)
    schemes = ref_schemes()
    assert len(schemes) == len(set(schemes)) and {"aws-sm", "vault"} <= set(schemes)
    assert all(a.kind in KIND_ORDER for a in ADAPTERS)


@pytest.mark.parametrize("uri, command", [
    ("aws-sm://prod/ds/root", "aws secretsmanager get-secret-value --secret-id 'prod/ds/root'"),
    ("azkv://kv-prod/ds-root", "az keyvault secret show --vault-name 'kv-prod' --name 'ds-root'"),
    ("vault://secret/ds/root", "vault kv get -field=value 'secret/ds/root'")])
def test_secret_references_resolve_through_the_owning_adapter(uri, command):
    assert secret_command(uri).startswith(command)


def test_unknown_secret_scheme_exits():
    with pytest.raises(SystemExit):
        secret_command("nosuch://x")
