"""directory domain schema fragment: its attribute types and object classes (OIDs pinned by number)."""
from ...core.standard import AttributeDef, ClassDef, fragment

ATTRIBUTES = (
    AttributeDef(3, 'snap', 'string', 'observed', True,
                 'RDN of an observed configuration snapshot'),
    AttributeDef(47, 'ciamBackendType', 'string', 'intent', True,
                 'DS backend type'),
    AttributeDef(48, 'ciamBaseDn', 'extdn', 'intent', True,
                 'Base DN in the user directory'),
    AttributeDef(49, 'ciamIndexedAttribute', 'dn', 'intent', True,
                 'User-directory attribute record being indexed'),
    AttributeDef(50, 'ciamIndexType', 'enum:equality|presence|substring|ordering|approximate', 'intent', False,
                 'DS index type'),
    AttributeDef(51, 'ciamStorageScheme', 'string', 'intent', True,
                 'Password storage scheme'),
    AttributeDef(52, 'ciamLockoutFailureCount', 'int', 'intent', True,
                 'Failed binds before lockout'),
    AttributeDef(53, 'ciamLockoutDuration', 'string', 'intent', True,
                 'Lockout duration (DS duration syntax)'),
    AttributeDef(54, 'ciamPasswordHistoryCount', 'int', 'intent', True,
                 'Passwords remembered'),
    AttributeDef(55, 'ciamMaxPasswordAge', 'string', 'intent', True,
                 'Maximum password age (DS duration syntax)'),
    AttributeDef(56, 'ciamEnabled', 'bool', 'intent', True,
                 'Enabled flag'),
    AttributeDef(57, 'ciamListenPort', 'port', 'intent', True,
                 'Listener port'),
    AttributeDef(58, 'ciamReplicaCount', 'int', 'intent', True,
                 'DS replicas per environment'),
    AttributeDef(59, 'ciamReplicationPurgeDelay', 'string', 'intent', True,
                 'Replication changelog purge delay'),
    AttributeDef(60, 'ciamServerRef', 'dn', 'observed', True,
                 'Server a snapshot was captured from'),
    AttributeDef(61, 'ciamCapturedAt', 'time', 'observed', True,
                 'Snapshot capture time'),
    AttributeDef(62, 'ciamLdapName', 'string', 'intent', True,
                 'Attribute or object class name in the user directory'),
    AttributeDef(63, 'ciamPiiClass', 'enum:none|low|moderate|high', 'intent', True,
                 'Privacy classification'),
    AttributeDef(64, 'ciamExportControlled', 'bool', 'intent', True,
                 'Export-control relevant'),
    AttributeDef(65, 'ciamPurpose', 'string', 'intent', True,
                 'Why the attribute is stored'),
    AttributeDef(66, 'ciamRetentionRule', 'string', 'intent', True,
                 'Retention rule'),
    AttributeDef(67, 'ciamBindDn', 'extdn', 'intent', True,
                 'Bind DN in the user directory'),
    AttributeDef(68, 'ciamObservedSource', 'cidr', 'observed', False,
                 'Source addresses seen in access logs'),
    AttributeDef(69, 'ciamOperationMix', 'string', 'observed', True,
                 'Operation mix seen in access logs'),
    AttributeDef(70, 'ciamSubtreeRead', 'extdn', 'observed', False,
                 'Subtrees searched'),
    AttributeDef(71, 'ciamAttrRead', 'dn', 'observed', False,
                 'User-directory attribute records read'),
    AttributeDef(72, 'ciamUnindexedSearchesPerDay', 'int', 'observed', True,
                 'Unindexed searches per day'),
    AttributeDef(73, 'ciamTlsOnly', 'bool', 'observed', True,
                 'Only TLS connections seen'),
    AttributeDef(74, 'ciamPeakOpsPerSec', 'int', 'observed', True,
                 'Peak operations per second'),
    AttributeDef(75, 'ciamFirstSeen', 'time', 'observed', True,
                 'First seen in logs'),
    AttributeDef(76, 'ciamLastSeen', 'time', 'observed', True,
                 'Last seen in logs'),
    AttributeDef(78, 'ciamMigrationStatus', 'enum:unknown|identified|contacted|tested|cutover', 'meta', True,
                 'Migration readiness of a consumer'),
    AttributeDef(79, 'ciamAciTargetDn', 'extdn', 'intent', True,
                 'Subtree the ACI is placed on'),
    AttributeDef(80, 'ciamAciTargetAttr', 'dn', 'intent', False,
                 'User-directory attribute records the ACI covers'),
    AttributeDef(81, 'ciamAciAllAttributes', 'bool', 'intent', True,
                 'ACI covers all attributes (targetattr=*)'),
    AttributeDef(82, 'ciamAciRight', 'enum:read|search|compare|write|add|delete|selfwrite|all', 'intent', False,
                 'Granted rights'),
    AttributeDef(83, 'ciamAciGrantee', 'dn', 'intent', False,
                 'Consumer(s) the ACI grants to'),
    AttributeDef(84, 'ciamJustification', 'string', 'meta', True,
                 'Why the access exists'),
    AttributeDef(85, 'ciamReviewedOn', 'time', 'meta', True,
                 'Last access review'),
    # Definitions of user-directory attributes and classes the standards do not provide (core.ldap_schema)
    AttributeDef(130, 'ciamLdapOid', 'string', 'intent', True,
                 'OID of a non-standard user-directory attribute type or object class'),
    AttributeDef(131, 'ciamLdapSyntax', 'string', 'intent', True,
                 'LDAP syntax OID of a non-standard user-directory attribute'),
    AttributeDef(132, 'ciamLdapEquality', 'string', 'intent', True,
                 'Equality matching rule of a non-standard user-directory attribute'),
    AttributeDef(133, 'ciamLdapSubstring', 'string', 'intent', True,
                 'Substring matching rule of a non-standard user-directory attribute'),
    AttributeDef(134, 'ciamLdapOrdering', 'string', 'intent', True,
                 'Ordering matching rule of a non-standard user-directory attribute'),
    AttributeDef(135, 'ciamLdapSingleValue', 'bool', 'intent', True,
                 'A non-standard user-directory attribute holds one value'),
    AttributeDef(136, 'ciamLdapClassKind', 'enum:structural|auxiliary|abstract', 'intent', True,
                 'Kind of a user-directory object class'),
    AttributeDef(137, 'ciamLdapSuperior', 'string', 'intent', True,
                 'Superclass (by name: standard, or another recorded class) of a user-directory object class'),
    AttributeDef(138, 'ciamLdapMust', 'dn', 'intent', False,
                 'User-directory attribute records a user-directory object class requires'),
    AttributeDef(139, 'ciamLdapMay', 'dn', 'intent', False,
                 'User-directory attribute records a user-directory object class allows'),
)
CLASSES = (
    ClassDef(16, 'ciamBackend', 'ciamObject', 'STRUCTURAL', ('cn', 'ciamBackendType', 'ciamBaseDn'),
             (),
             'DS backend'),
    ClassDef(17, 'ciamIndex', 'ciamObject', 'STRUCTURAL', ('cn', 'ciamIndexedAttribute', 'ciamIndexType'),
             (),
             'DS backend index'),
    ClassDef(18, 'ciamPasswordPolicy', 'ciamObject', 'STRUCTURAL', ('cn', 'ciamStorageScheme'),
             ('ciamLockoutFailureCount', 'ciamLockoutDuration', 'ciamPasswordHistoryCount', 'ciamMaxPasswordAge', 'ciamPopulation'),
             'Password policy'),
    ClassDef(19, 'ciamConnectionHandler', 'ciamObject', 'STRUCTURAL', ('cn', 'ciamEnabled'),
             ('ciamListenPort',),
             'DS connection handler'),
    ClassDef(20, 'ciamLogPublisher', 'ciamObject', 'STRUCTURAL', ('cn', 'ciamEnabled'),
             (),
             'DS log publisher'),
    ClassDef(21, 'ciamReplicationTopology', 'ciamObject', 'STRUCTURAL', ('cn', 'ciamReplicaCount'),
             ('ciamReplicationPurgeDelay',),
             'Replication topology shape'),
    ClassDef(22, 'ciamSnapshot', 'ciamObject', 'STRUCTURAL', ('snap', 'ciamServerRef', 'ciamCapturedAt'),
             (),
             'Observed config snapshot of one server'),
    ClassDef(23, 'ciamUserAttribute', 'ciamObject', 'STRUCTURAL', ('cn', 'ciamLdapName', 'ciamPiiClass'),
             ('ciamExportControlled', 'ciamPurpose', 'ciamRetentionRule', 'ciamLdapOid', 'ciamLdapSyntax',
              'ciamLdapEquality', 'ciamLdapSubstring', 'ciamLdapOrdering', 'ciamLdapSingleValue'),
             'Record describing a user-directory attribute'),
    ClassDef(24, 'ciamConsumer', 'ciamObject', 'STRUCTURAL', ('cn', 'ciamBindDn'),
             ('ciamObservedSource', 'ciamOperationMix', 'ciamSubtreeRead', 'ciamAttrRead', 'ciamUnindexedSearchesPerDay', 'ciamTlsOnly', 'ciamPeakOpsPerSec', 'ciamFirstSeen', 'ciamLastSeen', 'ciamCriticality', 'ciamMigrationStatus'),
             'A client of the user directory'),
    ClassDef(25, 'ciamAci', 'ciamObject', 'STRUCTURAL', ('cn', 'ciamAciTargetDn', 'ciamAciRight', 'ciamAciGrantee'),
             ('ciamAciTargetAttr', 'ciamAciAllAttributes', 'ciamJustification', 'ciamReviewedOn'),
             'Access control instruction'),
    ClassDef(34, 'ciamUserObjectClass', 'ciamObject', 'STRUCTURAL', ('cn', 'ciamLdapName', 'ciamLdapClassKind'),
             ('ciamLdapOid', 'ciamLdapSuperior', 'ciamLdapMust', 'ciamLdapMay', 'ciamPurpose'),
             'Record describing a user-directory object class'),
)

FRAGMENT = fragment(ATTRIBUTES, CLASSES)
