"""Small core records (findings, network, manifest, naming) and the registry that composes domains and adapters."""
import hashlib
import json

import pytest

from opsdir.connectors.plan import render_summary
from opsdir.connectors.registry import ADAPTERS, ref_schemes, schema_fragments, secret_command, sql_files
from opsdir.core.contract import Adapter
from opsdir.core.directory import get
from opsdir.core.environment import env_model
from opsdir.core.findings import Findings, findings, merge_findings, owner_label, responsible
from opsdir.core.manifest import header, manifest
from opsdir.core.naming import SUFFIX, branch
from opsdir.core.network import covers, is_private
from opsdir.core.standard import CORE
from opsdir.domains.governance.domain import display_name, operator


def test_findings_merge_concatenates_each_column_in_order():
    a = findings(blockers=[("A", "a", "o")], ok=["fine"])
    b = findings(actions=[("B", "b", "o", None)], ok=["also"], requests=[("r",)])
    assert merge_findings([a, b]) == Findings((("A", "a", "o"),), (("B", "b", "o", None),), ("fine", "also"), (("r",),))
    assert merge_findings([]) == findings()


def test_owners_come_from_the_directory(estate):
    d = estate["before"]
    owned = get(d, "env=prod,cloud=aws-current,ou=environments,dc=ciam-ops")
    unowned = get(d, "cn=legacy-rptuser,ou=consumers,dc=ciam-ops")
    assert owner_label(d, owned) == "ciam-platform"
    assert owner_label(d, unowned) == "**NO OWNER**"
    assert responsible(d, None, unowned, owned) == "ciam-platform"      # first entry that has an owner
    assert responsible(d, unowned) == "**NO OWNER**"


def test_operator_and_display_names_are_data(estate):
    d = estate["before"]
    assert display_name(get(d, "cn=ciam-platform,ou=owners,dc=ciam-ops")) == "CIAM platform team"
    assert display_name(get(d, "cn=network-security,ou=owners,dc=ciam-ops")) == "network-security"   # no display name
    assert operator(d).dn == "cn=example-aero,ou=owners,dc=ciam-ops"


@pytest.mark.parametrize("cidrs, addr, expected", [
    (["10.20.0.0/16"], "10.20.1.5", True), (["10.20.0.0/16"], "10.20.1.0/24", True),
    (["10.20.1.0/24"], "10.20.0.0/16", False), (["192.0.2.0/24", "198.51.100.7/32"], "198.51.100.7/32", True),
    ([], "10.0.0.1", False)])
def test_covers(cidrs, addr, expected):
    assert covers(cidrs, addr) is expected


def test_is_private():
    assert is_private("10.1.2.3/32") and not is_private("9.9.9.9")


def test_manifest_lists_scope_and_hash_of_every_file(estate):
    m = env_model(estate["before"], "rtx-next/prod", ("backup-target",))
    doc = json.loads(manifest(m, {"b.txt": "neutral"}, {"a.txt": "specific"}))
    assert doc["environment"] == m.dn and doc["provider"] == "azure" and doc["unbound_roles"] == ["backup-target"]
    assert list(doc["files"]) == ["a.txt", "b.txt"]
    assert doc["files"]["b.txt"] == {"scope": "environment-neutral",
                                     "sha256": hashlib.sha256(b"neutral").hexdigest()}
    assert doc["files"]["a.txt"]["scope"] == "environment-specific"
    assert header(m, "what").splitlines()[0] == f"# Generated by opsdir from {m.dn}"


def test_branch_names():
    assert branch("consumers") == f"ou=consumers,{SUFFIX}"
    assert branch("declared", branch("config")) == f"ou=declared,ou=config,{SUFFIX}"


def test_registry_composition():
    assert schema_fragments()[0] is CORE
    files = sql_files()
    assert [f.name for f in files[:2]] == ["001_core.sql", "002_graph.sql"] and files[-1].name == "connectors.sql"
    assert all(f.is_file() for f in files)
    schemes = ref_schemes()
    assert len(schemes) == len(set(schemes)) and {"aws-sm", "vault"} <= set(schemes)
    assert all(a.kind in ("provider", "product", "secret-store") for a in ADAPTERS)


@pytest.mark.parametrize("uri, command", [
    ("aws-sm://prod/ds/root", "aws secretsmanager get-secret-value --secret-id 'prod/ds/root'"),
    ("azkv://kv-prod/ds-root", "az keyvault secret show --vault-name 'kv-prod' --name 'ds-root'"),
    ("vault://secret/ds/root", "vault kv get -field=value 'secret/ds/root'")])
def test_secret_references_resolve_through_the_owning_adapter(uri, command):
    assert secret_command(uri).startswith(command)


def test_unknown_secret_scheme_exits():
    with pytest.raises(SystemExit):
        secret_command("nosuch://x")


def _adapter(renders, neutral_label):
    return Adapter("x", "product", None, (), None, None, (), (), {}, renders, neutral_label)


def test_render_summary_reads_like_a_sentence():
    assert render_summary(()) == "nothing"
    assert render_summary((_adapter("Terraform", None),)) == "Terraform"
    assert render_summary((_adapter("Terraform", None), _adapter("scripts", "DS"), _adapter(None, "PF"))) == \
        "Terraform, scripts, and the environment-neutral DS/PF configuration"
