# Generated by opsdir from env=prod,cloud=standby,ou=environments,dc=ciam-ops
# Google Cloud infrastructure for the CIAM platform
# Do not edit. Change the operations directory (under an approved change) and re-render.

data "google_compute_network" "main" {
  name    = "ciam-standby"
  project = "example-aero-net"
}

data "google_compute_subnetwork" "subnet_am" {
  name    = "ciam-standby-am"
  region  = "us-central1"
  project = "example-aero-net"
}

data "google_compute_subnetwork" "subnet_ds" {
  name    = "ciam-standby-ds"
  region  = "us-central1"
  project = "example-aero-net"
}

data "google_compute_subnetwork" "subnet_edge" {
  name    = "ciam-standby-proxy"
  region  = "us-central1"
  project = "example-aero-net"
}

data "google_compute_subnetwork" "subnet_idm" {
  name    = "ciam-standby-idm"
  region  = "us-central1"
  project = "example-aero-net"
}

data "google_compute_subnetwork" "subnet_ig" {
  name    = "ciam-standby-ig"
  region  = "us-central1"
  project = "example-aero-net"
}

data "google_compute_subnetwork" "subnet_pf" {
  name    = "ciam-standby-pf"
  region  = "us-central1"
  project = "example-aero-net"
}

# The network evaluates its policy first: network_firewall_policy_enforcement_order = BEFORE_CLASSIC_FIREWALL on its network (the landing zone keeps it)

# The network's project is example-aero-net: the policy, its rules and the tag key live there, so the deployer needs rights in it

# Binding the tag values to the instances needs roles/resourcemanager.tagUser on them for the deployer (an access request)

resource "google_compute_network_firewall_policy" "network_policy" {
  name        = "ciam-prod-fw-policy"
  project     = "example-aero-net"
  description = "CIAM firewall policy (standby/prod): rules target the servers' secure tags"
}

resource "google_compute_network_firewall_policy_association" "network_policy" {
  name              = "ciam-prod-fw-policy"
  project           = "example-aero-net"
  attachment_target = data.google_compute_network.main.self_link
  firewall_policy   = google_compute_network_firewall_policy.network_policy.id
}

resource "google_tags_tag_key" "server_role" {
  parent      = "projects/example-aero-net"
  short_name  = "ciam-prod-role"
  description = "CIAM server role (standby/prod): what the firewall policy's rules target. Managed by opsdir"
  purpose     = "GCE_FIREWALL"
  purpose_data = {
    network = "example-aero-net/ciam-standby"
  }
}

resource "google_tags_tag_value" "am" {
  parent      = google_tags_tag_key.server_role.id
  short_name  = "am"
  description = "CIAM am servers (standby/prod)"
}

resource "google_tags_tag_value" "ds" {
  parent      = google_tags_tag_key.server_role.id
  short_name  = "ds"
  description = "CIAM ds servers (standby/prod)"
}

resource "google_tags_tag_value" "idm" {
  parent      = google_tags_tag_key.server_role.id
  short_name  = "idm"
  description = "CIAM idm servers (standby/prod)"
}

resource "google_tags_tag_value" "ig" {
  parent      = google_tags_tag_key.server_role.id
  short_name  = "ig"
  description = "CIAM ig servers (standby/prod)"
}

resource "google_tags_tag_value" "pf_admin" {
  parent      = google_tags_tag_key.server_role.id
  short_name  = "pf-admin"
  description = "CIAM pf-admin servers (standby/prod)"
}

resource "google_tags_tag_value" "pf_engine" {
  parent      = google_tags_tag_key.server_role.id
  short_name  = "pf-engine"
  description = "CIAM pf-engine servers (standby/prod)"
}

resource "google_tags_location_tag_binding" "am_1" {
  parent    = "//compute.googleapis.com/projects/${var.project_id}/zones/us-central1-a/instances/${google_compute_instance.am_1.instance_id}"
  tag_value = google_tags_tag_value.am.id
  location  = "us-central1-a"
}

resource "google_tags_location_tag_binding" "ds_1" {
  parent    = "//compute.googleapis.com/projects/${var.project_id}/zones/us-central1-a/instances/${google_compute_instance.ds_1.instance_id}"
  tag_value = google_tags_tag_value.ds.id
  location  = "us-central1-a"
}

resource "google_tags_location_tag_binding" "ds_2" {
  parent    = "//compute.googleapis.com/projects/${var.project_id}/zones/us-central1-b/instances/${google_compute_instance.ds_2.instance_id}"
  tag_value = google_tags_tag_value.ds.id
  location  = "us-central1-b"
}

resource "google_tags_location_tag_binding" "idm_1" {
  parent    = "//compute.googleapis.com/projects/${var.project_id}/zones/us-central1-a/instances/${google_compute_instance.idm_1.instance_id}"
  tag_value = google_tags_tag_value.idm.id
  location  = "us-central1-a"
}

resource "google_tags_location_tag_binding" "ig_1" {
  parent    = "//compute.googleapis.com/projects/${var.project_id}/zones/us-central1-a/instances/${google_compute_instance.ig_1.instance_id}"
  tag_value = google_tags_tag_value.ig.id
  location  = "us-central1-a"
}

resource "google_tags_location_tag_binding" "pf_admin_1" {
  parent    = "//compute.googleapis.com/projects/${var.project_id}/zones/us-central1-a/instances/${google_compute_instance.pf_admin_1.instance_id}"
  tag_value = google_tags_tag_value.pf_admin.id
  location  = "us-central1-a"
}

resource "google_tags_location_tag_binding" "pf_engine_1" {
  parent    = "//compute.googleapis.com/projects/${var.project_id}/zones/us-central1-a/instances/${google_compute_instance.pf_engine_1.instance_id}"
  tag_value = google_tags_tag_value.pf_engine.id
  location  = "us-central1-a"
}

resource "google_tags_location_tag_binding" "pf_engine_2" {
  parent    = "//compute.googleapis.com/projects/${var.project_id}/zones/us-central1-b/instances/${google_compute_instance.pf_engine_2.instance_id}"
  tag_value = google_tags_tag_value.pf_engine.id
  location  = "us-central1-b"
}

resource "google_compute_network_firewall_policy_rule" "fw_admin" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 150
  direction       = "INGRESS"
  action          = "allow"
  rule_name       = "fw-admin"
  description     = "fw-admin"
  match {
    src_ip_ranges = ["10.70.9.0/28"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["4444"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.ds.id
  }
}

resource "google_compute_network_firewall_policy_rule" "fw_apps_public" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 180
  direction       = "INGRESS"
  action          = "allow"
  rule_name       = "fw-apps-public"
  description     = "fw-apps-public"
  match {
    src_ip_ranges = ["0.0.0.0/0"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["443"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.ig.id
  }
}

resource "google_compute_network_firewall_policy_rule" "fw_customer_portal" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 110
  direction       = "INGRESS"
  action          = "allow"
  rule_name       = "fw-customer-portal"
  description     = "consumer customer-portal-svc"
  match {
    src_ip_ranges = ["10.30.8.0/24"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["1636"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.ds.id
  }
}

resource "google_compute_network_firewall_policy_rule" "fw_idm_sync" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 130
  direction       = "INGRESS"
  action          = "allow"
  rule_name       = "fw-idm-sync"
  description     = "consumer idm-sync"
  match {
    src_ip_ranges = ["10.70.6.0/24"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["1636"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.ds.id
  }
}

resource "google_compute_network_firewall_policy_rule" "fw_login_public" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 170
  direction       = "INGRESS"
  action          = "allow"
  rule_name       = "fw-login-public"
  description     = "fw-login-public"
  match {
    src_ip_ranges = ["0.0.0.0/0"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["443"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.am.id
  }
}

resource "google_compute_network_firewall_policy_rule" "fw_pf_cluster" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 190
  direction       = "INGRESS"
  action          = "allow"
  rule_name       = "fw-pf-cluster"
  description     = "fw-pf-cluster"
  match {
    src_ip_ranges = ["10.70.2.0/24"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["7600", "7700"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.pf_engine.id
  }
}

resource "google_compute_network_firewall_policy_rule" "fw_pf_cluster_admin" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 200
  direction       = "INGRESS"
  action          = "allow"
  rule_name       = "fw-pf-cluster-admin"
  description     = "fw-pf-cluster-admin"
  match {
    src_ip_ranges = ["10.70.2.0/24"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["7600", "7700"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.pf_admin.id
  }
}

resource "google_compute_network_firewall_policy_rule" "fw_pf_ds_svc" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 100
  direction       = "INGRESS"
  action          = "allow"
  rule_name       = "fw-pf-ds-svc"
  description     = "consumer pf-ds-svc"
  match {
    src_ip_ranges = ["10.70.2.0/24"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["1636"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.ds.id
  }
}

resource "google_compute_network_firewall_policy_rule" "fw_replication" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 140
  direction       = "INGRESS"
  action          = "allow"
  rule_name       = "fw-replication"
  description     = "fw-replication"
  match {
    src_ip_ranges = ["10.70.1.0/24", "10.20.0.0/16"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["8989"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.ds.id
  }
}

resource "google_compute_network_firewall_policy_rule" "fw_sso_public" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 160
  direction       = "INGRESS"
  action          = "allow"
  rule_name       = "fw-sso-public"
  description     = "fw-sso-public"
  match {
    src_ip_ranges = ["0.0.0.0/0"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["443"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.pf_engine.id
  }
}

resource "google_compute_network_firewall_policy_rule" "fw_supplier_portal" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 120
  direction       = "INGRESS"
  action          = "allow"
  rule_name       = "fw-supplier-portal"
  description     = "consumer supplier-portal-svc"
  match {
    src_ip_ranges = ["10.31.2.0/24"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["1636"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.ds.id
  }
}

resource "google_service_account" "identity_ds" {
  account_id   = "ciam-standby-ds"
  display_name = "pingds (identity-ds)"
}

resource "google_secret_manager_secret_iam_member" "identity_ds_read_secret_ds_root_password" {
  project   = "example-aero-ciam-standby"
  secret_id = "ds-root-password"
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.identity_ds.email}"
}

resource "google_kms_crypto_key_iam_member" "identity_ds_use_key_disk_encryption" {
  crypto_key_id = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:${google_service_account.identity_ds.email}"
}

resource "google_project_iam_member" "identity_ds_write_logs_audit_logs" {
  # granted on the project: the narrowest scope Google Cloud allows for it
  project = "example-aero-ciam-standby"
  role    = "roles/logging.logWriter"
  member  = "serviceAccount:${google_service_account.identity_ds.email}"
}

resource "google_storage_bucket_iam_member" "identity_ds_write_storage_backup_target" {
  bucket = "example-aero-ciam-standby-ds-backups"
  role   = "roles/storage.objectCreator"
  member = "serviceAccount:${google_service_account.identity_ds.email}"
}

resource "google_service_account" "identity_pf" {
  account_id   = "ciam-standby-pf"
  display_name = "pingfederate (identity-pf)"
}

resource "google_secret_manager_secret_iam_member" "identity_pf_read_secret_pf_admin_password" {
  project   = "example-aero-ciam-standby"
  secret_id = "pf-admin-password"
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.identity_pf.email}"
}

resource "google_secret_manager_secret_iam_member" "identity_pf_read_secret_pf_ds_bind_password" {
  project   = "example-aero-ciam-standby"
  secret_id = "pf-ds-bind-password"
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.identity_pf.email}"
}

resource "google_secret_manager_secret_iam_member" "identity_pf_read_secret_pf_signing_key" {
  project   = "example-aero-ciam-standby"
  secret_id = "pf-signing-key"
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.identity_pf.email}"
}

resource "google_project_iam_member" "identity_pf_write_logs_audit_logs" {
  # granted on the project: the narrowest scope Google Cloud allows for it
  project = "example-aero-ciam-standby"
  role    = "roles/logging.logWriter"
  member  = "serviceAccount:${google_service_account.identity_pf.email}"
}

resource "google_compute_instance" "am_1" {
  name         = "am-1"
  machine_type = "n2-standard-2"
  zone         = "us-central1-a"
  hostname     = "am-1.gcp.internal.example-aero.test"
  tags         = ["ciam-prod-am"]
  boot_disk {
    initialize_params {
      image = "projects/example-aero-images/global/images/pingam-7-5-1-rhel9"
    }
    kms_key_self_link = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  network_interface {
    subnetwork = data.google_compute_subnetwork.subnet_am.self_link
    network_ip = "10.70.3.21"
  }
  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }
  metadata = {
    enable-oslogin = "TRUE"
    ciam-role      = "am"
    ciam-product   = "PingAM 7.5.1"
  }
  labels = {
    role       = "am"
    product    = "pingam-7-5-1"
    managed_by = "opsdir"
  }
}

resource "google_compute_instance" "ds_1" {
  name         = "ds-1"
  machine_type = "n2-standard-4"
  zone         = "us-central1-a"
  hostname     = "ds-1.gcp.internal.example-aero.test"
  tags         = ["ciam-prod-ds"]
  boot_disk {
    initialize_params {
      image = "projects/example-aero-images/global/images/pingds-7-5-1-rhel9"
    }
    kms_key_self_link = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  network_interface {
    subnetwork = data.google_compute_subnetwork.subnet_ds.self_link
    network_ip = "10.70.1.11"
  }
  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }
  service_account {
    email  = google_service_account.identity_ds.email
    scopes = ["cloud-platform"]
  }
  metadata = {
    enable-oslogin = "TRUE"
    ciam-role      = "ds"
    ciam-product   = "PingDS 7.5.1"
  }
  labels = {
    role       = "ds"
    product    = "pingds-7-5-1"
    managed_by = "opsdir"
  }
}

# ds-1 mounts vol-ds-data at /opt/ds/db (its own configuration, not Terraform)

resource "google_compute_disk" "ds_1_vol_ds_data" {
  name = "ds-1-vol-ds-data"
  zone = "us-central1-a"
  type = "pd-ssd"
  size = 500
  disk_encryption_key {
    kms_key_self_link = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  labels = {
    volume          = "vol-ds-data"
    role            = "volume-ds-data"
    server          = "ds-1"
    snapshot_policy = "snapshots-daily"
    managed_by      = "opsdir"
  }
}

resource "google_compute_attached_disk" "ds_1_vol_ds_data" {
  disk        = google_compute_disk.ds_1_vol_ds_data.id
  instance    = google_compute_instance.ds_1.id
  device_name = "vol-ds-data"
}

resource "google_compute_disk_resource_policy_attachment" "ds_1_vol_ds_data" {
  name = google_compute_resource_policy.snapshots_daily.name
  disk = google_compute_disk.ds_1_vol_ds_data.name
  zone = "us-central1-a"
}

resource "google_compute_instance" "ds_2" {
  name         = "ds-2"
  machine_type = "n2-standard-4"
  zone         = "us-central1-b"
  hostname     = "ds-2.gcp.internal.example-aero.test"
  tags         = ["ciam-prod-ds"]
  boot_disk {
    initialize_params {
      image = "projects/example-aero-images/global/images/pingds-7-5-1-rhel9"
    }
    kms_key_self_link = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  network_interface {
    subnetwork = data.google_compute_subnetwork.subnet_ds.self_link
    network_ip = "10.70.1.12"
  }
  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }
  service_account {
    email  = google_service_account.identity_ds.email
    scopes = ["cloud-platform"]
  }
  metadata = {
    enable-oslogin = "TRUE"
    ciam-role      = "ds"
    ciam-product   = "PingDS 7.5.1"
  }
  labels = {
    role       = "ds"
    product    = "pingds-7-5-1"
    managed_by = "opsdir"
  }
}

# ds-2 mounts vol-ds-data at /opt/ds/db (its own configuration, not Terraform)

resource "google_compute_disk" "ds_2_vol_ds_data" {
  name = "ds-2-vol-ds-data"
  zone = "us-central1-b"
  type = "pd-ssd"
  size = 500
  disk_encryption_key {
    kms_key_self_link = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  labels = {
    volume          = "vol-ds-data"
    role            = "volume-ds-data"
    server          = "ds-2"
    snapshot_policy = "snapshots-daily"
    managed_by      = "opsdir"
  }
}

resource "google_compute_attached_disk" "ds_2_vol_ds_data" {
  disk        = google_compute_disk.ds_2_vol_ds_data.id
  instance    = google_compute_instance.ds_2.id
  device_name = "vol-ds-data"
}

resource "google_compute_disk_resource_policy_attachment" "ds_2_vol_ds_data" {
  name = google_compute_resource_policy.snapshots_daily.name
  disk = google_compute_disk.ds_2_vol_ds_data.name
  zone = "us-central1-b"
}

resource "google_compute_instance" "idm_1" {
  name         = "idm-1"
  machine_type = "n2-standard-2"
  zone         = "us-central1-a"
  hostname     = "idm-1.gcp.internal.example-aero.test"
  tags         = ["ciam-prod-idm"]
  boot_disk {
    initialize_params {
      image = "projects/example-aero-images/global/images/pingidm-7-5-0-rhel9"
    }
    kms_key_self_link = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  network_interface {
    subnetwork = data.google_compute_subnetwork.subnet_idm.self_link
    network_ip = "10.70.6.21"
  }
  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }
  metadata = {
    enable-oslogin = "TRUE"
    ciam-role      = "idm"
    ciam-product   = "PingIDM 7.5.0"
  }
  labels = {
    role       = "idm"
    product    = "pingidm-7-5-0"
    managed_by = "opsdir"
  }
}

resource "google_compute_instance" "ig_1" {
  name         = "ig-1"
  machine_type = "n2-standard-2"
  zone         = "us-central1-a"
  hostname     = "ig-1.gcp.internal.example-aero.test"
  tags         = ["ciam-prod-ig"]
  boot_disk {
    initialize_params {
      image = "projects/example-aero-images/global/images/pinggateway-2024-11-0-rhel9"
    }
    kms_key_self_link = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  network_interface {
    subnetwork = data.google_compute_subnetwork.subnet_ig.self_link
    network_ip = "10.70.10.21"
  }
  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }
  metadata = {
    enable-oslogin = "TRUE"
    ciam-role      = "ig"
    ciam-product   = "PingGateway 2024.11.0"
  }
  labels = {
    role       = "ig"
    product    = "pinggateway-2024-11-0"
    managed_by = "opsdir"
  }
}

resource "google_compute_instance" "pf_admin_1" {
  name         = "pf-admin-1"
  machine_type = "n2-standard-2"
  zone         = "us-central1-a"
  hostname     = "pf-admin-1.gcp.internal.example-aero.test"
  tags         = ["ciam-prod-pf-admin"]
  boot_disk {
    initialize_params {
      image = "projects/example-aero-images/global/images/pingfederate-12-1-4-rhel9"
    }
    kms_key_self_link = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  network_interface {
    subnetwork = data.google_compute_subnetwork.subnet_pf.self_link
    network_ip = "10.70.2.10"
  }
  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }
  metadata = {
    enable-oslogin = "TRUE"
    ciam-role      = "pf-admin"
    ciam-product   = "PingFederate 12.1.4"
  }
  labels = {
    role       = "pf-admin"
    product    = "pingfederate-12-1-4"
    managed_by = "opsdir"
  }
}

resource "google_compute_instance" "pf_engine_1" {
  name         = "pf-engine-1"
  machine_type = "n2-standard-2"
  zone         = "us-central1-a"
  hostname     = "pf-engine-1.gcp.internal.example-aero.test"
  tags         = ["ciam-prod-pf-engine"]
  boot_disk {
    initialize_params {
      image = "projects/example-aero-images/global/images/pingfederate-12-1-4-rhel9"
    }
    kms_key_self_link = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  network_interface {
    subnetwork = data.google_compute_subnetwork.subnet_pf.self_link
    network_ip = "10.70.2.21"
  }
  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }
  service_account {
    email  = google_service_account.identity_pf.email
    scopes = ["cloud-platform"]
  }
  metadata = {
    enable-oslogin = "TRUE"
    ciam-role      = "pf-engine"
    ciam-product   = "PingFederate 12.1.4"
  }
  labels = {
    role       = "pf-engine"
    product    = "pingfederate-12-1-4"
    managed_by = "opsdir"
  }
}

resource "google_compute_instance" "pf_engine_2" {
  name         = "pf-engine-2"
  machine_type = "n2-standard-2"
  zone         = "us-central1-b"
  hostname     = "pf-engine-2.gcp.internal.example-aero.test"
  tags         = ["ciam-prod-pf-engine"]
  boot_disk {
    initialize_params {
      image = "projects/example-aero-images/global/images/pingfederate-12-1-4-rhel9"
    }
    kms_key_self_link = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  network_interface {
    subnetwork = data.google_compute_subnetwork.subnet_pf.self_link
    network_ip = "10.70.2.22"
  }
  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }
  service_account {
    email  = google_service_account.identity_pf.email
    scopes = ["cloud-platform"]
  }
  metadata = {
    enable-oslogin = "TRUE"
    ciam-role      = "pf-engine"
    ciam-product   = "PingFederate 12.1.4"
  }
  labels = {
    role       = "pf-engine"
    product    = "pingfederate-12-1-4"
    managed_by = "opsdir"
  }
}

resource "google_compute_resource_policy" "snapshots_daily" {
  name        = "ciam-prod-snapshots-daily"
  region      = var.region
  description = "CIAM snapshots snapshots-daily (standby/prod)"
  snapshot_schedule_policy {
    schedule {
      daily_schedule {
        days_in_cycle = 1
        start_time    = "03:00"
      }
    }
    retention_policy {
      max_retention_days    = 7
      on_source_disk_delete = "KEEP_AUTO_SNAPSHOTS"
    }
    snapshot_properties {
      storage_locations = ["us-east1"]
      guest_flush       = false
      labels = {
        policy     = "snapshots-daily"
        role       = "snapshots-daily"
        managed_by = "opsdir"
      }
    }
  }
}

import {
  to = google_compute_resource_policy.snapshots_daily
  id = "projects/example-aero-ciam-standby/regions/us-central1/resourcePolicies/ciam-prod-snapshots-daily"
}

resource "google_backup_dr_backup_vault" "ciam_backups" {
  location                                   = "us-east1"
  backup_vault_id                            = "ciam-prod-ciam-backups"
  backup_minimum_enforced_retention_duration = "1209600s"
  labels = {
    name       = "ciam-backups"
    role       = "backup-vault"
    managed_by = "opsdir"
  }
}

import {
  to = google_backup_dr_backup_vault.ciam_backups
  id = "projects/example-aero-ciam-standby/locations/us-east1/backupVaults/ciam-prod-ciam-backups"
}

resource "google_backup_dr_backup_plan" "backup_daily" {
  location       = var.region
  backup_plan_id = "backup-daily"
  resource_type  = "compute.googleapis.com/Disk"
  backup_vault   = google_backup_dr_backup_vault.ciam_backups.id
  backup_rules {
    rule_id               = "ciam"
    backup_retention_days = 35
    standard_schedule {
      recurrence_type = "DAILY"
      time_zone       = "UTC"
      backup_window {
        start_hour_of_day = 5
        end_hour_of_day   = 11
      }
    }
  }
}

resource "google_backup_dr_backup_plan_association" "backup_daily_ds_1_vol_ds_data" {
  location                   = var.region
  backup_plan_association_id = "ds-1-vol-ds-data"
  resource                   = google_compute_disk.ds_1_vol_ds_data.id
  resource_type              = "compute.googleapis.com/Disk"
  backup_plan                = google_backup_dr_backup_plan.backup_daily.name
}

resource "google_backup_dr_backup_plan_association" "backup_daily_ds_2_vol_ds_data" {
  location                   = var.region
  backup_plan_association_id = "ds-2-vol-ds-data"
  resource                   = google_compute_disk.ds_2_vol_ds_data.id
  resource_type              = "compute.googleapis.com/Disk"
  backup_plan                = google_backup_dr_backup_plan.backup_daily.name
}

import {
  to = google_backup_dr_backup_plan.backup_daily
  id = "projects/example-aero-ciam-standby/locations/us-central1/backupPlans/backup-daily"
}

data "google_compute_address" "svc_apps" {
  name   = "ciam-standby-apps"
  region = var.region
}

resource "google_compute_instance_group" "svc_apps_us_central1_a" {
  name      = "ciam-prod-svc-apps-us-central1-a"
  zone      = "us-central1-a"
  instances = [google_compute_instance.ig_1.self_link]
  named_port {
    name = "ciam"
    port = 443
  }
}

resource "google_compute_region_health_check" "svc_apps" {
  name   = "ciam-prod-svc-apps"
  region = var.region
  tcp_health_check {
    port = 443
  }
}

resource "google_compute_network_firewall_policy_rule" "svc_apps_health_checks" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 70000
  direction       = "INGRESS"
  action          = "allow"
  description     = "Google Cloud health checks for svc-apps"
  match {
    src_ip_ranges = ["35.191.0.0/16", "209.85.152.0/22", "209.85.204.0/22"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["443"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.ig.id
  }
}

resource "google_compute_region_backend_service" "svc_apps" {
  name                  = "ciam-prod-svc-apps"
  region                = var.region
  load_balancing_scheme = "EXTERNAL"
  protocol              = "TCP"
  port_name             = "ciam"
  health_checks         = [google_compute_region_health_check.svc_apps.id]
  backend {
    group           = google_compute_instance_group.svc_apps_us_central1_a.self_link
    balancing_mode  = "CONNECTION"
    capacity_scaler = 1.0
  }
}

resource "google_compute_forwarding_rule" "svc_apps" {
  name                  = "ciam-prod-svc-apps"
  region                = var.region
  load_balancing_scheme = "EXTERNAL"
  ip_protocol           = "TCP"
  ports                 = ["443"]
  ip_address            = data.google_compute_address.svc_apps.address
  backend_service       = google_compute_region_backend_service.svc_apps.id
  labels = {
    service    = "apps-example-aero-test"
    managed_by = "opsdir"
  }
}

resource "google_dns_record_set" "svc_apps" {
  managed_zone = "example-aero-public"
  name         = "apps.example-aero.test."
  type         = "A"
  ttl          = 300
  rrdatas      = [google_compute_forwarding_rule.svc_apps.ip_address]
}

resource "google_compute_instance_group" "svc_ldaps_us_central1_a" {
  name      = "ciam-prod-svc-ldaps-us-central1-a"
  zone      = "us-central1-a"
  instances = [google_compute_instance.ds_1.self_link]
}

resource "google_compute_instance_group" "svc_ldaps_us_central1_b" {
  name      = "ciam-prod-svc-ldaps-us-central1-b"
  zone      = "us-central1-b"
  instances = [google_compute_instance.ds_2.self_link]
}

resource "google_compute_region_health_check" "svc_ldaps" {
  name   = "ciam-prod-svc-ldaps"
  region = var.region
  tcp_health_check {
    port = 1636
  }
}

resource "google_compute_network_firewall_policy_rule" "svc_ldaps_health_checks" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 70001
  direction       = "INGRESS"
  action          = "allow"
  description     = "Google Cloud health checks for svc-ldaps"
  match {
    src_ip_ranges = ["35.191.0.0/16"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["1636"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.ds.id
  }
}

resource "google_compute_region_backend_service" "svc_ldaps" {
  name                  = "ciam-prod-svc-ldaps"
  region                = var.region
  load_balancing_scheme = "INTERNAL"
  protocol              = "TCP"
  health_checks         = [google_compute_region_health_check.svc_ldaps.id]
  backend {
    group          = google_compute_instance_group.svc_ldaps_us_central1_a.self_link
    balancing_mode = "CONNECTION"
  }
  backend {
    group          = google_compute_instance_group.svc_ldaps_us_central1_b.self_link
    balancing_mode = "CONNECTION"
  }
}

resource "google_compute_forwarding_rule" "svc_ldaps" {
  name                  = "ciam-prod-svc-ldaps"
  region                = var.region
  load_balancing_scheme = "INTERNAL"
  ip_protocol           = "TCP"
  ports                 = ["1636"]
  ip_address            = "10.70.1.100"
  backend_service       = google_compute_region_backend_service.svc_ldaps.id
  network               = data.google_compute_network.main.self_link
  subnetwork            = data.google_compute_subnetwork.subnet_ds.self_link
  labels = {
    service    = "ldap-id-example-aero-test"
    managed_by = "opsdir"
  }
}

resource "google_dns_record_set" "svc_ldaps" {
  managed_zone = "ciam-standby-private"
  name         = "ldap.id.example-aero.test."
  type         = "A"
  ttl          = 300
  rrdatas      = [google_compute_forwarding_rule.svc_ldaps.ip_address]
}

resource "google_compute_instance_group" "svc_login_us_central1_a" {
  name      = "ciam-prod-svc-login-us-central1-a"
  zone      = "us-central1-a"
  instances = [google_compute_instance.am_1.self_link]
  named_port {
    name = "ciam"
    port = 443
  }
}

data "google_compute_address" "svc_login" {
  name   = "ciam-standby-login"
  region = var.region
}

resource "google_compute_region_ssl_policy" "svc_login" {
  name            = "ciam-prod-svc-login"
  region          = var.region
  profile         = "MODERN"
  min_tls_version = "TLS_1_2"
}

resource "google_compute_region_health_check" "svc_login" {
  name   = "ciam-prod-svc-login"
  region = var.region
  https_health_check {
    port         = 443
    request_path = "/am/json/health/ready"
  }
}

resource "google_compute_network_firewall_policy_rule" "svc_login_proxies" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 75002
  direction       = "INGRESS"
  action          = "allow"
  description     = "Load balancer proxies for svc-login"
  match {
    src_ip_ranges = ["10.70.250.0/23"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["443"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.am.id
  }
}

resource "google_compute_network_firewall_policy_rule" "svc_login_health_checks" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 70002
  direction       = "INGRESS"
  action          = "allow"
  description     = "Google Cloud health checks for svc-login"
  match {
    src_ip_ranges = ["35.191.0.0/16", "130.211.0.0/22"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["443"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.am.id
  }
}

# not rendered: bot-control needs reCAPTCHA keys (bot management)

resource "google_compute_region_security_policy" "svc_login" {
  name   = "ciam-prod-svc_login"
  region = var.region
  type   = "CLOUD_ARMOR"
}

resource "google_compute_region_security_policy_rule" "svc_login_1000" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_login.name
  priority        = 1000
  action          = "throttle"
  match {
    expr {
      expression = "request.path.matches('^/am/json/realms/[^?#]+/authenticate$')"
    }
  }
  description = "rate-login"
  rate_limit_options {
    conform_action = "allow"
    exceed_action  = "deny(429)"
    enforce_on_key = "IP"
    rate_limit_threshold {
      count        = 300
      interval_sec = 300
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_login_1010" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_login.name
  priority        = 1010
  action          = "throttle"
  match {
    expr {
      expression = "request.path.matches('^/am/oauth2/access_token$') || request.path.matches('^/am/oauth2/realms/[^?#]+/access_token$')"
    }
  }
  description = "rate-token"
  rate_limit_options {
    conform_action = "allow"
    exceed_action  = "deny(429)"
    enforce_on_key = "IP"
    rate_limit_threshold {
      count        = 600
      interval_sec = 300
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_login_1020" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_login.name
  priority        = 1020
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('sqli-v33-stable')"
    }
  }
  # exclusions apply on every path, not only the endpoint kind named
  preconfigured_waf_config {
    exclusion {
      target_rule_set = "sqli-v33-stable"
      request_query_param {
        operator = "EQUALS"
        value    = "SAMLResponse"
      }
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_login_1030" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_login.name
  priority        = 1030
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('xss-v33-stable')"
    }
  }
  # exclusions apply on every path, not only the endpoint kind named
  preconfigured_waf_config {
    exclusion {
      target_rule_set = "xss-v33-stable"
      request_query_param {
        operator = "EQUALS"
        value    = "SAMLResponse"
      }
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_login_1040" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_login.name
  priority        = 1040
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('lfi-v33-stable')"
    }
  }
  # exclusions apply on every path, not only the endpoint kind named
  preconfigured_waf_config {
    exclusion {
      target_rule_set = "lfi-v33-stable"
      request_query_param {
        operator = "EQUALS"
        value    = "SAMLResponse"
      }
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_login_1050" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_login.name
  priority        = 1050
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('rfi-v33-stable')"
    }
  }
  # exclusions apply on every path, not only the endpoint kind named
  preconfigured_waf_config {
    exclusion {
      target_rule_set = "rfi-v33-stable"
      request_query_param {
        operator = "EQUALS"
        value    = "SAMLResponse"
      }
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_login_1060" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_login.name
  priority        = 1060
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('rce-v33-stable')"
    }
  }
  # exclusions apply on every path, not only the endpoint kind named
  preconfigured_waf_config {
    exclusion {
      target_rule_set = "rce-v33-stable"
      request_query_param {
        operator = "EQUALS"
        value    = "SAMLResponse"
      }
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_login_1070" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_login.name
  priority        = 1070
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('methodenforcement-v33-stable')"
    }
  }
  # exclusions apply on every path, not only the endpoint kind named
  preconfigured_waf_config {
    exclusion {
      target_rule_set = "methodenforcement-v33-stable"
      request_query_param {
        operator = "EQUALS"
        value    = "SAMLResponse"
      }
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_login_1080" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_login.name
  priority        = 1080
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('scannerdetection-v33-stable')"
    }
  }
  # exclusions apply on every path, not only the endpoint kind named
  preconfigured_waf_config {
    exclusion {
      target_rule_set = "scannerdetection-v33-stable"
      request_query_param {
        operator = "EQUALS"
        value    = "SAMLResponse"
      }
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_login_1090" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_login.name
  priority        = 1090
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('protocolattack-v33-stable')"
    }
  }
  # exclusions apply on every path, not only the endpoint kind named
  preconfigured_waf_config {
    exclusion {
      target_rule_set = "protocolattack-v33-stable"
      request_query_param {
        operator = "EQUALS"
        value    = "SAMLResponse"
      }
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_login_1100" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_login.name
  priority        = 1100
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('sessionfixation-v33-stable')"
    }
  }
  # exclusions apply on every path, not only the endpoint kind named
  preconfigured_waf_config {
    exclusion {
      target_rule_set = "sessionfixation-v33-stable"
      request_query_param {
        operator = "EQUALS"
        value    = "SAMLResponse"
      }
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_login_1110" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_login.name
  priority        = 1110
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('cve-canary')"
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_login_1120" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_login.name
  priority        = 1120
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('java-v33-stable')"
    }
  }
}

resource "google_compute_region_backend_service" "svc_login" {
  name                    = "ciam-prod-svc-login"
  region                  = var.region
  load_balancing_scheme   = "EXTERNAL_MANAGED"
  protocol                = "HTTPS"
  port_name               = "ciam"
  health_checks           = [google_compute_region_health_check.svc_login.id]
  session_affinity        = "GENERATED_COOKIE"
  affinity_cookie_ttl_sec = 3600
  security_policy         = google_compute_region_security_policy.svc_login.self_link
  backend {
    group           = google_compute_instance_group.svc_login_us_central1_a.self_link
    balancing_mode  = "UTILIZATION"
    capacity_scaler = 1.0
  }
}

resource "google_compute_region_url_map" "svc_login" {
  name            = "ciam-prod-svc-login"
  region          = var.region
  default_service = google_compute_region_backend_service.svc_login.id
}

resource "google_compute_region_target_https_proxy" "svc_login" {
  name    = "ciam-prod-svc-login"
  region  = var.region
  url_map = google_compute_region_url_map.svc_login.id
  # UNBOUND: no Certificate Manager certificate holds this service's certificate here
  ssl_policy = google_compute_region_ssl_policy.svc_login.id
}

resource "google_compute_forwarding_rule" "svc_login" {
  name                  = "ciam-prod-svc-login"
  region                = var.region
  load_balancing_scheme = "EXTERNAL_MANAGED"
  ip_protocol           = "TCP"
  port_range            = "443"
  ip_address            = data.google_compute_address.svc_login.address
  network               = data.google_compute_network.main.self_link
  network_tier          = "STANDARD"
  target                = google_compute_region_target_https_proxy.svc_login.id
  labels = {
    service    = "login-example-aero-test"
    managed_by = "opsdir"
  }
}

resource "google_dns_record_set" "svc_login" {
  managed_zone = "example-aero-public"
  name         = "login.example-aero.test."
  type         = "A"
  ttl          = 300
  rrdatas      = [google_compute_forwarding_rule.svc_login.ip_address]
}

resource "google_compute_instance_group" "svc_sso_us_central1_a" {
  name      = "ciam-prod-svc-sso-us-central1-a"
  zone      = "us-central1-a"
  instances = [google_compute_instance.pf_engine_1.self_link]
  named_port {
    name = "ciam"
    port = 443
  }
}

resource "google_compute_instance_group" "svc_sso_us_central1_b" {
  name      = "ciam-prod-svc-sso-us-central1-b"
  zone      = "us-central1-b"
  instances = [google_compute_instance.pf_engine_2.self_link]
  named_port {
    name = "ciam"
    port = 443
  }
}

data "google_compute_address" "svc_sso" {
  name   = "ciam-standby-sso"
  region = var.region
}

resource "google_compute_region_ssl_policy" "svc_sso" {
  name            = "ciam-prod-svc-sso"
  region          = var.region
  profile         = "MODERN"
  min_tls_version = "TLS_1_2"
}

resource "google_compute_region_health_check" "svc_sso" {
  name   = "ciam-prod-svc-sso"
  region = var.region
  https_health_check {
    port         = 443
    request_path = "/pf/heartbeat.ping"
  }
}

resource "google_compute_network_firewall_policy_rule" "svc_sso_proxies" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 75003
  direction       = "INGRESS"
  action          = "allow"
  description     = "Load balancer proxies for svc-sso"
  match {
    src_ip_ranges = ["10.70.250.0/23"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["443"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.pf_engine.id
  }
}

resource "google_compute_network_firewall_policy_rule" "svc_sso_health_checks" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 70003
  direction       = "INGRESS"
  action          = "allow"
  description     = "Google Cloud health checks for svc-sso"
  match {
    src_ip_ranges = ["35.191.0.0/16", "130.211.0.0/22"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["443"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.pf_engine.id
  }
}

# not rendered: bot-control needs reCAPTCHA keys (bot management)

resource "google_compute_region_security_policy" "svc_sso" {
  name   = "ciam-prod-svc_sso"
  region = var.region
  type   = "CLOUD_ARMOR"
}

resource "google_compute_region_security_policy_rule" "svc_sso_1000" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_sso.name
  priority        = 1000
  action          = "throttle"
  match {
    expr {
      expression = "request.path.matches('^/as/authorization\\.oauth2$') || request.path.matches('^/idp/SSO\\.saml2$')"
    }
  }
  description = "rate-login"
  rate_limit_options {
    conform_action = "allow"
    exceed_action  = "deny(429)"
    enforce_on_key = "IP"
    rate_limit_threshold {
      count        = 300
      interval_sec = 300
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_sso_1010" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_sso.name
  priority        = 1010
  action          = "throttle"
  match {
    expr {
      expression = "request.path.matches('^/as/token\\.oauth2$')"
    }
  }
  description = "rate-token"
  rate_limit_options {
    conform_action = "allow"
    exceed_action  = "deny(429)"
    enforce_on_key = "IP"
    rate_limit_threshold {
      count        = 600
      interval_sec = 300
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_sso_1020" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_sso.name
  priority        = 1020
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('sqli-v33-stable')"
    }
  }
  # exclusions apply on every path, not only the endpoint kind named
  preconfigured_waf_config {
    exclusion {
      target_rule_set = "sqli-v33-stable"
      request_query_param {
        operator = "EQUALS"
        value    = "SAMLResponse"
      }
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_sso_1030" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_sso.name
  priority        = 1030
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('xss-v33-stable')"
    }
  }
  # exclusions apply on every path, not only the endpoint kind named
  preconfigured_waf_config {
    exclusion {
      target_rule_set = "xss-v33-stable"
      request_query_param {
        operator = "EQUALS"
        value    = "SAMLResponse"
      }
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_sso_1040" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_sso.name
  priority        = 1040
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('lfi-v33-stable')"
    }
  }
  # exclusions apply on every path, not only the endpoint kind named
  preconfigured_waf_config {
    exclusion {
      target_rule_set = "lfi-v33-stable"
      request_query_param {
        operator = "EQUALS"
        value    = "SAMLResponse"
      }
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_sso_1050" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_sso.name
  priority        = 1050
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('rfi-v33-stable')"
    }
  }
  # exclusions apply on every path, not only the endpoint kind named
  preconfigured_waf_config {
    exclusion {
      target_rule_set = "rfi-v33-stable"
      request_query_param {
        operator = "EQUALS"
        value    = "SAMLResponse"
      }
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_sso_1060" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_sso.name
  priority        = 1060
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('rce-v33-stable')"
    }
  }
  # exclusions apply on every path, not only the endpoint kind named
  preconfigured_waf_config {
    exclusion {
      target_rule_set = "rce-v33-stable"
      request_query_param {
        operator = "EQUALS"
        value    = "SAMLResponse"
      }
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_sso_1070" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_sso.name
  priority        = 1070
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('methodenforcement-v33-stable')"
    }
  }
  # exclusions apply on every path, not only the endpoint kind named
  preconfigured_waf_config {
    exclusion {
      target_rule_set = "methodenforcement-v33-stable"
      request_query_param {
        operator = "EQUALS"
        value    = "SAMLResponse"
      }
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_sso_1080" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_sso.name
  priority        = 1080
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('scannerdetection-v33-stable')"
    }
  }
  # exclusions apply on every path, not only the endpoint kind named
  preconfigured_waf_config {
    exclusion {
      target_rule_set = "scannerdetection-v33-stable"
      request_query_param {
        operator = "EQUALS"
        value    = "SAMLResponse"
      }
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_sso_1090" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_sso.name
  priority        = 1090
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('protocolattack-v33-stable')"
    }
  }
  # exclusions apply on every path, not only the endpoint kind named
  preconfigured_waf_config {
    exclusion {
      target_rule_set = "protocolattack-v33-stable"
      request_query_param {
        operator = "EQUALS"
        value    = "SAMLResponse"
      }
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_sso_1100" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_sso.name
  priority        = 1100
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('sessionfixation-v33-stable')"
    }
  }
  # exclusions apply on every path, not only the endpoint kind named
  preconfigured_waf_config {
    exclusion {
      target_rule_set = "sessionfixation-v33-stable"
      request_query_param {
        operator = "EQUALS"
        value    = "SAMLResponse"
      }
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_sso_1110" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_sso.name
  priority        = 1110
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('cve-canary')"
    }
  }
}

resource "google_compute_region_security_policy_rule" "svc_sso_1120" {
  region          = var.region
  security_policy = google_compute_region_security_policy.svc_sso.name
  priority        = 1120
  action          = "deny(403)"
  match {
    expr {
      expression = "evaluatePreconfiguredWaf('java-v33-stable')"
    }
  }
}

resource "google_compute_region_backend_service" "svc_sso" {
  name                    = "ciam-prod-svc-sso"
  region                  = var.region
  load_balancing_scheme   = "EXTERNAL_MANAGED"
  protocol                = "HTTPS"
  port_name               = "ciam"
  health_checks           = [google_compute_region_health_check.svc_sso.id]
  session_affinity        = "GENERATED_COOKIE"
  affinity_cookie_ttl_sec = 3600
  security_policy         = google_compute_region_security_policy.svc_sso.self_link
  backend {
    group           = google_compute_instance_group.svc_sso_us_central1_a.self_link
    balancing_mode  = "UTILIZATION"
    capacity_scaler = 1.0
  }
  backend {
    group           = google_compute_instance_group.svc_sso_us_central1_b.self_link
    balancing_mode  = "UTILIZATION"
    capacity_scaler = 1.0
  }
}

resource "google_compute_region_url_map" "svc_sso" {
  name            = "ciam-prod-svc-sso"
  region          = var.region
  default_service = google_compute_region_backend_service.svc_sso.id
}

resource "google_compute_region_target_https_proxy" "svc_sso" {
  name                             = "ciam-prod-svc-sso"
  region                           = var.region
  url_map                          = google_compute_region_url_map.svc_sso.id
  certificate_manager_certificates = ["projects/example-aero-ciam-standby/locations/us-central1/certificates/sso-tls-2026"]
  ssl_policy                       = google_compute_region_ssl_policy.svc_sso.id
}

resource "google_compute_forwarding_rule" "svc_sso" {
  name                  = "ciam-prod-svc-sso"
  region                = var.region
  load_balancing_scheme = "EXTERNAL_MANAGED"
  ip_protocol           = "TCP"
  port_range            = "443"
  ip_address            = data.google_compute_address.svc_sso.address
  network               = data.google_compute_network.main.self_link
  network_tier          = "STANDARD"
  target                = google_compute_region_target_https_proxy.svc_sso.id
  labels = {
    service    = "sso-example-aero-test"
    managed_by = "opsdir"
  }
}

resource "google_dns_record_set" "svc_sso" {
  managed_zone = "example-aero-public"
  name         = "sso.example-aero.test."
  type         = "A"
  ttl          = 300
  rrdatas      = [google_compute_forwarding_rule.svc_sso.ip_address]
}

# Private endpoint 'psa-services' (database) is kept by network-security; rendered in their root, not here.

# private DNS: the landing zone's private googleapis.com zone answers 10.70.255.5 for 'psc-apis'

resource "google_compute_global_address" "psc_apis" {
  name         = "ciam-prod-psc-apis"
  project      = "example-aero-net"
  purpose      = "PRIVATE_SERVICE_CONNECT"
  address_type = "INTERNAL"
  network      = data.google_compute_network.main.self_link
  address      = "10.70.255.5"
  labels = {
    role       = "private-apis"
    managed_by = "opsdir"
  }
}

resource "google_compute_global_forwarding_rule" "psc_apis" {
  name                  = "pscapis"
  project               = "example-aero-net"
  target                = "all-apis"
  network               = data.google_compute_network.main.self_link
  ip_address            = google_compute_global_address.psc_apis.id
  load_balancing_scheme = ""
}

resource "google_compute_network_firewall_policy_rule" "egress_firewall_sites_80" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 80000
  direction       = "EGRESS"
  action          = "allow"
  description     = "Sites the CIAM platform reaches on 80 (egress-firewall)"
  match {
    dest_fqdns = ["ocsp.example-ca.test", "crl.example-ca.test"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["80"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.am.id
  }
  target_secure_tags {
    name = google_tags_tag_value.ds.id
  }
  target_secure_tags {
    name = google_tags_tag_value.idm.id
  }
  target_secure_tags {
    name = google_tags_tag_value.ig.id
  }
  target_secure_tags {
    name = google_tags_tag_value.pf_admin.id
  }
  target_secure_tags {
    name = google_tags_tag_value.pf_engine.id
  }
}

resource "google_compute_network_firewall_policy_rule" "egress_firewall_sites_443" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 80001
  direction       = "EGRESS"
  action          = "allow"
  description     = "Sites the CIAM platform reaches on 443 (egress-firewall)"
  match {
    dest_fqdns = ["metadata.skyline-air.test", "sso.harbor-mro.test"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["443"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.am.id
  }
  target_secure_tags {
    name = google_tags_tag_value.ds.id
  }
  target_secure_tags {
    name = google_tags_tag_value.idm.id
  }
  target_secure_tags {
    name = google_tags_tag_value.ig.id
  }
  target_secure_tags {
    name = google_tags_tag_value.pf_admin.id
  }
  target_secure_tags {
    name = google_tags_tag_value.pf_engine.id
  }
}

resource "google_compute_network_firewall_policy_rule" "egress_firewall_sites_587" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 80002
  direction       = "EGRESS"
  action          = "allow"
  description     = "Sites the CIAM platform reaches on 587 (egress-firewall)"
  match {
    dest_fqdns = ["email-smtp.us-east-1.amazonaws.com"]
    layer4_configs {
      ip_protocol = "tcp"
      ports       = ["587"]
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.am.id
  }
  target_secure_tags {
    name = google_tags_tag_value.ds.id
  }
  target_secure_tags {
    name = google_tags_tag_value.idm.id
  }
  target_secure_tags {
    name = google_tags_tag_value.ig.id
  }
  target_secure_tags {
    name = google_tags_tag_value.pf_admin.id
  }
  target_secure_tags {
    name = google_tags_tag_value.pf_engine.id
  }
}

resource "google_compute_network_firewall_policy_rule" "egress_firewall_private" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 80003
  direction       = "EGRESS"
  action          = "allow"
  description     = "What the CIAM platform reaches privately (its network, interconnects, private endpoints)"
  match {
    dest_ip_ranges = ["10.20.0.0/16", "10.70.0.0/16", "10.70.255.5/32", "10.71.0.0/20"]
    layer4_configs {
      ip_protocol = "all"
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.am.id
  }
  target_secure_tags {
    name = google_tags_tag_value.ds.id
  }
  target_secure_tags {
    name = google_tags_tag_value.idm.id
  }
  target_secure_tags {
    name = google_tags_tag_value.ig.id
  }
  target_secure_tags {
    name = google_tags_tag_value.pf_admin.id
  }
  target_secure_tags {
    name = google_tags_tag_value.pf_engine.id
  }
}

resource "google_compute_network_firewall_policy_rule" "egress_firewall_deny" {
  firewall_policy = google_compute_network_firewall_policy.network_policy.name
  project         = "example-aero-net"
  priority        = 2147483000
  direction       = "EGRESS"
  action          = "deny"
  description     = "Other egress to the internet (egress-firewall allows only its sites)"
  match {
    dest_ip_ranges = ["0.0.0.0/0"]
    layer4_configs {
      ip_protocol = "all"
    }
  }
  target_secure_tags {
    name = google_tags_tag_value.am.id
  }
  target_secure_tags {
    name = google_tags_tag_value.ds.id
  }
  target_secure_tags {
    name = google_tags_tag_value.idm.id
  }
  target_secure_tags {
    name = google_tags_tag_value.ig.id
  }
  target_secure_tags {
    name = google_tags_tag_value.pf_admin.id
  }
  target_secure_tags {
    name = google_tags_tag_value.pf_engine.id
  }
}

# ciam-standby-pf-grants admits 10.70.2.0/24: Cloud SQL's private IP is in Google's service producer network, which this network's firewall rules don't reach; the private services access peering carries the traffic

# ciam-standby-pf-grants: the Cloud SQL service agent (service-<project number>@gcp-sa-cloud-sql.iam.gserviceaccount.com) needs roles/cloudkms.cryptoKeyEncrypterDecrypter on its key

# ciam-standby-pf-grants: its administrator password is read when applied and written write-only: no Terraform state holds it

ephemeral "google_secret_manager_secret_version" "ciam_standby_pf_grants_admin" {
  secret  = "pf-grants-db-password"
  project = "example-aero-ciam-standby"
}

resource "google_sql_database_instance" "ciam_standby_pf_grants" {
  name                = "ciam-standby-pf-grants"
  database_version    = "POSTGRES_16"
  region              = var.region
  encryption_key_name = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  deletion_protection = true
  settings {
    tier                        = "db-custom-2-8192"
    availability_type           = "REGIONAL"
    disk_size                   = 100
    deletion_protection_enabled = true
    user_labels = {
      role       = "pf-grants-db"
      managed_by = "opsdir"
    }
    location_preference {
      zone = "us-central1-a"
    }
    backup_configuration {
      enabled                        = true
      point_in_time_recovery_enabled = true
      backup_retention_settings {
        retained_backups = 14
      }
    }
    ip_configuration {
      ipv4_enabled    = false
      private_network = data.google_compute_network.main.self_link
      ssl_mode        = "ENCRYPTED_ONLY"
    }
    database_flags {
      name  = "idle_in_transaction_session_timeout"
      value = "60000"
    }
    database_flags {
      name  = "log_min_duration_statement"
      value = "1000"
    }
  }
}

resource "google_sql_user" "ciam_standby_pf_grants_admin" {
  name                = var.ciam_standby_pf_grants_admin_login
  instance            = google_sql_database_instance.ciam_standby_pf_grants.name
  password_wo         = ephemeral.google_secret_manager_secret_version.ciam_standby_pf_grants_admin.secret_data
  password_wo_version = 1
}

variable "ciam_standby_pf_grants_admin_login" {
  type        = string
  description = "The administrator login of database ciam-standby-pf-grants"
}

import {
  to = google_sql_database_instance.ciam_standby_pf_grants
  id = "projects/example-aero-ciam-standby/instances/ciam-standby-pf-grants"
}

resource "google_storage_bucket" "audit_archive" {
  name                        = "example-aero-ciam-standby-audit"
  location                    = var.region
  uniform_bucket_level_access = true
  retention_policy {
    retention_period = 34560000
    is_locked        = true
  }
  labels = {
    role       = "audit-archive"
    managed_by = "opsdir"
  }
}

import {
  to = google_storage_bucket.audit_archive
  id = "example-aero-ciam-standby-audit"
}

# backup: the Cloud Storage service agent (service-<project number>@gs-project-accounts.iam.gserviceaccount.com) needs roles/cloudkms.cryptoKeyEncrypterDecrypter on its key

resource "google_storage_bucket" "backup" {
  name                        = "example-aero-ciam-standby-ds-backups"
  location                    = var.region
  uniform_bucket_level_access = true
  public_access_prevention    = "enforced"
  versioning {
    enabled = true
  }
  retention_policy {
    retention_period = 3024000
    is_locked        = true
  }
  encryption {
    default_kms_key_name = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  lifecycle_rule {
    condition {
      age = 30
    }
    action {
      type          = "SetStorageClass"
      storage_class = "COLDLINE"
    }
  }
  lifecycle_rule {
    condition {
      age = 90
    }
    action {
      type = "Delete"
    }
  }
  lifecycle_rule {
    condition {
      days_since_noncurrent_time = 7
      with_state                 = "ARCHIVED"
    }
    action {
      type = "Delete"
    }
  }
  labels = {
    role       = "backup-target"
    managed_by = "opsdir"
  }
}

import {
  to = google_storage_bucket.backup
  id = "example-aero-ciam-standby-ds-backups"
}

resource "google_dns_managed_zone" "fwd_corp_ad_0" {
  name        = "ciam-prod-fwd-corp-ad-0"
  dns_name    = "corp.example-aero.internal."
  visibility  = "private"
  description = "Forwards corp.example-aero.internal (fwd-corp-ad)"
  private_visibility_config {
    networks {
      network_url = data.google_compute_network.main.self_link
    }
  }
  forwarding_config {
    target_name_servers {
      ipv4_address = "10.40.0.53"
    }
    target_name_servers {
      ipv4_address = "10.40.0.54"
    }
  }
}

resource "google_logging_project_sink" "audit_sink" {
  name                   = "ciam-audit"
  destination            = "storage.googleapis.com/example-aero-ciam-standby-audit"
  filter                 = "logName:\"cloudaudit.googleapis.com\""
  unique_writer_identity = true
}

resource "google_storage_bucket_iam_member" "audit_sink" {
  bucket = google_storage_bucket.audit_archive.name
  role   = "roles/storage.objectCreator"
  member = google_logging_project_sink.audit_sink.writer_identity
}

resource "google_project_iam_audit_config" "audit_sink" {
  project = var.project_id
  service = "allServices"
  audit_log_config {
    log_type = "DATA_WRITE"
  }
}

# assets: Cloud Asset Inventory keeps 35 days of resource history itself

resource "google_cloud_asset_project_feed" "assets" {
  project      = var.project_id
  feed_id      = "assets"
  content_type = "RESOURCE"
  asset_types  = [".*"]
  feed_output_config {
    pubsub_destination {
      topic = "projects/example-aero-ciam-standby/topics/ciam-security"
    }
  }
}

# scc: Security Command Center (Premium or Enterprise) activated with Event Threat Detection, Container Threat Detection, VM Threat Detection: a request to the organization's administrators (not rendered)

resource "google_scc_v2_project_notification_config" "scc_findings" {
  # Security Command Center's service agent must be able to publish to the topic
  config_id    = "scc-findings"
  project      = var.project_id
  location     = "global"
  description  = "scc's findings to security-findings"
  pubsub_topic = "projects/example-aero-ciam-standby/topics/ciam-security"
  streaming_config {
    filter = "finding_class=\"THREAT\" AND state=\"ACTIVE\""
  }
}

resource "google_scc_v2_project_notification_config" "scc_incidents" {
  # Security Command Center's service agent must be able to publish to the topic
  config_id    = "scc-incidents"
  project      = var.project_id
  location     = "global"
  description  = "scc's high and worse findings to security-incidents (incident process)"
  pubsub_topic = "projects/example-aero-ciam-standby/topics/ciam-security-incidents"
  streaming_config {
    filter = "finding_class=\"THREAT\" AND state=\"ACTIVE\" AND (severity=\"CRITICAL\" OR severity=\"HIGH\")"
  }
}

# sdp-backups: Sensitive Data Protection refreshes profiles daily or monthly: the record asks every 7 days, profiled daily

resource "google_data_loss_prevention_inspect_template" "sdp_backups" {
  parent       = "projects/${var.project_id}/locations/${var.region}"
  template_id  = "ciam-sdp-backups"
  display_name = "sdp-backups: own data types"
  inspect_config {
    custom_info_types {
      info_type {
        name = "CUI_MARKING"
      }
      likelihood = "LIKELY"
      regex {
        pattern = "CUI//[A-Z][A-Z/-]*"
      }
    }
    custom_info_types {
      info_type {
        name = "EMPLOYEE_ID"
      }
      likelihood = "LIKELY"
      regex {
        pattern = "EA[0-9]{6}"
      }
    }
  }
}

resource "google_data_loss_prevention_discovery_config" "sdp_backups" {
  parent            = "projects/${var.project_id}/locations/${var.region}"
  location          = var.region
  display_name      = "sdp-backups"
  status            = "RUNNING"
  inspect_templates = [google_data_loss_prevention_inspect_template.sdp_backups.id]
  targets {
    cloud_storage_target {
      filter {
        collection {
          include_regexes {
            patterns {
              cloud_storage_regex {
                project_id_regex  = "^${var.project_id}$"
                bucket_name_regex = "^(example\\-aero\\-ciam\\-standby\\-ds\\-backups)$"
              }
            }
          }
        }
      }
      generation_cadence {
        refresh_frequency = "UPDATE_FREQUENCY_DAILY"
      }
    }
  }
  actions {
    pub_sub_notification {
      topic = "projects/example-aero-ciam-standby/topics/ciam-security"
      event = "NEW_PROFILE"
    }
  }
  actions {
    pub_sub_notification {
      topic = "projects/example-aero-ciam-standby/topics/ciam-security"
      event = "CHANGED_PROFILE"
    }
  }
}

data "google_secret_manager_secret" "am_admin_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "am-admin-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "am_ds_bind_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "am-ds-bind-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "am_keystore" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "am-keystore"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "ds_deployment_id" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "ds-deployment-id"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "ds_deployment_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "ds-deployment-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "ds_root_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "ds-root-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "ds_tls_keystore" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "ds-tls-keystore"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "idm_admin_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "idm-admin-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "idm_ds_bind_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "idm-ds-bind-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "idm_hrdb_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "idm-hrdb-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "idm_keystore" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "idm-keystore"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "ig_keystore" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "ig-keystore"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "pf_admin_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "pf-admin-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "pf_captcha_secret" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "pf-captcha-secret"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "pf_corp_ad_bind_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "pf-corp-ad-bind-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "pf_ds_bind_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "pf-ds-bind-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "pf_grants_db_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "pf-grants-db-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "pf_signing_key" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "pf-signing-key"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "pf_smtp_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "pf-smtp-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "sso_tls_keystore" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "sso-tls-keystore"
  project   = "example-aero-ciam-standby"
}

# Egress 'egress-pf': Cloud NAT example-aero-ciam-standby/us-central1/ciam-standby-router/ciam-standby-nat (landing zone; not managed here)
