# Generated by opsdir from env=prod,cloud=standby,ou=environments,dc=ciam-ops
# Google Cloud infrastructure for the CIAM platform
# Do not edit. Change the operations directory (under an approved change) and re-render.

data "google_compute_network" "main" {
  name    = "ciam-standby"
  project = "example-aero-net"
}

data "google_compute_subnetwork" "subnet_am" {
  name    = "ciam-standby-am"
  region  = "us-central1"
  project = "example-aero-net"
}

data "google_compute_subnetwork" "subnet_ds" {
  name    = "ciam-standby-ds"
  region  = "us-central1"
  project = "example-aero-net"
}

data "google_compute_subnetwork" "subnet_idm" {
  name    = "ciam-standby-idm"
  region  = "us-central1"
  project = "example-aero-net"
}

data "google_compute_subnetwork" "subnet_ig" {
  name    = "ciam-standby-ig"
  region  = "us-central1"
  project = "example-aero-net"
}

data "google_compute_subnetwork" "subnet_pf" {
  name    = "ciam-standby-pf"
  region  = "us-central1"
  project = "example-aero-net"
}

resource "google_compute_firewall" "fw_admin" {
  name        = "ciam-prod-fw-admin"
  description = "fw-admin (fw-admin)"
  network     = data.google_compute_network.main.self_link
  direction   = "INGRESS"
  priority    = 150
  allow {
    protocol = "tcp"
    ports    = ["4444"]
  }
  source_ranges = ["10.70.9.0/28"]
  target_tags   = ["ciam-prod-ds"]
}

resource "google_compute_firewall" "fw_apps_public" {
  name        = "ciam-prod-fw-apps-public"
  description = "fw-apps-public (fw-apps-public)"
  network     = data.google_compute_network.main.self_link
  direction   = "INGRESS"
  priority    = 180
  allow {
    protocol = "tcp"
    ports    = ["443"]
  }
  source_ranges = ["0.0.0.0/0"]
  target_tags   = ["ciam-prod-ig"]
}

resource "google_compute_firewall" "fw_customer_portal" {
  name        = "ciam-prod-fw-customer-portal"
  description = "consumer customer-portal-svc (fw-customer-portal)"
  network     = data.google_compute_network.main.self_link
  direction   = "INGRESS"
  priority    = 110
  allow {
    protocol = "tcp"
    ports    = ["1636"]
  }
  source_ranges = ["10.30.8.0/24"]
  target_tags   = ["ciam-prod-ds"]
}

resource "google_compute_firewall" "fw_idm_sync" {
  name        = "ciam-prod-fw-idm-sync"
  description = "consumer idm-sync (fw-idm-sync)"
  network     = data.google_compute_network.main.self_link
  direction   = "INGRESS"
  priority    = 130
  allow {
    protocol = "tcp"
    ports    = ["1636"]
  }
  source_ranges = ["10.70.6.0/24"]
  target_tags   = ["ciam-prod-ds"]
}

resource "google_compute_firewall" "fw_login_public" {
  name        = "ciam-prod-fw-login-public"
  description = "fw-login-public (fw-login-public)"
  network     = data.google_compute_network.main.self_link
  direction   = "INGRESS"
  priority    = 170
  allow {
    protocol = "tcp"
    ports    = ["443"]
  }
  source_ranges = ["0.0.0.0/0"]
  target_tags   = ["ciam-prod-am"]
}

resource "google_compute_firewall" "fw_pf_ds_svc" {
  name        = "ciam-prod-fw-pf-ds-svc"
  description = "consumer pf-ds-svc (fw-pf-ds-svc)"
  network     = data.google_compute_network.main.self_link
  direction   = "INGRESS"
  priority    = 100
  allow {
    protocol = "tcp"
    ports    = ["1636"]
  }
  source_ranges = ["10.70.2.0/24"]
  target_tags   = ["ciam-prod-ds"]
}

resource "google_compute_firewall" "fw_replication" {
  name        = "ciam-prod-fw-replication"
  description = "fw-replication (fw-replication)"
  network     = data.google_compute_network.main.self_link
  direction   = "INGRESS"
  priority    = 140
  allow {
    protocol = "tcp"
    ports    = ["8989"]
  }
  source_ranges = ["10.70.1.0/24", "10.20.0.0/16"]
  target_tags   = ["ciam-prod-ds"]
}

resource "google_compute_firewall" "fw_sso_public" {
  name        = "ciam-prod-fw-sso-public"
  description = "fw-sso-public (fw-sso-public)"
  network     = data.google_compute_network.main.self_link
  direction   = "INGRESS"
  priority    = 160
  allow {
    protocol = "tcp"
    ports    = ["443"]
  }
  source_ranges = ["0.0.0.0/0"]
  target_tags   = ["ciam-prod-pf-engine"]
}

resource "google_compute_firewall" "fw_supplier_portal" {
  name        = "ciam-prod-fw-supplier-portal"
  description = "consumer supplier-portal-svc (fw-supplier-portal)"
  network     = data.google_compute_network.main.self_link
  direction   = "INGRESS"
  priority    = 120
  allow {
    protocol = "tcp"
    ports    = ["1636"]
  }
  source_ranges = ["10.31.2.0/24"]
  target_tags   = ["ciam-prod-ds"]
}

resource "google_service_account" "identity_ds" {
  account_id   = "ciam-standby-ds"
  display_name = "pingds (identity-ds)"
}

resource "google_secret_manager_secret_iam_member" "identity_ds_read_secret_ds_root_password" {
  project   = "example-aero-ciam-standby"
  secret_id = "ds-root-password"
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.identity_ds.email}"
}

resource "google_kms_crypto_key_iam_member" "identity_ds_use_key_disk_encryption" {
  crypto_key_id = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:${google_service_account.identity_ds.email}"
}

resource "google_project_iam_member" "identity_ds_write_logs_audit_logs" {
  # granted on the project: the narrowest scope Google Cloud allows for it
  project = "example-aero-ciam-standby"
  role    = "roles/logging.logWriter"
  member  = "serviceAccount:${google_service_account.identity_ds.email}"
}

resource "google_storage_bucket_iam_member" "identity_ds_write_storage_backup_target" {
  bucket = "example-aero-ciam-standby-ds-backups"
  role   = "roles/storage.objectCreator"
  member = "serviceAccount:${google_service_account.identity_ds.email}"
}

resource "google_service_account" "identity_pf" {
  account_id   = "ciam-standby-pf"
  display_name = "pingfederate (identity-pf)"
}

resource "google_secret_manager_secret_iam_member" "identity_pf_read_secret_pf_admin_password" {
  project   = "example-aero-ciam-standby"
  secret_id = "pf-admin-password"
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.identity_pf.email}"
}

resource "google_secret_manager_secret_iam_member" "identity_pf_read_secret_pf_ds_bind_password" {
  project   = "example-aero-ciam-standby"
  secret_id = "pf-ds-bind-password"
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.identity_pf.email}"
}

resource "google_secret_manager_secret_iam_member" "identity_pf_read_secret_pf_signing_key" {
  project   = "example-aero-ciam-standby"
  secret_id = "pf-signing-key"
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.identity_pf.email}"
}

resource "google_project_iam_member" "identity_pf_write_logs_audit_logs" {
  # granted on the project: the narrowest scope Google Cloud allows for it
  project = "example-aero-ciam-standby"
  role    = "roles/logging.logWriter"
  member  = "serviceAccount:${google_service_account.identity_pf.email}"
}

resource "google_compute_instance" "am_1" {
  name         = "am-1"
  machine_type = "n2-standard-2"
  zone         = "us-central1-a"
  hostname     = "am-1.gcp.internal.example-aero.test"
  tags         = ["ciam-prod-am"]
  boot_disk {
    initialize_params {
      image = "projects/example-aero-images/global/images/pingam-7-5-1-rhel9"
    }
    kms_key_self_link = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  network_interface {
    subnetwork = data.google_compute_subnetwork.subnet_am.self_link
    network_ip = "10.70.3.21"
  }
  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }
  metadata = {
    enable-oslogin = "TRUE"
    ciam-role      = "am"
    ciam-product   = "PingAM 7.5.1"
  }
  labels = {
    role       = "am"
    product    = "pingam-7-5-1"
    managed_by = "opsdir"
  }
}

resource "google_compute_instance" "ds_1" {
  name         = "ds-1"
  machine_type = "n2-standard-4"
  zone         = "us-central1-a"
  hostname     = "ds-1.gcp.internal.example-aero.test"
  tags         = ["ciam-prod-ds"]
  boot_disk {
    initialize_params {
      image = "projects/example-aero-images/global/images/pingds-7-5-1-rhel9"
    }
    kms_key_self_link = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  network_interface {
    subnetwork = data.google_compute_subnetwork.subnet_ds.self_link
    network_ip = "10.70.1.11"
  }
  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }
  service_account {
    email  = google_service_account.identity_ds.email
    scopes = ["cloud-platform"]
  }
  metadata = {
    enable-oslogin = "TRUE"
    ciam-role      = "ds"
    ciam-product   = "PingDS 7.5.1"
  }
  labels = {
    role       = "ds"
    product    = "pingds-7-5-1"
    managed_by = "opsdir"
  }
}

resource "google_compute_instance" "ds_2" {
  name         = "ds-2"
  machine_type = "n2-standard-4"
  zone         = "us-central1-b"
  hostname     = "ds-2.gcp.internal.example-aero.test"
  tags         = ["ciam-prod-ds"]
  boot_disk {
    initialize_params {
      image = "projects/example-aero-images/global/images/pingds-7-5-1-rhel9"
    }
    kms_key_self_link = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  network_interface {
    subnetwork = data.google_compute_subnetwork.subnet_ds.self_link
    network_ip = "10.70.1.12"
  }
  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }
  service_account {
    email  = google_service_account.identity_ds.email
    scopes = ["cloud-platform"]
  }
  metadata = {
    enable-oslogin = "TRUE"
    ciam-role      = "ds"
    ciam-product   = "PingDS 7.5.1"
  }
  labels = {
    role       = "ds"
    product    = "pingds-7-5-1"
    managed_by = "opsdir"
  }
}

resource "google_compute_instance" "idm_1" {
  name         = "idm-1"
  machine_type = "n2-standard-2"
  zone         = "us-central1-a"
  hostname     = "idm-1.gcp.internal.example-aero.test"
  tags         = ["ciam-prod-idm"]
  boot_disk {
    initialize_params {
      image = "projects/example-aero-images/global/images/pingidm-7-5-0-rhel9"
    }
    kms_key_self_link = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  network_interface {
    subnetwork = data.google_compute_subnetwork.subnet_idm.self_link
    network_ip = "10.70.6.21"
  }
  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }
  metadata = {
    enable-oslogin = "TRUE"
    ciam-role      = "idm"
    ciam-product   = "PingIDM 7.5.0"
  }
  labels = {
    role       = "idm"
    product    = "pingidm-7-5-0"
    managed_by = "opsdir"
  }
}

resource "google_compute_instance" "ig_1" {
  name         = "ig-1"
  machine_type = "n2-standard-2"
  zone         = "us-central1-a"
  hostname     = "ig-1.gcp.internal.example-aero.test"
  tags         = ["ciam-prod-ig"]
  boot_disk {
    initialize_params {
      image = "projects/example-aero-images/global/images/pinggateway-2024-11-0-rhel9"
    }
    kms_key_self_link = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  network_interface {
    subnetwork = data.google_compute_subnetwork.subnet_ig.self_link
    network_ip = "10.70.10.21"
  }
  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }
  metadata = {
    enable-oslogin = "TRUE"
    ciam-role      = "ig"
    ciam-product   = "PingGateway 2024.11.0"
  }
  labels = {
    role       = "ig"
    product    = "pinggateway-2024-11-0"
    managed_by = "opsdir"
  }
}

resource "google_compute_instance" "pf_admin_1" {
  name         = "pf-admin-1"
  machine_type = "n2-standard-2"
  zone         = "us-central1-a"
  hostname     = "pf-admin-1.gcp.internal.example-aero.test"
  tags         = ["ciam-prod-pf-admin"]
  boot_disk {
    initialize_params {
      image = "projects/example-aero-images/global/images/pingfederate-12-1-4-rhel9"
    }
    kms_key_self_link = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  network_interface {
    subnetwork = data.google_compute_subnetwork.subnet_pf.self_link
    network_ip = "10.70.2.10"
  }
  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }
  metadata = {
    enable-oslogin = "TRUE"
    ciam-role      = "pf-admin"
    ciam-product   = "PingFederate 12.1.4"
  }
  labels = {
    role       = "pf-admin"
    product    = "pingfederate-12-1-4"
    managed_by = "opsdir"
  }
}

resource "google_compute_instance" "pf_engine_1" {
  name         = "pf-engine-1"
  machine_type = "n2-standard-2"
  zone         = "us-central1-a"
  hostname     = "pf-engine-1.gcp.internal.example-aero.test"
  tags         = ["ciam-prod-pf-engine"]
  boot_disk {
    initialize_params {
      image = "projects/example-aero-images/global/images/pingfederate-12-1-4-rhel9"
    }
    kms_key_self_link = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  network_interface {
    subnetwork = data.google_compute_subnetwork.subnet_pf.self_link
    network_ip = "10.70.2.21"
  }
  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }
  service_account {
    email  = google_service_account.identity_pf.email
    scopes = ["cloud-platform"]
  }
  metadata = {
    enable-oslogin = "TRUE"
    ciam-role      = "pf-engine"
    ciam-product   = "PingFederate 12.1.4"
  }
  labels = {
    role       = "pf-engine"
    product    = "pingfederate-12-1-4"
    managed_by = "opsdir"
  }
}

resource "google_compute_instance" "pf_engine_2" {
  name         = "pf-engine-2"
  machine_type = "n2-standard-2"
  zone         = "us-central1-b"
  hostname     = "pf-engine-2.gcp.internal.example-aero.test"
  tags         = ["ciam-prod-pf-engine"]
  boot_disk {
    initialize_params {
      image = "projects/example-aero-images/global/images/pingfederate-12-1-4-rhel9"
    }
    kms_key_self_link = "projects/example-aero-ciam-standby/locations/us-central1/keyRings/ciam/cryptoKeys/disk"
  }
  network_interface {
    subnetwork = data.google_compute_subnetwork.subnet_pf.self_link
    network_ip = "10.70.2.22"
  }
  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }
  service_account {
    email  = google_service_account.identity_pf.email
    scopes = ["cloud-platform"]
  }
  metadata = {
    enable-oslogin = "TRUE"
    ciam-role      = "pf-engine"
    ciam-product   = "PingFederate 12.1.4"
  }
  labels = {
    role       = "pf-engine"
    product    = "pingfederate-12-1-4"
    managed_by = "opsdir"
  }
}

data "google_compute_address" "svc_apps" {
  name   = "ciam-standby-apps"
  region = var.region
}

resource "google_compute_instance_group" "svc_apps_us_central1_a" {
  name      = "ciam-prod-svc-apps-us-central1-a"
  zone      = "us-central1-a"
  instances = [google_compute_instance.ig_1.self_link]
  named_port {
    name = "ciam"
    port = 443
  }
}

resource "google_compute_region_health_check" "svc_apps" {
  name   = "ciam-prod-svc-apps"
  region = var.region
  tcp_health_check {
    port = 443
  }
}

resource "google_compute_firewall" "svc_apps_health_checks" {
  name        = "ciam-prod-svc-apps-health-checks"
  description = "Google Cloud health checks for svc-apps"
  network     = data.google_compute_network.main.self_link
  direction   = "INGRESS"
  allow {
    protocol = "tcp"
    ports    = ["443"]
  }
  source_ranges = ["35.191.0.0/16", "209.85.152.0/22", "209.85.204.0/22"]
  target_tags   = ["ciam-prod-ig"]
}

resource "google_compute_region_backend_service" "svc_apps" {
  name                  = "ciam-prod-svc-apps"
  region                = var.region
  load_balancing_scheme = "EXTERNAL"
  protocol              = "TCP"
  port_name             = "ciam"
  health_checks         = [google_compute_region_health_check.svc_apps.id]
  backend {
    group           = google_compute_instance_group.svc_apps_us_central1_a.self_link
    balancing_mode  = "CONNECTION"
    capacity_scaler = 1.0
  }
}

resource "google_compute_forwarding_rule" "svc_apps" {
  name                  = "ciam-prod-svc-apps"
  region                = var.region
  load_balancing_scheme = "EXTERNAL"
  ip_protocol           = "TCP"
  ports                 = ["443"]
  ip_address            = data.google_compute_address.svc_apps.address
  backend_service       = google_compute_region_backend_service.svc_apps.id
  labels = {
    service    = "apps-example-aero-test"
    managed_by = "opsdir"
  }
}

resource "google_dns_record_set" "svc_apps" {
  managed_zone = "example-aero-public"
  name         = "apps.example-aero.test."
  type         = "A"
  ttl          = 300
  rrdatas      = [google_compute_forwarding_rule.svc_apps.ip_address]
}

resource "google_compute_instance_group" "svc_ldaps_us_central1_a" {
  name      = "ciam-prod-svc-ldaps-us-central1-a"
  zone      = "us-central1-a"
  instances = [google_compute_instance.ds_1.self_link]
}

resource "google_compute_instance_group" "svc_ldaps_us_central1_b" {
  name      = "ciam-prod-svc-ldaps-us-central1-b"
  zone      = "us-central1-b"
  instances = [google_compute_instance.ds_2.self_link]
}

resource "google_compute_region_health_check" "svc_ldaps" {
  name   = "ciam-prod-svc-ldaps"
  region = var.region
  tcp_health_check {
    port = 1636
  }
}

resource "google_compute_firewall" "svc_ldaps_health_checks" {
  name        = "ciam-prod-svc-ldaps-health-checks"
  description = "Google Cloud health checks for svc-ldaps"
  network     = data.google_compute_network.main.self_link
  direction   = "INGRESS"
  allow {
    protocol = "tcp"
    ports    = ["1636"]
  }
  source_ranges = ["35.191.0.0/16"]
  target_tags   = ["ciam-prod-ds"]
}

resource "google_compute_region_backend_service" "svc_ldaps" {
  name                  = "ciam-prod-svc-ldaps"
  region                = var.region
  load_balancing_scheme = "INTERNAL"
  protocol              = "TCP"
  health_checks         = [google_compute_region_health_check.svc_ldaps.id]
  backend {
    group          = google_compute_instance_group.svc_ldaps_us_central1_a.self_link
    balancing_mode = "CONNECTION"
  }
  backend {
    group          = google_compute_instance_group.svc_ldaps_us_central1_b.self_link
    balancing_mode = "CONNECTION"
  }
}

resource "google_compute_forwarding_rule" "svc_ldaps" {
  name                  = "ciam-prod-svc-ldaps"
  region                = var.region
  load_balancing_scheme = "INTERNAL"
  ip_protocol           = "TCP"
  ports                 = ["1636"]
  ip_address            = "10.70.1.100"
  backend_service       = google_compute_region_backend_service.svc_ldaps.id
  network               = data.google_compute_network.main.self_link
  subnetwork            = data.google_compute_subnetwork.subnet_ds.self_link
  labels = {
    service    = "ldap-id-example-aero-test"
    managed_by = "opsdir"
  }
}

resource "google_dns_record_set" "svc_ldaps" {
  managed_zone = "ciam-standby-private"
  name         = "ldap.id.example-aero.test."
  type         = "A"
  ttl          = 300
  rrdatas      = [google_compute_forwarding_rule.svc_ldaps.ip_address]
}

data "google_compute_address" "svc_login" {
  name   = "ciam-standby-login"
  region = var.region
}

resource "google_compute_instance_group" "svc_login_us_central1_a" {
  name      = "ciam-prod-svc-login-us-central1-a"
  zone      = "us-central1-a"
  instances = [google_compute_instance.am_1.self_link]
  named_port {
    name = "ciam"
    port = 443
  }
}

resource "google_compute_region_health_check" "svc_login" {
  name   = "ciam-prod-svc-login"
  region = var.region
  tcp_health_check {
    port = 443
  }
}

resource "google_compute_firewall" "svc_login_health_checks" {
  name        = "ciam-prod-svc-login-health-checks"
  description = "Google Cloud health checks for svc-login"
  network     = data.google_compute_network.main.self_link
  direction   = "INGRESS"
  allow {
    protocol = "tcp"
    ports    = ["443"]
  }
  source_ranges = ["35.191.0.0/16", "209.85.152.0/22", "209.85.204.0/22"]
  target_tags   = ["ciam-prod-am"]
}

resource "google_compute_region_backend_service" "svc_login" {
  name                  = "ciam-prod-svc-login"
  region                = var.region
  load_balancing_scheme = "EXTERNAL"
  protocol              = "TCP"
  port_name             = "ciam"
  health_checks         = [google_compute_region_health_check.svc_login.id]
  backend {
    group           = google_compute_instance_group.svc_login_us_central1_a.self_link
    balancing_mode  = "CONNECTION"
    capacity_scaler = 1.0
  }
}

resource "google_compute_forwarding_rule" "svc_login" {
  name                  = "ciam-prod-svc-login"
  region                = var.region
  load_balancing_scheme = "EXTERNAL"
  ip_protocol           = "TCP"
  ports                 = ["443"]
  ip_address            = data.google_compute_address.svc_login.address
  backend_service       = google_compute_region_backend_service.svc_login.id
  labels = {
    service    = "login-example-aero-test"
    managed_by = "opsdir"
  }
}

resource "google_dns_record_set" "svc_login" {
  managed_zone = "example-aero-public"
  name         = "login.example-aero.test."
  type         = "A"
  ttl          = 300
  rrdatas      = [google_compute_forwarding_rule.svc_login.ip_address]
}

data "google_compute_address" "svc_sso" {
  name   = "ciam-standby-sso"
  region = var.region
}

resource "google_compute_instance_group" "svc_sso_us_central1_a" {
  name      = "ciam-prod-svc-sso-us-central1-a"
  zone      = "us-central1-a"
  instances = [google_compute_instance.pf_engine_1.self_link]
  named_port {
    name = "ciam"
    port = 443
  }
}

resource "google_compute_instance_group" "svc_sso_us_central1_b" {
  name      = "ciam-prod-svc-sso-us-central1-b"
  zone      = "us-central1-b"
  instances = [google_compute_instance.pf_engine_2.self_link]
  named_port {
    name = "ciam"
    port = 443
  }
}

resource "google_compute_region_health_check" "svc_sso" {
  name   = "ciam-prod-svc-sso"
  region = var.region
  tcp_health_check {
    port = 443
  }
}

resource "google_compute_firewall" "svc_sso_health_checks" {
  name        = "ciam-prod-svc-sso-health-checks"
  description = "Google Cloud health checks for svc-sso"
  network     = data.google_compute_network.main.self_link
  direction   = "INGRESS"
  allow {
    protocol = "tcp"
    ports    = ["443"]
  }
  source_ranges = ["35.191.0.0/16", "209.85.152.0/22", "209.85.204.0/22"]
  target_tags   = ["ciam-prod-pf-engine"]
}

resource "google_compute_region_backend_service" "svc_sso" {
  name                  = "ciam-prod-svc-sso"
  region                = var.region
  load_balancing_scheme = "EXTERNAL"
  protocol              = "TCP"
  port_name             = "ciam"
  health_checks         = [google_compute_region_health_check.svc_sso.id]
  backend {
    group           = google_compute_instance_group.svc_sso_us_central1_a.self_link
    balancing_mode  = "CONNECTION"
    capacity_scaler = 1.0
  }
  backend {
    group           = google_compute_instance_group.svc_sso_us_central1_b.self_link
    balancing_mode  = "CONNECTION"
    capacity_scaler = 1.0
  }
}

resource "google_compute_forwarding_rule" "svc_sso" {
  name                  = "ciam-prod-svc-sso"
  region                = var.region
  load_balancing_scheme = "EXTERNAL"
  ip_protocol           = "TCP"
  ports                 = ["443"]
  ip_address            = data.google_compute_address.svc_sso.address
  backend_service       = google_compute_region_backend_service.svc_sso.id
  labels = {
    service    = "sso-example-aero-test"
    managed_by = "opsdir"
  }
}

resource "google_dns_record_set" "svc_sso" {
  managed_zone = "example-aero-public"
  name         = "sso.example-aero.test."
  type         = "A"
  ttl          = 300
  rrdatas      = [google_compute_forwarding_rule.svc_sso.ip_address]
}

data "google_secret_manager_secret" "am_admin_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "am-admin-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "am_ds_bind_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "am-ds-bind-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "am_keystore" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "am-keystore"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "ds_deployment_id" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "ds-deployment-id"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "ds_deployment_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "ds-deployment-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "ds_root_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "ds-root-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "ds_tls_keystore" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "ds-tls-keystore"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "idm_admin_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "idm-admin-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "idm_ds_bind_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "idm-ds-bind-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "idm_hrdb_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "idm-hrdb-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "idm_keystore" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "idm-keystore"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "ig_keystore" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "ig-keystore"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "pf_admin_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "pf-admin-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "pf_captcha_secret" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "pf-captcha-secret"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "pf_ds_bind_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "pf-ds-bind-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "pf_grants_db_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "pf-grants-db-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "pf_signing_key" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "pf-signing-key"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "pf_smtp_password" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "pf-smtp-password"
  project   = "example-aero-ciam-standby"
}

data "google_secret_manager_secret" "sso_tls_keystore" {
  # metadata only: no secret version (value) enters Terraform state
  secret_id = "sso-tls-keystore"
  project   = "example-aero-ciam-standby"
}

data "google_storage_bucket" "ds_backups" {
  name = "example-aero-ciam-standby-ds-backups"
}

# Egress 'egress-pf': Cloud NAT example-aero-ciam-standby/us-central1/ciam-standby-router/ciam-standby-nat (landing zone; not managed here)
