# Generated by opsdir from env=prod,cloud=standby,ou=environments,dc=ciam-ops
# Providers and inputs
# Do not edit. Change the operations directory (under an approved change) and re-render.

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 8.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
}

variable "project_id" {
  type = string
}

variable "region" {
  type    = string
  default = "us-central1"
}
