# Generated by opsdir from env=prod,cloud=standby,ou=environments,dc=ciam-ops
# Providers and inputs
# Do not edit. Change the operations directory (under an approved change) and re-render.

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 8.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
  default_labels = {
    costcenter         = "cc-1001"
    dataclassification = "confidential"
    environment        = "standby-prod"
    owner              = "ciam-platform"
  }
}

variable "project_id" {
  type    = string
  default = "example-aero-ciam-standby"
}

variable "region" {
  type    = string
  default = "us-central1"
}
