"""Environment-neutral configuration of a DS-lineage server, rendered from the directory domain: the standard LDAP
files (schema, tree), the dsconfig batch (backends and indexes, password policies, connection handlers, log
publishers, replication) and the ACIs in the lineage's ACI syntax.

Command and property names follow the products' documentation; verify them against the exact target version.
"""
from itertools import chain

from opsdir.core.contract import Format
from opsdir.core.directory import children, follow, get, one, rdn_value, subtree, values
from opsdir.domains.directory.naming import ACIS, DECLARED as DECL
from opsdir_adapter_ldap.adapter import FORMATS as LDAP_FORMATS, render_standard
from .product import handler_name

# The lineage's batch syntax: dsconfig subcommands, one per line (registered under opsdir.formats).
DSCONFIG_BATCH = Format(name="dsconfig-batch", title="DS lineage dsconfig batch file", media_type="text/plain",
                        extensions=(".batch",), comment=("#",), read=None, write=None, codec=None)
# The format of every neutral file the lineage renders (products add their setup scripts)
FORMATS = (*LDAP_FORMATS, ("ds/dsconfig.batch", "dsconfig-batch"), ("ds/*.ldif", "ldif"))
# directory attribute → dsconfig password-policy property (optional ones)
POLICY_PROPS = (("ciamLockoutFailureCount", "lockout-failure-count"),
                ("ciamLockoutDuration", "lockout-duration"),
                ("ciamPasswordHistoryCount", "password-history-count"),
                ("ciamMaxPasswordAge", "max-password-age"))


def _q(v):
    return f'"{v}"' if " " in v else v


def _index_line(d, be, ix):
    attr = one(follow(d, ix, "ciamIndexedAttribute"), "ciamLdapName")
    types = " ".join(f"--set index-type:{t}" for t in values(ix, "ciamIndexType"))
    return f"create-backend-index --backend-name {rdn_value(be)} --index-name {attr} {types}"


def _backend_lines(d, be):
    return (f"# backend {rdn_value(be)} ({one(be, 'ciamBaseDn')})",
            *(_index_line(d, be, ix) for ix in children(d, be.dn, "ciamIndex")), "")


def _policy_line(product, pp):
    """create-password-policy, or set-password-policy-prop for a policy the product's servers already have."""
    props = (f"--set default-password-storage-scheme:{_q(one(pp, 'ciamStorageScheme'))}",
             "--set password-attribute:userPassword",
             *(f"--set {prop}:{_q(one(pp, attr))}" for attr, prop in POLICY_PROPS if one(pp, attr) is not None))
    if rdn_value(pp) in product.builtin_policies:
        return f'set-password-policy-prop --policy-name "{rdn_value(pp)}" ' + " ".join(props)
    return f'create-password-policy --policy-name "{rdn_value(pp)}" --type password-policy ' + " ".join(props)


def _handler_line(product, h):
    port = f" --set listen-port:{one(h, 'ciamListenPort')}" if one(h, "ciamListenPort") else ""
    return (f"set-connection-handler-prop --handler-name {_q(handler_name(product, rdn_value(h)))} "
            f"--set enabled:{one(h, 'ciamEnabled').lower()}{port}")


def _publisher_line(lp):
    return f'set-log-publisher-prop --publisher-name "{rdn_value(lp)}" --set enabled:{one(lp, "ciamEnabled").lower()}'


def _replication_lines(d):
    topo = get(d, f"cn=topology,ou=replication,{DECL}")
    if not (topo and one(topo, "ciamReplicationPurgeDelay")):
        return ()
    return ("set-synchronization-provider-prop --provider-name \"Multimaster Synchronization\" "
            f"--set replication-purge-delay:{_q(one(topo, 'ciamReplicationPurgeDelay'))}",)


def dsconfig_batch(product, d):
    lines = (f"# dsconfig batch file. Generated by opsdir from {DECL}",
             "# Environment-neutral: the same file is applied to every environment.", *product.dsconfig_apply, "",
             *chain.from_iterable(_backend_lines(d, be) for be in subtree(d, f"ou=backends,{DECL}", "ciamBackend")),
             *(_policy_line(product, pp)
               for pp in children(d, f"ou=password-policies,{DECL}", "ciamPasswordPolicy")), "",
             *(_handler_line(product, h)
               for h in children(d, f"ou=connection-handlers,{DECL}", "ciamConnectionHandler")),
             *(_publisher_line(lp) for lp in children(d, f"ou=log-publishers,{DECL}", "ciamLogPublisher")),
             *_replication_lines(d))
    return "\n".join(lines) + "\n"


def _aci_target(d, aci):
    if one(aci, "ciamAciAllAttributes") == "TRUE":
        return "*"
    return " || ".join(one(get(d, a), "ciamLdapName") for a in values(aci, "ciamAciTargetAttr"))


def _aci_warnings(aci, target):
    checks = (("no owner", not one(aci, "ciamOwner")),
              ("no justification", not one(aci, "ciamJustification")),
              ("targetattr=* (all attributes)", target == "*"))
    return tuple(w for w, failed in checks if failed)


def _aci_lines(d, aci):
    target = _aci_target(d, aci)
    users = " || ".join(f"ldap:///{one(get(d, g), 'ciamBindDn')}" for g in values(aci, "ciamAciGrantee"))
    rights = ",".join(values(aci, "ciamAciRight"))
    warn = _aci_warnings(aci, target)
    return ((f"# WARNING {rdn_value(aci)}: " + ", ".join(warn),) if warn else ()) + (
        f"dn: {one(aci, 'ciamAciTargetDn')}", "changetype: modify", "add: aci",
        f'aci: (targetattr = "{target}")(version 3.0; acl "{rdn_value(aci)}"; '
        f'allow ({rights}) userdn = "{users}";)', "")


def acis_ldif(d):
    head = (f"# ACIs for the user directory. Generated by opsdir from {ACIS}.",
            "# Environment-neutral. Apply with ldapmodify under change control.", "")
    body = chain.from_iterable(_aci_lines(d, aci) for aci in children(d, ACIS, "ciamAci"))
    return "\n".join((*head, *body))


def neutral_files(product, d):
    """Every environment-neutral file of a DS-lineage server: the standard LDAP files, then the lineage's own."""
    return {**render_standard(d), "ds/dsconfig.batch": dsconfig_batch(product, d), "ds/acis.ldif": acis_ldif(d)}
