"""CloudWatch Synthetics canaries rendered from the record: a script per canary (GET for health, a client-credentials
token request reading its secret when it runs), the canary named as its binding, its artifacts where its binding says,
one execution role for the environment; what a canary outside a VPC can't reach or the record can't describe is
named."""
import ast

from opsdir.core.contract import Endpoint
from opsdir.domains.observability.naming import CANARIES
from opsdir_adapter_aws.canaries import render_canaries
from network_fixtures import ALPHA, entry, model

ENDPOINTS = (Endpoint("health", "/pf/heartbeat.ping", "web"), Endpoint("token", "/as/token.oauth2", "web"))
SECRET = "arn:aws:secretsmanager:us-east-1:111122223333:secret:canary-client"


def _canary(cn, **attrs):
    return entry(CANARIES, cn, "ciamCanary", **attrs).replace("objectClass: ciamCanary",
                                                               "objectClass: ciamObject\nobjectClass: ciamCanary")


TREE = (f"dn: {CANARIES}\nobjectClass: top\nobjectClass: organizationalUnit\nou: canaries\n",
        _canary("sso-alive", ciamCheckedService="sso", ciamCanaryFlow="health", ciamInterval="5m"),
        _canary("sso-token", ciamCheckedService="sso", ciamCanaryFlow="oidc-token", ciamUsesRole="canary-client"),
        _canary("intranet", ciamCheckedService="admin", ciamCanaryFlow="health"))
BINDINGS = (
    entry(ALPHA, "svc-sso", "ciamServiceName", ciamBindingRole="sso", ciamFqdn="sso.example.test",
          ciamTargetRole="web", ciamExposure="internet"),
    entry(ALPHA, "svc-admin", "ciamServiceName", ciamBindingRole="admin", ciamFqdn="admin.example.test",
          ciamTargetRole="web", ciamFrontendIp="10.1.9.20"),
    entry(ALPHA, "client", "ciamSecretRef", ciamBindingRole="canary-client", ciamRefUri=f"aws-sm://{SECRET}"),
)
ALIVE = entry(ALPHA, "ciam-sso-alive", "ciamCanaryBinding", ciamBindingRole="canary-sso-alive",
              ciamRealizes="sso-alive",
              ciamProviderRef="arn:aws:synthetics:us-east-1:111122223333:canary:ciam-sso-alive",
              ciamStorageRef="s3://example-ciam-canaries/alive/")
TOKEN = entry(ALPHA, "sso-token", "ciamCanaryBinding", ciamBindingRole="canary-sso-token", ciamRealizes="sso-token",
              ciamProviderRef="arn:aws:synthetics:us-east-1:111122223333:canary:sso-token",
              ciamStorageRef="s3://example-ciam-canaries")


def _render(*extra):
    _, alpha, _ = model(alpha=(*BINDINGS, *extra), tree=TREE)
    return render_canaries(alpha, ENDPOINTS)


def test_each_canary_runs_a_rendered_script_named_as_its_binding():
    hcl, scripts = _render(ALIVE, TOKEN)
    text = "\n".join(hcl)
    assert ('resource "aws_synthetics_canary" "ciam_sso_alive" {\n'
            '  name                 = "ciam-sso-alive"\n'
            '  runtime_version      = "syn-python-selenium-12.0"\n'
            '  handler              = "canary.handler"\n'
            '  zip_file             = data.archive_file.canary_ciam_sso_alive.output_path\n'
            '  artifact_s3_location = "s3://example-ciam-canaries/alive/"\n'
            '  execution_role_arn   = aws_iam_role.canaries.arn\n'
            '  start_canary         = true\n') in text
    assert 'expression = "rate(5 minutes)"' in text and 'BindingRole = "canary-sso-alive"' in text
    assert 'Realizes    = "sso-token"' in text and 'BindingRole = "canary-sso-token"' in text
    assert 'artifact_s3_location = "s3://example-ciam-canaries/"' in text
    health = scripts["terraform/canaries/ciam-sso-alive/python/canary.py"]
    assert health.startswith("# Generated by opsdir from env=prod,cloud=alpha")
    assert "URL = 'https://sso.example.test/pf/heartbeat.ping'" in health and 'method="GET"' in health
    token = scripts["terraform/canaries/sso-token/python/canary.py"]
    assert f"SECRET_ID = '{SECRET}'" in token and '"grant_type": "client_credentials"' in token
    for text_ in scripts.values():
        ast.parse(text_)                                  # the scripts are Python


def test_one_role_lets_the_canaries_write_their_artifacts_and_read_their_secret():
    text = "\n".join(_render(ALIVE, TOKEN)[0])
    assert 'resource "aws_iam_role" "canaries" {' in text and "lambda.amazonaws.com" in text
    assert '\\"arn:aws:s3:::example-ciam-canaries/*\\",\\"arn:aws:s3:::example-ciam-canaries/alive/*\\"' in text
    assert '\\"Resource\\":[\\"arn:aws:s3:::example-ciam-canaries\\"]' in text
    assert "arn:aws:logs:*:*:log-group:/aws/lambda/cwsyn-ciam-sso-alive-*" in text
    assert '\\"Resource\\":[\\"' + SECRET in text and "CloudWatchSynthetics" in text


def test_what_a_canary_cant_reach_or_keep_is_named():
    hcl, scripts = _render(ALIVE.replace("ciamStorageRef: s3://example-ciam-canaries/alive/\n", ""))
    assert [x for x in hcl if x.startswith("#")] == [
        "# NOTE: canary intranet: not rendered: service name svc-admin isn't recorded as internet-facing: a canary "
        "outside a VPC can't reach it (canaries in a VPC aren't rendered yet)",
        "# NOTE: canary sso-alive: not rendered: its canary binding ciam-sso-alive records no S3 location for its "
        "artifacts (ciamStorageRef s3://bucket/prefix)",
        "# NOTE: canary sso-token: not rendered: no place for its artifacts: record its canary binding with an S3 "
        "location (ciamStorageRef s3://bucket/prefix)"]
    assert scripts == {} and not any("aws_iam_role" in x for x in hcl)
