# Generated by opsdir from env=stage,cloud=source,ou=environments,dc=ciam-ops
# AWS network kept by cloud-landing-zone for the CIAM platform: applied by them, not by the platform's pipeline
# Do not edit. Change the operations directory (under an approved change) and re-render.

data "aws_vpc" "main" {
  id = "vpc-0a1b2c3d4e5f67890"
}

data "aws_subnet" "subnet_am_a" {
  id = "subnet-0c77d88e99fa00b1a"
}

data "aws_subnet" "subnet_am_b" {
  id = "subnet-0c77d88e99fa00b1b"
}

data "aws_subnet" "subnet_ds_a" {
  id = "subnet-0a11b22c33d44e55a"
}

data "aws_subnet" "subnet_ds_b" {
  id = "subnet-0a11b22c33d44e55b"
}

data "aws_subnet" "subnet_ds_c" {
  id = "subnet-0a11b22c33d44e55c"
}

data "aws_subnet" "subnet_idm_a" {
  id = "subnet-0d88e99fa00b11c2a"
}

data "aws_subnet" "subnet_ig_a" {
  id = "subnet-0e99fa00b11c22d3a"
}

data "aws_subnet" "subnet_pf_a" {
  id = "subnet-0f66e77d88c99b00a"
}

data "aws_subnet" "subnet_pf_b" {
  id = "subnet-0f66e77d88c99b00b"
}

data "aws_eip" "egress_pf_0" {
  public_ip = "203.0.113.10"
}

resource "aws_nat_gateway" "egress_pf" {
  connectivity_type = "public"
  allocation_id     = data.aws_eip.egress_pf_0.id
  subnet_id         = var.egress_pf_subnet_id
  tags = {
    Name      = "egress-pf"
    Role      = "pf-egress"
    ManagedBy = "opsdir"
  }
}

import {
  to = aws_nat_gateway.egress_pf
  id = "nat-0123456789abcdef0"
}
