# Generated by opsdir from env=stage,cloud=source,ou=environments,dc=ciam-ops
# Providers and inputs (landing zone)
# Do not edit. Change the operations directory (under an approved change) and re-render.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.10"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

variable "account_id" {
  type        = string
  description = "The account stage runs in"
}

variable "guardrail_target_id" {
  type        = string
  description = "The organizational unit or account the guardrails attach to"
}

variable "egress_pf_subnet_id" {
  type        = string
  description = "The public subnet NAT gateway egress-pf sits in"
}
