"""PingDS adapter: render the directory domain as PingDS artifacts, on the DS-lineage base.

Environment-neutral (identical for every environment):  ldap/schema.ldif, ldap/dit.ldif, ds/dsconfig.batch,
                                                       ds/acis.ldif
Environment-specific (hostnames, peers, secret refs):   ds/setup-<server>.sh

Command and property names follow the PingDS 7.x documentation; verify them against the exact
target version before use.
"""
from opsdir.core.directory import one, rdn_value
from opsdir.core.environment import joins
from opsdir_base_ds.config import neutral_files
from opsdir_base_ds.product import DsProduct
from opsdir_base_ds.replication import REPLICATION_PORT, peer_ds_hosts
from opsdir_base_ds.setup import port, setup_inputs

PINGDS = DsProduct(
    name="PingDS", root_dn="uid=admin",
    dsconfig_apply=("# Apply: dsconfig --hostname <ds> --port 4444 --bindDN uid=admin --bindPasswordFile <file> \\",
                    "#          --usePkcs12TrustStore <truststore> --batchFilePath dsconfig.batch --no-prompt"),
    handler_names={})
SETUP_SECRET_ROLES = ("ds-deployment-id", "ds-deployment-password", "ds-root-password")


def _setup_script(m, x):
    joined = joins(m)
    how = f"joins the replication deployment of {joined.dn}" if joined else "new or existing deployment"
    bootstrap = " \\\n  ".join(f"--bootstrapReplicationServer {h}:{REPLICATION_PORT}" for h in x.peers)
    s = x.server
    return f"""#!/usr/bin/env bash
# Generated by opsdir for {rdn_value(s)} in {m.dn}
# {one(s, 'ciamProductVersion')}; {how}.
# Secrets are resolved at run time from references; no secret value is stored in this file.
# The TLS keystore (binding role ds-tls-keystore) is materialized by the secrets agent before this runs.
set -euo pipefail
DEPLOYMENT_ID={x.secrets['ds-deployment-id']}
DEPLOYMENT_ID_PASSWORD={x.secrets['ds-deployment-password']}
ROOT_PASSWORD={x.secrets['ds-root-password']}

./setup \\
  --serverId {rdn_value(s)} \\
  --deploymentId "$DEPLOYMENT_ID" \\
  --deploymentIdPassword "$DEPLOYMENT_ID_PASSWORD" \\
  --rootUserDn {PINGDS.root_dn} \\
  --rootUserPassword "$ROOT_PASSWORD" \\
  --hostname {one(s, 'ciamHostname')} \\
  --adminConnectorPort 4444 \\
  --ldapsPort {port(x.ports, 'LDAPS')} \\
  --httpsPort {port(x.ports, 'HTTPS')} \\
  --replicationPort {REPLICATION_PORT} \\
  {bootstrap} \\
  --profile ds-user-data \\
  --set ds-user-data/baseDn:{one(x.backend, 'ciamBaseDn')} \\
  --acceptLicense

# Then apply the environment-neutral configuration, in this order (indexes need the schema):
#   ldapmodify ... -f ../ldap/schema.ldif
#   ldapadd -c ... -f ../ldap/dit.ldif
#   dsconfig ... --batchFilePath ../ds/dsconfig.batch
#   ldapmodify ... -f ../ds/acis.ldif
"""


def setup_scripts(m, services):
    return {f"ds/setup-{rdn_value(x.server)}.sh": _setup_script(m, x)
            for x in setup_inputs(m, services, peer_ds_hosts(m.d, m), SETUP_SECRET_ROLES)}


def render_neutral(d):
    return neutral_files(PINGDS, d)
