"""PingDS adapter: render the directory domain as PingDS artifacts.

Environment-neutral (identical for every environment):  ds/dsconfig.batch, ds/acis.ldif
Environment-specific (hostnames, peers, secret refs):   ds/setup-<server>.sh

Command and property names follow the PingDS 7.x documentation; verify them against the exact
target version before use.
"""
from itertools import chain

from opsdir.core.directory import children, follow, get, one, rdn_value, subtree, values
from opsdir.core.environment import joins, secret, servers_with_role
from opsdir.domains.directory.naming import ACIS, DECLARED as DECL, DIRECTORY_SERVER_ROLE
from .replication import REPLICATION_PORT, peer_ds_hosts

BATCH_HEADER = ("# dsconfig batch file. Generated by opsdir from " + DECL,
                "# Environment-neutral: the same file is applied to every environment.",
                "# Apply: dsconfig --hostname <ds> --port 4444 --bindDN uid=admin --bindPasswordFile <file> \\",
                "#          --usePkcs12TrustStore <truststore> --batchFilePath dsconfig.batch --no-prompt", "")
# directory attribute → dsconfig password-policy property (optional ones)
POLICY_PROPS = (("ciamLockoutFailureCount", "lockout-failure-count"),
                ("ciamLockoutDuration", "lockout-duration"),
                ("ciamPasswordHistoryCount", "password-history-count"),
                ("ciamMaxPasswordAge", "max-password-age"))
SETUP_SECRET_ROLES = ("ds-deployment-id", "ds-deployment-password", "ds-root-password")


def _q(v):
    return f'"{v}"' if " " in v else v


def _index_line(d, be, ix):
    attr = one(follow(d, ix, "ciamIndexedAttribute"), "ciamLdapName")
    types = " ".join(f"--set index-type:{t}" for t in values(ix, "ciamIndexType"))
    return f"create-backend-index --backend-name {rdn_value(be)} --index-name {attr} {types}"


def _backend_lines(d, be):
    return (f"# backend {rdn_value(be)} ({one(be, 'ciamBaseDn')})",
            *(_index_line(d, be, ix) for ix in children(d, be.dn, "ciamIndex")), "")


def _policy_line(pp):
    props = (f"--set default-password-storage-scheme:{_q(one(pp, 'ciamStorageScheme'))}",
             "--set password-attribute:userPassword",
             *(f"--set {prop}:{_q(one(pp, attr))}" for attr, prop in POLICY_PROPS if one(pp, attr) is not None))
    return f'create-password-policy --policy-name "{rdn_value(pp)}" --type password-policy ' + " ".join(props)


def _handler_line(h):
    port = f" --set listen-port:{one(h, 'ciamListenPort')}" if one(h, "ciamListenPort") else ""
    return (f"set-connection-handler-prop --handler-name {rdn_value(h)} "
            f"--set enabled:{one(h, 'ciamEnabled').lower()}{port}")


def _publisher_line(lp):
    return f'set-log-publisher-prop --publisher-name "{rdn_value(lp)}" --set enabled:{one(lp, "ciamEnabled").lower()}'


def _replication_lines(d):
    topo = get(d, f"cn=topology,ou=replication,{DECL}")
    if not (topo and one(topo, "ciamReplicationPurgeDelay")):
        return ()
    return ("set-synchronization-provider-prop --provider-name \"Multimaster Synchronization\" "
            f"--set replication-purge-delay:{_q(one(topo, 'ciamReplicationPurgeDelay'))}",)


def dsconfig_batch(d):
    lines = (*BATCH_HEADER,
             *chain.from_iterable(_backend_lines(d, be) for be in subtree(d, f"ou=backends,{DECL}", "ciamBackend")),
             *(_policy_line(pp) for pp in children(d, f"ou=password-policies,{DECL}", "ciamPasswordPolicy")), "",
             *(_handler_line(h) for h in children(d, f"ou=connection-handlers,{DECL}", "ciamConnectionHandler")),
             *(_publisher_line(lp) for lp in children(d, f"ou=log-publishers,{DECL}", "ciamLogPublisher")),
             *_replication_lines(d))
    return "\n".join(lines) + "\n"


def _aci_target(d, aci):
    if one(aci, "ciamAciAllAttributes") == "TRUE":
        return "*"
    return " || ".join(one(get(d, a), "ciamLdapName") for a in values(aci, "ciamAciTargetAttr"))


def _aci_warnings(aci, target):
    checks = (("no owner", not one(aci, "ciamOwner")),
              ("no justification", not one(aci, "ciamJustification")),
              ("targetattr=* (all attributes)", target == "*"))
    return tuple(w for w, failed in checks if failed)


def _aci_lines(d, aci):
    target = _aci_target(d, aci)
    users = " || ".join(f"ldap:///{one(get(d, g), 'ciamBindDn')}" for g in values(aci, "ciamAciGrantee"))
    rights = ",".join(values(aci, "ciamAciRight"))
    warn = _aci_warnings(aci, target)
    return ((f"# WARNING {rdn_value(aci)}: " + ", ".join(warn),) if warn else ()) + (
        f"dn: {one(aci, 'ciamAciTargetDn')}", "changetype: modify", "add: aci",
        f'aci: (targetattr = "{target}")(version 3.0; acl "{rdn_value(aci)}"; '
        f'allow ({rights}) userdn = "{users}";)', "")


def acis_ldif(d):
    head = (f"# ACIs for the user directory. Generated by opsdir from {ACIS}.",
            "# Environment-neutral. Apply with ldapmodify under change control.", "")
    body = chain.from_iterable(_aci_lines(d, aci) for aci in children(d, ACIS, "ciamAci"))
    return "\n".join((*head, *body))


def _secret_expr(m, services, role):
    uri = secret(m, role)
    return f'"$({services.secret_command(uri)})"' if uri else f'"${{UNBOUND_{role.upper().replace("-", "_")}}}"'


def _setup_script(m, s, be, ports, peers, secrets):
    joined = joins(m)
    how = f"joins the replication deployment of {joined.dn}" if joined else "new or existing deployment"
    bootstrap = " \\\n  ".join(f"--bootstrapReplicationServer {h}:{REPLICATION_PORT}" for h in peers)
    return f"""#!/usr/bin/env bash
# Generated by opsdir for {rdn_value(s)} in {m.dn}
# {one(s, 'ciamProductVersion')}; {how}.
# Secrets are resolved at run time from references; no secret value is stored in this file.
# The TLS keystore (binding role ds-tls-keystore) is materialized by the secrets agent before this runs.
set -euo pipefail
DEPLOYMENT_ID={secrets['ds-deployment-id']}
DEPLOYMENT_ID_PASSWORD={secrets['ds-deployment-password']}
ROOT_PASSWORD={secrets['ds-root-password']}

./setup \\
  --serverId {rdn_value(s)} \\
  --deploymentId "$DEPLOYMENT_ID" \\
  --deploymentIdPassword "$DEPLOYMENT_ID_PASSWORD" \\
  --rootUserDn uid=admin \\
  --rootUserPassword "$ROOT_PASSWORD" \\
  --hostname {one(s, 'ciamHostname')} \\
  --adminConnectorPort 4444 \\
  --ldapsPort {ports.get('LDAPS', 1636)} \\
  --httpsPort {ports.get('HTTPS', 8443)} \\
  --replicationPort {REPLICATION_PORT} \\
  {bootstrap} \\
  --profile ds-user-data \\
  --set ds-user-data/baseDn:{one(be, 'ciamBaseDn')} \\
  --acceptLicense

# Then apply the environment-neutral configuration:
#   dsconfig ... --batchFilePath ../ds/dsconfig.batch
"""


def setup_scripts(m, services):
    d = m.d
    be = subtree(d, f"ou=backends,{DECL}", "ciamBackend")[0]
    ports = {rdn_value(h): one(h, "ciamListenPort") for h in children(d, f"ou=connection-handlers,{DECL}")}
    peers = peer_ds_hosts(d, m)
    secrets = {role: _secret_expr(m, services, role) for role in SETUP_SECRET_ROLES}
    return {f"ds/setup-{rdn_value(s)}.sh": _setup_script(m, s, be, ports, peers, secrets)
            for s in servers_with_role(m, DIRECTORY_SERVER_ROLE)}


def render_neutral(d):
    return {"ds/dsconfig.batch": dsconfig_batch(d), "ds/acis.ldif": acis_ldif(d)}
