"""OpenDJ adapter: render the directory domain as OpenDJ artifacts, on the DS-lineage base.

Environment-neutral (identical for every environment):  ldap/schema.ldif, ldap/dit.ldif, ds/dsconfig.batch,
                                                       ds/acis.ldif
Environment-specific (hostnames, peers, secret refs):   ds/setup-<server>.sh (setup, then dsreplication)

OpenDJ has no deployment ID: a new replica joins the replication topology through an existing replica
(`dsreplication enable`) and is initialized from it. Command and option names follow the OpenDJ 4.x
documentation; verify them against the exact target version before use.
"""
from opsdir.core.directory import one, rdn_value
from opsdir.core.environment import joins
from opsdir_base_ds.config import neutral_files
from opsdir_base_ds.product import DsProduct
from opsdir_base_ds.replication import REPLICATION_PORT, joined_ds_hosts
from opsdir_base_ds.setup import ADMIN_PORT, directory_servers, port, setup_inputs

OPENDJ = DsProduct(
    name="OpenDJ", root_dn="cn=Directory Manager",
    dsconfig_apply=(f'# Apply: dsconfig --hostname <ds> --port {ADMIN_PORT} --bindDN "cn=Directory Manager" '
                    "--bindPasswordFile <file> \\",
                    "#          --trustStorePath <truststore> --batchFilePath dsconfig.batch --no-prompt"),
    handler_names={"LDAP": "LDAP Connection Handler", "LDAPS": "LDAPS Connection Handler",
                   "HTTPS": "HTTP Connection Handler"},
    builtin_policies=("Default Password Policy", "Root Password Policy"))
SETUP_SECRET_ROLES = ("ds-root-password", "ds-replication-admin-password")


def replication_source(m, server):
    """The existing replica a new one joins through: the first directory server of the environment it joins, else
    the first of its own environment's (which the others join); None for the first replica of a new topology."""
    theirs = joined_ds_hosts(m.d, m)
    own = tuple(one(s, "ciamHostname") for s in directory_servers(m))
    host = one(server, "ciamHostname")
    candidates = theirs or own[:own.index(host)]
    return candidates[0] if candidates else None


def _replication(x, source, base):
    host = one(x.server, "ciamHostname")
    if not source:
        return ("# First replica of a new topology: nothing to join. "
                "The next replica enables replication with this one.\n")
    admin = ('  --trustStorePath "$DS_TRUSTSTORE" \\\n'
             '  --adminUID admin --adminPassword "$REPLICATION_ADMIN_PASSWORD" \\\n'
             f"  --baseDN {base} \\\n")
    return f"""# Join the replication topology through {source}, then initialize this replica from it.
./bin/dsreplication enable --no-prompt \\
{admin}  --host1 {source} --port1 {ADMIN_PORT} --bindDN1 "{OPENDJ.root_dn}" --bindPassword1 "$ROOT_PASSWORD" \\
  --replicationPort1 {REPLICATION_PORT} \\
  --host2 {host} --port2 {ADMIN_PORT} --bindDN2 "{OPENDJ.root_dn}" --bindPassword2 "$ROOT_PASSWORD" \\
  --replicationPort2 {REPLICATION_PORT}
./bin/dsreplication initialize --no-prompt \\
{admin}  --hostSource {source} --portSource {ADMIN_PORT} \\
  --hostDestination {host} --portDestination {ADMIN_PORT}
"""


def _setup_script(m, x):
    joined = joins(m)
    how = f"joins the replication topology of {joined.dn}" if joined else "new or existing topology"
    s, base = x.server, one(x.backend, "ciamBaseDn")
    return f"""#!/usr/bin/env bash
# Generated by opsdir for {rdn_value(s)} in {m.dn}
# {one(s, 'ciamProductVersion')}; {how}.
# Secrets are resolved at run time from references; no secret value is stored in this file.
# The TLS keystore (binding role ds-tls-keystore) is materialized by the secrets agent before this runs:
# $DS_KEYSTORE (PKCS#12) with its PIN in $DS_KEYSTORE_PIN_FILE, and the CA truststore $DS_TRUSTSTORE.
# Every replica of a topology shares the root and replication-administrator passwords.
set -euo pipefail
ROOT_PASSWORD={x.secrets['ds-root-password']}
REPLICATION_ADMIN_PASSWORD={x.secrets['ds-replication-admin-password']}

./setup --cli --no-prompt --acceptLicense \\
  --hostname {one(s, 'ciamHostname')} \\
  --rootUserDN "{OPENDJ.root_dn}" \\
  --rootUserPassword "$ROOT_PASSWORD" \\
  --adminConnectorPort {ADMIN_PORT} \\
  --ldapPort {port(x.ports, 'LDAP')} \\
  --ldapsPort {port(x.ports, 'LDAPS')} \\
  --usePkcs12keyStore "$DS_KEYSTORE" \\
  --keyStorePasswordFile "$DS_KEYSTORE_PIN_FILE" \\
  --baseDN {base} \\
  --backendType {one(x.backend, 'ciamBackendType')}

{_replication(x, replication_source(m, s), base)}
# Then apply the environment-neutral configuration, in this order (indexes need the schema):
#   ldapmodify ... -f ../ldap/schema.ldif
#   ldapadd -c ... -f ../ldap/dit.ldif
#   dsconfig ... --batchFilePath ../ds/dsconfig.batch
#   ldapmodify ... -f ../ds/acis.ldif
"""


def setup_scripts(m, services):
    return {f"ds/setup-{rdn_value(x.server)}.sh": _setup_script(m, x)
            for x in setup_inputs(m, services, (), SETUP_SECRET_ROLES)}


def render_neutral(d):
    return neutral_files(OPENDJ, d)
